### ISSUE TITLE
Reset slider (clear)

### ISSUE THREAD

**Issue by jmrichardson** [seiyria/bootstrap-slider#105]
Hello,

Thanks for the great plugin!  How do you reset the initial values back to original values?  Form reset doesn't work.  I would like to reset the slider to its original visual state.  

Thanks,
John

**Comment by Zumochi** [comment]
:+1: looking for this feature.

**Comment by gordon-matt** [comment]
Upvote! Please add this! In the meantime, is there any way at all (any hack) to programatically set the slider back to its default state? When i tried the following, it does nothing:

var defaultValue = '[' + minValue + ',' + maxValue + ']';
$("#MySlider").slider('setValue', defaultValue);

I get an error like: "Invalid input value '[2.39,6.04]' passed in"

**Comment by seiyria** [comment]
Try setting it as an array literal instead of a string. It doesn't parse
values.

**Comment by gordon-matt** [comment]
That did it, thank you!
