### ISSUE TITLE
conflict with jquery-ui slider function

### ISSUE THREAD

**Issue by gad2103** [seiyria/bootstrap-slider#132]
hi there. please consider changing the name of this plugin. i am having a collision with the jquery ui slider. i can't get it working. i tried renaming the plugin in the plugin file but it isn't working. i'm getting undefined is not a function error.

thanks

**Comment by DaveSauce** [comment]
I'm having the same problem, for what it's worth.

**Comment by seiyria** [comment]
The plugin has been re-written to only optionally use jQuery, so you should be fine now.

**Comment by rovolution** [comment]
This problem was solved quite some time ago.

Please read through the __Using bootstrap-slider (with JQuery)__ section of our README

**Comment by DaveSauce** [comment]
Awesome, thanks!
