### ISSUE TITLE
Right mouse click on slider has undesired behaviour

### ISSUE THREAD

**Issue by roelvermeulen** [seiyria/bootstrap-slider#138]
Right clicking on most HTML elements such as buttons, checkboxes, etc. brings up the context menu and doesn't activate the element. However on the slider it changes the value. The following code in the mousedown function should fix the problem:

```
var isRightMB;
ev = ev || window.event;

if ("which" in ev)  // Gecko (Firefox), WebKit (Safari/Chrome) & Opera
    isRightMB = ev.which == 3; 
else if ("button" in e)  // IE, Opera 
    isRightMB = ev.button == 2; 
if (isRightMB)
    return false;
```

Regards

**Comment by simevo** [comment]
Three years on, it seems that [MouseEvent.button](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) is supported everywhere so the patch would be:
```
var isRMB;
var e = e || window.event;
if ('object' === typeof e) {
  var btnCode;
  btnCode = e.button;
  isRMB = (btnCode == 2);
}
if (isRMB)
  return false;
```
For a quick check, I have inserted this code in `dist/bootstrap-slider.js` at line 1421 and it seems to work. Are you still interested in a PR ?
