### ISSUE TITLE
React.js component

### ISSUE THREAD

**Issue by rovolution** [seiyria/bootstrap-slider#142]
Hey @seiyria 

Since we are adding in examples of integrating the slider into various JavaScript MV/MVVC frameworks, I was thinking it would be awesome to have a component for React.js.

I've started using it in a work-project and its pretty sick!

**Comment by seiyria** [comment]
https://github.com/jarsbe/react-bootstrap-slider I found this, it looks like someone started on this already.

**Comment by rovolution** [comment]
thats awesome!v I am thinking that it might be time for us to create a GH organization and move all of the repos into there. Thoughts?

**Comment by seiyria** [comment]
I don't disagree with you, but as I noted above, I have no idea how to move the bower endpoint (and now the npm endpoint), if I can at all. If we can figure that out, then we should be fine.
