### ISSUE TITLE
tick mark enhancements

### ISSUE THREAD

**Issue by seiyria** [seiyria/bootstrap-slider#158]
The tick marks could use a little bit of work. Here are the options I forsee being useful:

`tickPosition`: either top, bottom, middle, or all. top tickmarks will be on the top of the slider, bottom will be on the bottom, middle will be the current behavior, and all will be top, middle, and bottom.

`tickMarks`: pass an array as well - this array would contain the percentage at which the tickMark should be drawn.

`tickLabels`: boolean - label the tick marks with their value. This would probably also have to have some staggering depending on how close the labels are.

This post will be updated as more suggestions materialize.

**Comment by MelleB** [comment]
See #296
