### ISSUE TITLE
Show slider after initially hidden

### ISSUE THREAD

**Issue by levivoelz** [seiyria/bootstrap-slider#162]
There's an issue with the tooltip position when a container around the slider is initially set to `display: none` and then revealed via `$("#container").show()`, or by adding an `active` class to the container that has a `display:block` attribute.

http://jsfiddle.net/levivoelz/RSGjY/

![screen shot 2014-06-18 at 3 13 22 pm](https://cloud.githubusercontent.com/assets/1270610/3321371/7943556c-f736-11e3-8f0c-e318e175692b.png)

![screen shot 2014-06-18 at 3 18 42 pm](https://cloud.githubusercontent.com/assets/1270610/3321379/8b3ce1ac-f736-11e3-8653-26ab43410354.png)

**Comment by seiyria** [comment]
I would need an updated case to show that this is still a problem.

**Comment by lessaworld** [comment]
This seems to be still an issue with Bootstrap 4. Here's the solution that worked for me. 

$('#myModal').on('shown.bs.modal', function (event) {
  setTimeout(function() {
      $('input[name=sliderName]').slider('relayout');
  }, 0);
})

where myModal and sliderName can be seen in the following example snippet.


<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <h4 class="modal-title">Modal Heading</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      
      <div class="modal-body">
            <div class="form-group">          
              <span>Min Value</span>
			  <input
              	type="text"
              	name="sliderName"
              	data-provide="slider"
...
