### ISSUE TITLE
Tooltip value on click

### ISSUE THREAD

**Issue by Flower7C3** [seiyria/bootstrap-slider#166]
When I change the point position by single click (not move) the value of tooltip is not updating. When I click again in any position I can see the last value of slider. To fix this call `this.layout();` in `mouseup` function just before `var val = this.calculateValue();`.

**Comment by rdraviteja** [comment]
$(document).ready(function(){
$('.slider-track').click(function(){
var sliderval = $('.tooltip-inner').html();
$("#dSAnalysisSliderValue").text(sliderval);
});
});

HTML: Add a span element with id - dSAnalysisSliderValue

**Comment by explooosion** [comment]
Hi, I use this way to handle.

// With JQuery
   $("#ex6").slider().on("slide", function (slideEvt) {
     $("#ex6SliderVal").text(slideEvt.value);
   }).on("change", function (slideEvt) {
     console.log(slideEvt.value.newValue);
   });

**Comment by cromartie1984** [comment]
if you have tick snaps, it does not snap to these values when you click on the slider. Has anyone been able to do this ?

**Comment by mohitjangid21** [comment]
I have been using the following code but the value doesn't change on click, value only changes when it slides,

$('#accuracySlider').slider({
                formatter: function (value) {

                    return 'Current value: ' + value;
                }
            });
            $('.span2').slider().on('slideStop', function (ev) {

                var newVal = $('.span2').data('slider').getValue();
                $('#accuracyValue').val(newVal);

            });

Can anybody please help?

**Comment by criger** [comment]
> Hi, I use this way to handle.
> 
> // With JQuery
> $("#ex6").slider().on("slide", function (slideEvt) {
> $("#ex6SliderVal").text(slideEvt.value);
> }).on("change", function (slideEvt) {
> console.log(slideEvt.value.newValue);
> });

I experienced this issue now, and while the solution provided by Flower7C3 didn't work, this one did.

*kudos* :)
