### ISSUE TITLE
'slideStop' event lost after jQuery.clone

### ISSUE THREAD

**Issue by angel1st** [seiyria/bootstrap-slider#192]
I have successfully created slider and bind function to `slideStop` event - so far so good. The slider works just fine. 
At specific point I need to copy a `<div>` - from one source `<div>` to another destination `<div>`. As you can guess within the source div I have bootstrap slider, buried few levels beneath the source. I use jQuery to clone the source div, using following command:
`$(sourceDivContent).clone(true, true).appendTo(destDiv);`

The clone process is successful and entire sourceDiv content is cloned to `destDiv`, including "standard" event handlers (e.g. click, hover and etc.), however `slideStop` is missing, thus the slider stops to work.

**Comment by tunacon** [comment]
@angel1st Can you suggest me about the solution to work around this?
