### ISSUE TITLE
Unaligned tooltip on Firefox

### ISSUE THREAD

**Issue by oesgalha** [seiyria/bootstrap-slider#205]
The tooltip is unaligned on Firefox 32.0.1 (newest one) when using bootstrap-slider >= 4.0.

If you visit the [demo page](http://seiyria.github.io/bootstrap-slider/) with Firefox and hover on the first slider you'll see it.
Here are some screenshots:
<img src="http://i.imgur.com/DLV2YkY.png"></img>
<img src="http://i.imgur.com/9umf1Bm.png"></img>

This behavior doesn't occur on Chrome or when bootstrap-slider 3.x is used.

**Comment by seiyria** [comment]
Either in a newer version of firefox or bootstrap-slider, this has been fixed.
