### ISSUE TITLE
Logarithmic Slider

### ISSUE THREAD

**Issue by rickyvetter** [seiyria/bootstrap-slider#210]
Would be nice to have options for scaling the slider - logarithmic, exponential, etc.

**Comment by maxpsq** [comment]
I'd love it too !

**Comment by MelleB** [comment]
Please see pull request #302

**Comment by rovolution** [comment]
This is now a feature thanks to @MelleB! Check out Ex 15 on out github.io page!

**Comment by seiyria** [comment]
+100!
