### ISSUE TITLE
Events are triggered twice

### ISSUE THREAD

**Issue by daveshapiro** [seiyria/bootstrap-slider#216]
When attaching events (I assume all, but only tested with slideStop) using the built-in "on" (ie: ```elem.slider("on", "slideStop", func)```), the events get triggered twice.  I traced the issue down to the following bit of logic:

```
_triggerJQueryEvent: function(evt, val) {
	var eventData = {
		type: evt,
		value: val
	};
	this.$element.trigger(eventData);
	this.$sliderElem.trigger(eventData); // This second trigger causes the event to be triggered twice
},
```

**Comment by Badspeed** [comment]
Bump, is there any workaround for this ?

**Comment by seiyria** [comment]
This is no longer relevant.
