### ISSUE TITLE
Feature request: option to show value on the handle rather than a tooltip

### ISSUE THREAD

**Issue by will-e-yams** [seiyria/bootstrap-slider#237]
Example:

![image](https://cloud.githubusercontent.com/assets/5280307/4669698/5aefd516-5570-11e4-9729-b698e6970268.png)

**Comment by gviger** [comment]
+1

**Comment by seiyria** [comment]
Thinking about this more, the only real problem is for excessively large values. I'm not certain of the feasibility of doing so in that case.

**Comment by will-e-yams** [comment]
good point, but i say let that be the dev's problem.

**Comment by gviger** [comment]
I agree let the dev decide. However if a bootstrap badge class was wrapped around the the indicator it would be style consistent and probably address your concerns about size. Not sure how easy that would be to do though.

**Comment by seiyria** [comment]
I've thought about this even more and I'm going to close this. No other slider that I've used recently does this, and it would be sufficiently noisy to do so, especially given the case of numbers being of any size.
