### ISSUE TITLE
Tooltip always on for a range slider. 

### ISSUE THREAD

**Issue by Lucy83** [seiyria/bootstrap-slider#238]
I can't make tooltip always on for a range slider. Is it possible? If not, are you planning on add that function in future?

Also do you think it'd be better to have for a range slider two separate tooltips on each marker rather than one combined tooltip displaying current selection (currently there is a tool tip having 200:500 value).

**Comment by cjbutcher** [comment]
I also had a problem with tooltips not always showing, even when using the 'tooltip: always' option. I had to change the "if (tooltip == 'show')" part to read (around about line 139):

		if (tooltip === 'show') {
			this.picker.on({
				mouseenter: $.proxy(this.showTooltip, this),
				mouseleave: $.proxy(this.hideTooltip, this)
			});
		} else if (tooltip === 'always') {
			this.showTooltip();
			this.alwaysShowTooltip = true;
		} 
		else {
			this.tooltip.addClass('hide');
		}

**Comment by seiyria** [comment]
This should be correct now, given the rewrite that happened later last year.
