### ISSUE TITLE
Feature request: change event

### ISSUE THREAD

**Issue by will-e-yams** [seiyria/bootstrap-slider#239]
From my tests, moving the slider doesn't raise the change event. Form validation coding would be much simpler if this were added. As and example, I'm monitoring this way:

```
$('input.slider').on('change', function() {
    // do something
})
```

I noticed that the original input element is gone in the markup and I'm guessing I might be able to add the change event to the `div` created that does all the work. If that's the case, just let me know.

**Comment by onesneakymofo** [comment]
Can some show me an example of this? It's not working for me.

**Comment by seiyria** [comment]
We'd need a jsfiddle, @onesneakymofo to see what you're currently doing.
