### ISSUE TITLE
Possible animation when setValue

### ISSUE THREAD

**Issue by dukevomv** [seiyria/bootstrap-slider#258]
I would like to know if there is any possible way to change the slider value when i press a button but not just to move the handler to its new position, I'd like to animate/slide on its own to the new value.

**Comment by drosendo** [comment]
Possile animation, working for me for what I need.
``` 
$('input.rangeslider').slider();
$('.slider-selection').hide();
$('.col-lg-9 .slider-selection').each(function (i, v) {
    var grow_original = $(this).css('width')
    $(this).css('width', '0');
    $(this).show();
    $(this).delay(100 * i).animate({width: grow_original}, 500);
});
```
