### ISSUE TITLE
Slider over an ordinal scale

### ISSUE THREAD

**Issue by seiyria** [seiyria/bootstrap-slider#26]
Make scale able to be an array of values, ie, [Jan, Feb, Mar, Apr, ... Nov, Dec].

**Comment by Khrysller** [comment]
Thanks @jkrehm, sorry for the very late response.
Why this is closed? There is a way to do a Month/Year range? Thanks.

**Comment by rovolution** [comment]
@Khrysller i have no idea why we closed this haha!

But if you want to try to implement a date sliding concept, you could use the `formatter` function to have numeric values that map to certain date strings

**Comment by yidingalan** [comment]
@rovolution is the date sliding concept implemented yet?

**Comment by seiyria** [comment]
@yidingalan as suggested, you can implement this yourself with the formatter function.

**Comment by yidingalan** [comment]
@seiyria Thanks for responding. Is there a cap limit for the integer input for `value` and `min max`? I converted my datetime value into integer from Rails side, and when I plug into the slider, the value is set to default `10:10`. Did I hit the limit?

**Comment by seiyria** [comment]
There is no such limit. I can't say what could be going wrong unless you have a jsfiddle to look at. If you continue to have issues please open a new one.
