### ISSUE TITLE
Multiple custom sliders

### ISSUE THREAD

**Issue by paulgration** [seiyria/bootstrap-slider#263]
I've been using bootstrap-slider recently (which is great) but found a situation where I needed multiple custom sliders which differ in appearance on a single page, e.g. an audio mixer where you have multiple faders of different colours / styles.
Unfortunately I found that I couldn't just use an arbitrary style for the data-slider-handle attribute, and that it only worked using a value of "custom" meaning you could only define one custom style. Looking through the source I found this line: https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L443 which seems to restrict the accepted value of the handle to 'round', 'triangle' or 'custom'. Is there any reason this could not perform the acceptable value check and allow any css class definition?

To workaround this and save modifying the the bootstrap-slider code for the project I'm working on I am applying the custom classes to the handles once the sliders are initialised.

**Comment by jeyakrishnanp** [comment]
Hi - When I try this not working for me, my goal is to apply my own symbol on the tick handles(glyphicon glyphicon-bell)

**Comment by seiyria** [comment]
It'd be helpful if you showed us a jsfiddle of what you're trying to do. Depending on how different your issue is from this one, it might make sense to open a new issue instead.

**Comment by jeyakrishnanp** [comment]
Here I'm attaching simple slider with ticks handle, I would like to change my own tick handle instead of round

http://jsfiddle.net/aprrq169/

**Comment by seiyria** [comment]
Sorry, I think that is definitely a separate issue than this one, and it's definitely not supported implicitly by the library. You could try setting the CSS `content` of the handle but past that I'm not sure how well this feature would work.
