### ISSUE TITLE
Is it possible to use bootstrap slider to select more than 3 ranges?

### ISSUE THREAD

**Issue by xujiajun** [seiyria/bootstrap-slider#271]
Hello,
   We have a requirement, where we were earlier using 5 different sliders,but now we want to try and see if we can somehow merge them into one slider itself.

like this |----O----O------O-----O-------|

i google question like this http://stackoverflow.com/questions/22814074/bootstrap-slider-with-3-or-more-handles
Any help would be awesome.

**Comment by jthrilly** [comment]
I actually have a use case for this, too. 

I think in general you're correct that supporting N ranges would be silly, but supporting 4 or 5 makes a lot of sense as a top limit.

In my case the slider interface is large, full width, and high enough fidelity to be intelligible with more than three segments. I am using the slider within a survey to allow users to indicate proportions of between two and four properties that collectively add up to 100%, and this is definitely the best UI component for that.

Would you consider increasing the limit? I am happy to do the work if you could briefly outline where in the source I should start.

**Comment by seiyria** [comment]
The thing is, I think to make this successful you would have to make it so slider knobs can't cross each other (which they currently can).

That said, if you want to work on this (and I would wait for @rovolution's input first), I would be ok with it provided you:
 * add unit tests
 * add documentation
 * make the code robust enough to support N slider knobs
 * add a sufficient amount of options around this (the ones I can think off offhand: starting slider positions (array), slider track colors (array), allowCrossing (bool, default false for this))

As for where, I would look into how range sliders currently work (just ctrl-f range and work out the options pertaining to those)

**Comment by rovolution** [comment]
@jthrilly if you want to add this feature in, by all means go ahead and do so. just make sure to follow the guidelines as listed by @seiyria

**Comment by ascourtas** [comment]
@jthrilly was this implemented? I don't see anything in the documentation about it.

**Comment by jthrilly** [comment]
Nope, I didn't have time to add the functionality.
