### ISSUE TITLE
Tooltip displaying too high above slider

### ISSUE THREAD

**Issue by bradlis7** [seiyria/bootstrap-slider#273]
![image](https://cloud.githubusercontent.com/assets/7062604/5558285/abd1d580-8ce6-11e4-8f0d-aca16f1f551a.png)

The tooltip is showing too high. I think the CSS had a margin-top:-36px and then it's setting top:-30px in the Javascript. If you do one or the other, it would work fine, but doing both makes it display too high. Using master branch from yesterday.

Tested in Chrome and IE, and both are having the issue.

**Comment by PopeOnARope** [comment]
If you inspect on the demo page, you will see this happening in example 2, even when the tooltips are hidden. Noticed in firefox and chrome. 
![screen shot 2015-01-21 at 11 11 17 am](https://cloud.githubusercontent.com/assets/6982830/5839762/6a0d3360-a15e-11e4-9060-2976034fd650.png)
