### ISSUE TITLE
Lagginess

### ISSUE THREAD

**Issue by ksnyde** [seiyria/bootstrap-slider#278]
I have written a very simple Ember component which wraps your slider but to my great dismay it appears to have substantial "lagginess" (for lack of a better word). 

- Here's a short video of this behaviour: [video](http://www.screencast.com/t/ot8cdqNf0). 
- You can also try it out for yourself here: [demo](http://development.ui-slider-input.divshot.io/). 
- Finally, if you want to see the source and how simple my wrapper is you can find it here: [source](https://github.com/lifegadget/ui-slider-input/tree/e7ea781ff57229def4aed7d582107e2ef4fe6f5f/app/components)

I'm using the latest version of your code (that's available on Bower).

**Comment by seiyria** [comment]
It seems to perform fine for me. The behaviour you're seeing is likely the hitbox being very large.

**Comment by ksnyde** [comment]
My demo worked fine for you? Sorry to ask a silly question but what is the "hitbox"? For me there is a very clear and distinct difference from the samples on your demo page and my demo page.

**Comment by seiyria** [comment]
Yes, it worked just fine. It seems it's not the hitbox (ie, the area you can hit it and have it react to you) -- however, I find that in a lot of draggable things, if you drag and your mouse is not on them, the draggable thing will follow your cursor even if it's not directly touching. I believe this is a UX thing so people don't have to be pixel-perfect, but I'm not sure. A lot of jQuery draggable components do it, too, if I remember right.

As such, I don't think this is a huge problem, but I'll leave it open in case @rovolution has an idea about it.

**Comment by ksnyde** [comment]
what browser did you use? Here's a quick comparison on Chrome (OSX)

[video](http://www.screencast.com/t/B3JzMi4qXpM)

BTW, my computer has a good graphics card, lots of memory, and generally good karma so I'd not expect this kind of lagginess but I'm no expert on draggable content. :(

**Comment by ksnyde** [comment]
Also, this behaviour can be found w/o dragging. Just clicking missing the target.

**Comment by seiyria** [comment]
Chrome on Windows and Ubuntu.

**Comment by ksnyde** [comment]
I have exactly the same experience on Firefox, Safari, and Chrome. It works on your page, it misses the target on mine. If you don't have any other thoughts I guess I'll close this as it is more my issue than yours.

**Comment by rovolution** [comment]
yea i tried this on the latest versions of Chrome and FF and didn't experience anything unusual

**Comment by ksnyde** [comment]
Wow ... so strange. I have now tested it on my iPad, my iPhone, my laptop and my home computer. They all behave as I have experienced it. I really wish I could get the correct behaviour out. I am in shock that it seems to work for both of you.
