### ISSUE TITLE
Change tooltip value as I drag

### ISSUE THREAD

**Issue by SantechDev** [seiyria/bootstrap-slider#280]
Hi,

I was just wondering how I could change the value the tooltip is displaying when I drag the slider?

Basically I have a slider with a range of minutes, from 15 to 600, with increments of 15. I want to display "15min" if the value is at 15, and "1h15min" if the value is at 75.

I've already made an angular filter for the change of value, I just need to know how to apply it the the tooltip value.

Cheers

**Comment by seiyria** [comment]
Use the formatter function?
