### ISSUE TITLE
Add a prefix to value

### ISSUE THREAD

**Issue by jimmyphong** [seiyria/bootstrap-slider#281]
can be add prefix to value example fontsize px
and default value is px !

Thanks i wanna using slider for fontsize range !

**Comment by seiyria** [comment]
I have no idea what you're asking here. Can you clarify please?

**Comment by jimmyphong** [comment]
ex : <input type="text" name="fontsize" value="20px" data-slider-min="14px" data-slider-max="30px" data-slider-step="2px">

my mean add "px" prefix to value ! 
do you undestand me !! :+1:

**Comment by seiyria** [comment]
Sure, use the formatter function parameter.

**Comment by jimmyphong** [comment]
$(el).slider({
				formatter: function(value) {
					return value + 'px';
				}
			});

function formatter only format to show in tooltip only this not return a + "px" in input value !

**Comment by seiyria** [comment]
To do that, you're going to have to do some transformation by setting the variable elsewhere, ie, watch the slider event `change` and then output the resulting variable wherever you want it.

**Comment by jimmyphong** [comment]
Thanks @seiyria !
              $(el).on('slideStop',function(e){
			v = $(el).slider('getValue');
			$(el).val(v + 'px');
		});

when slide ,the value update awesome with "px" in value atrrattribute !
so when first load , input value is interger too, im try to set default value with "px" prefix
                $(el).val('16px');

but not work !

**Comment by seiyria** [comment]
Because the value has to be an integer. You simply can't do that. You have to format the value coming out of the slider; you can't format it when it's going in. In short, you would want to set it to 16, and format it everywhere else.

**Comment by jimmyphong** [comment]
Okie !! Thanhks @seiyria
