### ISSUE TITLE
Example 9 - precision needs float step

### ISSUE THREAD

**Issue by adamjakab** [seiyria/bootstrap-slider#285]
hi, I noticed that this example on http://seiyria.github.io/bootstrap-slider/ even though has a default value as float, when you use the slider the data-slider-step is 1 so it does not show well that slider supports float values. You should set the "data-slider-step"="0.1" or the step:0.1 option when initing the plugin.

**Comment by adamjakab** [comment]
sorry, I just noticed this as well - on your readme.md (master branch)  the docs talk about a "tooltip_separator" option wchich I think is now superseeded by the formatter option - in fact in js/bootstrap-slider.js there is no such thing as "tooltip_separator".

**Comment by seiyria** [comment]
Updates have been made and this seems to be correct now.
