### ISSUE TITLE
_offset computation does not take into account css transforms of parents

### ISSUE THREAD

**Issue by sebtoun** [seiyria/bootstrap-slider#286]
When a parent is positionned using css transform property, it's offset is not taken into account when computing offset property (_offset method). As a result, sliders handler are not correctly positionned. Particularly it prevents the use of both iScroll library and bootstrap-slider as iScroll use css transform if available to implement smooth scroll.

**Comment by sebtoun** [comment]
[Here](http://jsfiddle.net/zefkc1rw/) is a jsfiddle showing the issue: scroll a bit and try to move the slider.

**Comment by seiyria** [comment]
Is this fixed now, with your PR #286?
