### ISSUE TITLE
Rulers

### ISSUE THREAD

**Issue by fcferreira29** [seiyria/bootstrap-slider#290]
Is there a way to create rulers in the slider?

since i have been working with the slider, my boss asked me to put a ruler in the middle of the slider,

ex: 0 - 100 (he wants to have a marker in 50)

Thanks,

Fabio Ferreira

i want to do something like this
(http://www.jqueryrain.com/?jpubA5it)

**Comment by seiyria** [comment]
No. See #80, #157, and #158. I tried to implement this but it looked terrible.
