### ISSUE TITLE
Insert Dropdown to choose number (above Slider)

### ISSUE THREAD

**Issue by fcferreira29** [seiyria/bootstrap-slider#291]
Also,

we would like to include something like this,

http://jqueryui.com/slider/#hotelrooms

because there are persons that have user usabilities issues, so we would like to insert this sort of dropdown or eaven a input text box to insert a value,

is there a way to do it?

thanks,

Fabio Ferreira

**Comment by seiyria** [comment]
I don't see why not. Just add a dropdown, and when it changes, change the slider.

**Comment by fcferreira29** [comment]
I tried to change the value of the slider via jquery, but he did nothing, i did a onchange event. because i want to make shure that the sum of all the options is equall to 100,  i did something like this: $("input[id^=slider]").on("change",function(e){  total = $("#total").val();
        if(total>100){
                      revert = eval(total-100);          $("input[id^=slider]").val(revert);
        }
    }); why is not working? on the dropdown subject is there an example on the code you left for us to download? Thanks, Fabio FerreiraDate: Thu, 22 Jan 2015 05:53:41 -0800From: notifications@github.comTo: bootstrap-slider@noreply.github.comCC: fcferreira@msn.comSubject: Re: [bootstrap-slider] Insert Dropdown to choose number (above Slider) (#291)I don't see why not. Just add a dropdown, and when it changes, change the slider.

—Reply to this email directly or view it on GitHub.

  
    
    
  
  
 		 	   		  =

**Comment by seiyria** [comment]
Honestly, I have no idea. You might want to make a jsfiddle that looks close to what your current environment is trying to portray -- that would make it a lot easier to help.

**Comment by fcferreira29** [comment]
Here is a jsfiddler, this is what i got

http://jsfiddle.net/fcferreira/gv41fexa/23/embedded/result/

the question is, what i want instead of the alert is to change the value of the slider that surpassed the (100) to return to the value that, (sum of all the slider values = 100), example, if the first is 50, and i for instance change the value of the 2º to 100, he will become 50 because 50 + 50 =100

**Comment by seiyria** [comment]
Your jsfiddle doesn't appear to work for me. I think you're trying to load the JS/CSS directly from github, which they disallow now. You might wanna try http://rawgit.com/

**Comment by fcferreira29** [comment]
check if its ok now

http://jsfiddle.net/fcferreira/gv41fexa/28/embedded/result/

**Comment by seiyria** [comment]
That's probably going to be difficult to do, so I'm going to suggest something different: do not let a user submit a value >100, and warn them appropriately if their value is greater than 100.
