### ISSUE TITLE
How can i stop the slider from moving after a alert message?

### ISSUE THREAD

**Issue by fcferreira29** [seiyria/bootstrap-slider#292]
I have a slider that after some conditions shows an alert message, 

i would like to know how can i make the slider stop after the alert message?

Thanks,

Fabio Ferreira

**Comment by seiyria** [comment]
I don't understand what you mean by this. Can you provide a demo?

**Comment by fcferreira29** [comment]
i have an alert box happening when the sum of the first slider and the second passes 100.

my problem is, when i click of in the "ok" of the alert message, the event from the slide that i was changing continues to work, what i want is too make the slide stop when i click "ok", because i dont want to continue increasing the value in that specific box.

**Comment by seiyria** [comment]
This is not something we can really do with the slider (this is something with how the browser handles events). As I suggested in the other thread, there is probably a better way to do this.

**Comment by fcferreira29** [comment]
here is an example,

change the first slider to 50 and the second go 50 too,

http://jsfiddle.net/fcferreira/gv41fexa/32/embedded/result/

then press ok, then move the mouse, 

i want to prevent that movement, you move the mouse and the slider moves too.

**Comment by seiyria** [comment]
Yes, as I just said, that is something the browser does and is not a case we can reliably cover. Please look towards doing this a more user-friendly way.
