### ISSUE TITLE
Chrome Version 40.0.2214.91m - Slider broken

### ISSUE THREAD

**Issue by TheAnimus** [seiyria/bootstrap-slider#293]
Hi,

In the latest stable Chrome I find the slider is broken completely for mouse.  I can use keyboard after I've clicked on the thumb, but mouse moving doesn't work.

I took a guess that this was due to chrome's handling of touch events and it's idea of mouse capture.  As a real dirty fix for me (and so I could patch our production quickly) I set this.touchCapable = false; on line 336 of bootstrap-slider.js

I appreciate this isn't a good fix, and I'm not really that knowledgeable with Chrome's touch API to offer a better solution.  But if anyone else has been having issues today with the slider not working in Chrome, figured this might help.

Alex

**Comment by seiyria** [comment]
Thanks for the heads up. Chrome seems to do something with their touch capability every few versions and it's quite dreadful to deal with it all the time.

**Comment by rovolution** [comment]
@TheAnimus thanks for bringing this to our attention

**Comment by TheAnimus** [comment]
Kudos for the response time, sorry I've not got more time to look into what's been broken exactly, as I've never learned the touch API at all.  Crude as it is, we've no touch users, so my hack is fine for me.. sorry.

**Comment by ivanbarlog** [comment]
I am experiencing same issue with slider - I can click on it and move it with arrows but I cannot drag and drop the slider. I am trying it on latest Chrome on Windows 8.1 and the issue seems to be related with multi-touch screen. When I disable my multi-touch screen it works. Couldn't you somehow detect if user is "touching" or "clicking"?

**Comment by rovolution** [comment]
should be resolved now. let us know if this happens up again
