### ISSUE TITLE
 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by labs-stellios** [seiyria/bootstrap-slider#298]
I'm getting the following error logged to the javascript console in your latest build:

`Uncaught SyntaxError: Unexpected token <` 

On line `bootstrap-slider.min.js:5`

Can you specify in your README whether I need to include your css and js in a particular order relative to jQuery and bootstrap?

**Comment by seiyria** [comment]
Can you create a jsfiddle that reproduces this issue?

**Comment by labs-stellios** [comment]
http://jsfiddle.net/x3upq36f/

I'm not sure how to include your latest dist files as external resources with jsfiddle.  I linked to the raw file in GitHub, but got a warning that github is NOT a CDN and the files may not load correctly.  What I'm seeing in the output of jsfiddle is consistent with what I am seeing in my own attempts.

I know the order can be important as well and tried to include your css and js files after jquery and bootstrap.

**Comment by seiyria** [comment]
What you're probably seeing is issues using github as a CDN. You should not link to files from github. Try downloading the files with bower and let me know if you're still having problems.
