### ISSUE TITLE
Firefox input value lag

### ISSUE THREAD

**Issue by aosmialowski** [seiyria/bootstrap-slider#299]
I've discovered weird and unexpected behaviour of the plugin in Mozilla Firefox 34.0.5.

The value of the hidden input is not being change immediately on Firefox - it's rather being "animated" on fly. Please see the attached screencast of the issue:

![Video](http://i.imgur.com/4OFbJlZ.gif)

Stuff works perfectly in Webkit based browsers (Chrome, Safari, Opera).

**Comment by rovolution** [comment]
one solution may be to to apply a ```transform: translateZ(0)``` CSS property to the slider-handle to trick the browser into thinking it is a 3D transform, thus giving it its own layer in the GPU. This would make all the slider handle movement happen on the GPU itself, thereby increasing perf
