### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by rahis** [seiyria/bootstrap-slider#303]
I am creating slider in jquery like this.

$('#mealR1').slider({
                    formatter: function (value) {
                        return '$' + value;
                    }, tooltip: 'always',
 });
when this slider is attached to the main page from the jquery function the tool tip is initially shown as follows:
I am using chrome browser, same behavior on I.E.
![image](https://cloud.githubusercontent.com/assets/2923716/6078185/8e979548-ae1c-11e4-9bfd-b51870f64025.png)

I have seen the issue reported earlier. it was happening in case of mozilla browser.. 
https://github.com/seiyria/bootstrap-slider/pull/240

Kindly help me on this.

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can get a better look at your working environment.

**Comment by rahis** [comment]
jsfiddler link ...
http://jsfiddle.net/hh2y7bnh/

see the problem in tooptip alignment.
![image](https://cloud.githubusercontent.com/assets/2923716/6090741/4ef1ea1c-aeab-11e4-82c7-810fb159973f.png)

**Comment by rahis** [comment]
I think this is similar to issue #162...

**Comment by Szeremeta** [comment]
I got around this by exposing layout as a public method

layout: Slider.prototype.layout

ensuring that the opacity of the tooltip was 0 in the case of an 'always' setting

else if(tooltip === 'always') {
  this.showTooltip();
  this.alwaysShowTooltip = true;
  this.tooltip.css('opacity', '0');
}

...then manually tweening the opacity of the tooltip in, after calling the public method (to prevent the visual snap)

**Comment by seiyria** [comment]
I see what you mean. Would it be possible to initialize the slider when it has visibility instead of initializing it before that, then showing it?

**Comment by Szeremeta** [comment]
Agreed - that sounds far more practical/sensible!

**Comment by Kinnonii** [comment]
I need to get a workaround on this. Any update since closed?

**Comment by seiyria** [comment]
If nothing in this thread works for you, then I would recommend opening up a new issue with an updated example. Many things have changed since this issue was closed, as it was almost a year ago.

**Comment by AbdullahNofal** [comment]
I noticed this problem with me when I put the slider inside anything hidden like accordion.
I found a trick for it, using the relayout function

```
    $('.panel-title a').click(function() {
        setTimeout(function() {
            $('.slider-range').slider('relayout');
        }, 0);
    });

```
Hope it helps.
