### ISSUE TITLE
Calling `refresh` changes slider type to `range`

### ISSUE THREAD

**Issue by pavelhoral** [seiyria/bootstrap-slider#306]
Refresh calls initialization with the current options, which contain non-range value stored as a single item array. Initialization [then contains this piece of code](https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L476-L478):

    if (this.options.value instanceof Array) {
        this.options.range = true;
    }

This will incorrectly change single value slider to range slider. This test should also test for a number of items in the array to be two.

**Comment by pavelhoral** [comment]
Simple workaround is to call refresh like this:

    slider.setAttribute('value', value).refresh();

**Comment by crevete** [comment]
The workaround works fine, but I wish this bug could be fixed soon...

**Comment by crevete** [comment]
This workaround has some side effect : the change event will be fired every time we call
```
slider.setAttribute('value', value).refresh();
```
Please see : https://jsfiddle.net/crevete/kLqjf4gq/5/

**Comment by crevete** [comment]
@rovolution @seiyria could you please fix this critical issue ? Thanks

**Comment by rovolution** [comment]
@crevete we will get to it when we get a chance. Thank you for bringing this to our attention

**Comment by seiyria** [comment]
As far as I can tell, this is no longer an issue.
