### ISSUE TITLE
Cutoff vertical slider

### ISSUE THREAD

**Issue by labs-stellios** [seiyria/bootstrap-slider#307]
The bottom of a vertical slider seems to get cut off.  Adding a <br> tag does not seem to help.

The jsfiddle is unable to link to your library.  Please provide an example jsfiddle or other tool if you can to teach me how to prove to you better:
http://jsfiddle.net/xsztwuga/

![cutoff_slider](https://cloud.githubusercontent.com/assets/8261825/6134521/df986d30-b116-11e4-8aa6-a0f6ecb67de9.png)

**Comment by seiyria** [comment]
Use rawgithub or something to link to the file, don't just link to github. Github is not a CDN.

**Comment by labs-stellios** [comment]
Thank you for telling me about rawgithub.  Here is an update where the top of the vertical slider is cutoff:
http://jsfiddle.net/xsztwuga/4/

This is a likely a simple fix in HTML, but should we need to hack extra HTML when using the slider?

**Comment by seiyria** [comment]
This is not an issue on our end. Add more padding to your container.
