### ISSUE TITLE
Event not firing on click

### ISSUE THREAD

**Issue by wirk** [seiyria/bootstrap-slider#310]
On some sliders, if you click somewhere on the range rather than drag the handle, the slide event does not fire. It moves to the new location and also displays the correct value in the tooltip. This only happens on some sliders, and I suspect it may have something to do with large steppings in the possible slider values. This behaviour can be observed in the demo in example 6: click somewhere on the slider track, and the tooltip will contain the corresponding value. But the text on the right saying "Current slider value: x" will remain unchanged. For the moment, I have gotten around this by also listening to the slideStart event.

**Comment by rovolution** [comment]
Bind to the ```change``` event instead of slide

**Comment by rdraviteja** [comment]
$('.slider-track').click(function(){
var sliderval = $('.tooltip-inner').html();
$("#dSAnalysisSliderValue").text(sliderval);
});

HTML: Add a span element:
<span id="dSAnalysisSliderValue"></span>
