### ISSUE TITLE
Slider not showing

### ISSUE THREAD

**Issue by Soelen** [seiyria/bootstrap-slider#311]
Hello,

I tried bootstrap-slider out today, unfortunatly no matter what i try my testfile is now showing anything when I instance bootstrap.slider anyhow.

Can anyone take a look? I am using bootstrap 3.2.0 and jquery 2.1.1. I downloaded the latest version of bootstraps-slider and I included everything to make this work, also in the right order I think.

http://gearhead.noip.me/slider/example.html

thanks in advance : )

**Comment by seiyria** [comment]
Uhh... 

![](http://puu.sh/fTfEL/7d687a033f.png)

?

**Comment by Soelen** [comment]
Interesting, I fear the slider is not working on firefox then; or at least for a range of firefox releases.

Xubuntu 64bit 14.04

Firefox 35.0.1 =>

![firefox1](https://cloud.githubusercontent.com/assets/1114549/6199602/49e0c374-b44e-11e4-96e1-4d0f9cb70c6a.png)

Firefox 37.0a2 =>

![firefox2](https://cloud.githubusercontent.com/assets/1114549/6199603/6314c796-b44e-11e4-9b13-d449c3c7fe39.png)

I also created a new firefox profile (firefox -p) in order to see if any addons, additionals scripts and whatnot are causing this behaviour, unfortunatly for both of us this is not the case.

**Comment by seiyria** [comment]
Still works for me in firefox. I don't want to say that it's probably an OS thing, but it seems to be an OS thing.
![](http://puu.sh/fUp7T/52538894e9.jpg)
