### ISSUE TITLE
touch-events chrome flag breaks draggablity

### ISSUE THREAD

**Issue by justin-hackin** [seiyria/bootstrap-slider#312]
Version 40.0.2214.95 (64-bit)
Linux Mint 17.1 
chrome://flags/#touch-events -> Enabled   results in immovable slider handle, can't be dragged with mouse, touchpad, or touchscreen.  

Searched through related issues but seems to be slightly different than existing issues.  This issue is not a result of modernizr as removing it does not fix.

**Comment by justin-hackin** [comment]
Also confirmed existence in Windows via VirtualBox

**Comment by justin-hackin** [comment]
It might be that mouse events turn into touch events with Enabled, setting to Automatic keeps touch features but prevents this issue.

**Comment by rovolution** [comment]
should be resolved now. let us know if this happens up again
