### ISSUE TITLE
Slider doesn't work (on the demo page as well) on Windows 8.

### ISSUE THREAD

**Issue by teologov** [seiyria/bootstrap-slider#313]
Hi. I've noticed, that slider doesn't work. 
Environment: Microsoft windows version 6.3 (build 9600). Chrome Version 40.0.2214.111 m

I've checked on the demo page as well.
Thanks in advance!

**Comment by seiyria** [comment]
Works for me.

**Comment by teologov** [comment]
Hi. Plugin is not working on a single machine only. This is a really weird. I am going to take a closer look soon. 
Thanks
