### ISSUE TITLE
Tooltip positioning on range slider (tooltip_split: true)

### ISSUE THREAD

**Issue by pooshok** [seiyria/bootstrap-slider#315]
Tooltips are positioned incorrectly when the page loads - http://jsfiddle.net/7aj9xzat/5/.

**Comment by pooshok** [comment]
Fix here: http://jsfiddle.net/7aj9xzat/7/
https://github.com/pooshok/bootstrap-slider/commit/c753e36b76942ad7509341a63313d0915fddd767

**Comment by rovolution** [comment]
@pooshok please submit this as a PR if you want it to be included in the plugin
