### ISSUE TITLE
Tag v4.5.0 does not include rebuilt distribution assets

### ISSUE THREAD

**Issue by mgwalker** [seiyria/bootstrap-slider#316]
The commit tagged as v4.5.0 does not include the most recent asset distribution builds, so those changes are absent.  Using bower to install 4.5.0 results in getting distribution code that what was in 4.4.2.

**Comment by crevete** [comment]
You are right :+1: and that's incredible!!! :-1:

**Comment by seiyria** [comment]
Should be good to go now, use 4.5.1.
