### ISSUE TITLE
[Blocker] Calling "setValue" with array may fail

### ISSUE THREAD

**Issue by crevete** [seiyria/bootstrap-slider#317]
When I call ```setValue``` method on a range slider, it fails with the following error :
```
Invalid input value '5,100' passed in
```
YES, please not that ```[] instanceof Array``` may return ```false```. Cf. http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/

I suggest using the native API ```Array.isArray([])``` or jQuery API ```$.isArray([])``` for better compatibility, rather than ```instanceof Array```.

Could you get it fixed ASAP, thanks

**Comment by seiyria** [comment]
Please make a jsfiddle so we can actually see the issue.

**Comment by crevete** [comment]
It's difficult... because my application runs with GWT. I does not use directly your js file, but a GWT wrapper. I've tested the type of the first argument with ```instanceof Array``` just before passing it to the ```setValue``` function, so I'm sure that it's an Array. But as described in http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/ : 
```
The problems arise when it comes to scripting in multi-frame DOM environments. In a nutshell, Array objects created within one iframe do not share [[Prototype]]’s with arrays created within another iframe. Their constructors are different objects and so both instanceof and constructor checks fail:

var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
xArray = window.frames[window.frames.length-1].Array;
var arr = new xArray(1,2,3); // [1,2,3]

// Boom!
arr instanceof Array; // false

// Boom!
arr.constructor === Array; // false
```

That's why I've created this issue. In fact, just to debug it, I've changed ```instanceof Array``` to ```$.isArray()``` in the JS source code, and this have get it fixed.  So I just suggest using a better function to detect if a variable is an array.

**Comment by crevete** [comment]
Can you fix this please? Otherwise I have to patch the JS file...

**Comment by seiyria** [comment]
Feel free to submit a PR; both of us do have other projects on our plate and this one is mostly run by the community that uses it.

**Comment by crevete** [comment]
Thanks
