### ISSUE TITLE
nuget package for version 4.5.*

### ISSUE THREAD

**Issue by SychevIgor** [seiyria/bootstrap-slider#324]
Please, update your nuget package. You last version was 4.0.* 
https://www.nuget.org/packages/bootstrap.slider 
And also update dependencies https://www.nuget.org/packages/Twitter.Bootstrap/2.3.2 is out-of-date an new dependency should be in nuget https://www.nuget.org/packages/bootstrap/.

**Comment by seiyria** [comment]
This is not our nuget package. Please bring it up with the package maintainer.

**Comment by SychevIgor** [comment]
Maybe you could create official version for nuget? As I see package maintainer didn't care about the package during 4 month.

**Comment by seiyria** [comment]
Honestly, I have no interest in maintaining an "official" version when there is one out there, that's only going to cause confusion on which package to use. Unless there's a grunt plugin we can use to automatically handle this as part of our release process, this probably isn't happening.
