### ISSUE TITLE
No-jQuery dist

### ISSUE THREAD

**Issue by knownasilya** [seiyria/bootstrap-slider#329]
Would love a dist without the jquery portion for a smaller footprint.

**Comment by seiyria** [comment]
The solution is a generic one that allows you to optionally use jQuery or not already. I'm not sure what more can be done here. Unless you mean [this section](https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L33-L188) in which case the footprint is already minimal; it's less than a fifth of the overall source code and there's no reason to split hairs over a few kb of code.
