### ISSUE TITLE
Click doesn't work when using setValue repeatedly

### ISSUE THREAD

**Issue by benkaiser** [seiyria/bootstrap-slider#331]
#### Background

I am the developer a web-based music player called [node-music-player](https://github.com/benkaiser/node-music-player) with a live version of my application [hosted here](http://music.kaiserapps.com/) for you to test the issue I am having.

I recently switched from having all my libs committed in my repo to using bower/grunt, and because the eyecon bootstrap slider did not have a proper bower repo and there was not much progress on it I decided to switch to a more healthy (active contributors, open source, unit tests, etc) library such as yours.

#### Issue

Most everything has been API compliant with eyecon, however I am having some issues with click-seeking (single clicking somewhere on the track slider where the button isn't). This seems to be because there are some backlogged `setValue` commands, so that when the `slideStop` event is triggered it reports the value from `setValue`, not from the actual click! I'm not sure if this is what is actually happening, it's just based on some initial testing of disabling the `setValue` commands.

The relevant lines of code are from line 361-394 [here](https://github.com/benkaiser/node-music-player/blob/master/static/js/player/player.js#L361).

**Comment by rovolution** [comment]
Try binding to the ```change``` event instead of ```slide``` and ```slideStop```

**Comment by rovolution** [comment]
btw that looks like a sweet app!

**Comment by benkaiser** [comment]
I tried that, however due to `setValue` being called every 100 ms, it was calling the change event and therefore seeking to that point causing it to have a weird slow stuttering behaviour.

And thanks!

**Comment by benkaiser** [comment]
Any other ideas?

**Comment by rovolution** [comment]
why is ```setValue``` being called that repeatedly?

**Comment by benkaiser** [comment]
@rovolution because as the song progress is changing (when the song is playing) the slider needs to update to show the current position.

**Comment by benkaiser** [comment]
I ended up fixing this by listening to the `slideStart` event and disabling my `setValue` commands when the click was happening and the unsetting it when the `slideStop` was called.

This can be seen in my commit [here](https://github.com/benkaiser/node-music-player/commit/1ec5eea85ebb6b96b5564230dcf433c5c04f7059#diff-a15e4c7cbbb0b7155617019e2f850238R369) .

Thanks for your help, and thanks for the awesome project! :+1:
