### ISSUE TITLE
Bootstrap slider Nuget package is still old version 4.0.8

### ISSUE THREAD

**Issue by loomarc** [seiyria/bootstrap-slider#333]
Please update the bootstrap slider version on nuget.
I would like to use the Ticks features but the Nuget package doesn't support this yet.
While the version i can download via Github does. I would like to keep using the nuget update mechanism.

**Comment by seiyria** [comment]
This is not our package, please urge the author to update it.

**Comment by loomarc** [comment]
I followed the project information link and come on your github.
see screenshot.
so I don’t know who else manage the package please tell me so I can ask him:

**Comment by seiyria** [comment]
In the README we have a link to [this page](https://www.nuget.org/packages/bootstrap.slider), on the left you can hit 'contact owners' to email the author.
