### ISSUE TITLE
bug updating value by clicking jQuery

### ISSUE THREAD

**Issue by chon27** [seiyria/bootstrap-slider#336]
I'm using this plugin and I use the bind option to show the current value in a span using jQuery like the example 6 in: http://seiyria.github.io/bootstrap-slider/

Using Opera and Firefox browsers the current value is not updating when I click in slider without slide it. The slider is changed but not in the span tag. This bug can be checked at the same example site.

I propose to fix it or to give option to only slide it and not changes by clicking.

Regards.

**Comment by seiyria** [comment]
Are you able to reproduce this against master? It's possible that the examples are outdated.

**Comment by chon27** [comment]
Hello,
I have not understood your post. I'm using /dist/bootstrap-slider.min.js from this repository in my site and it works how I said.

This is my jQuery code:
$("#score").on("slide", function(slideEvt) {
    $("#valueSlider").text(slideEvt.value);
});

Should it works fine?

**Comment by seiyria** [comment]
Presumably so. Can you make a jsfiddle?

**Comment by chon27** [comment]
Yes, I did it here: https://jsfiddle.net/4x3Lmavu/35/

I was newbie at jsfiddle but it was done like in my website, using the same and updated resources.
I hope you can see the problem.

Thanks.

**Comment by crevete** [comment]
@chon27 It's not a bug. The doc says : 

```The slide event fires when the slider is dragged```
When you click on the slider, it's not dragged, so there is not a slide event fired, but a "change" event.

try this: 
```
$("#score").on("change", function (e) {
    $("#valueSlider").text(e.value.newValue);
});
```

**Comment by chon27** [comment]
It works!
Now the value is updated sliding or clicking in it.
Thank you crevete.

**Comment by pradeepsiluveru** [comment]
$('#sliderInstn').bind('slideStop',function()) - not working on if slider moves back to 0th place.
