### ISSUE TITLE
setValue function fires consistently a change event

### ISSUE THREAD

**Issue by crevete** [seiyria/bootstrap-slider#337]
When calling ```setValue``` function, a change event is fired consistently.

It would better to and an optional argument ```triggerChangeEvent``` (defaults to ```true```) to make it more flexible.

**Comment by seiyria** [comment]
What benefit does this provide, exactly? If the event has no listeners then there should be more-or-less no overhead. I'm not seeing "flexibility" -- I'm only seeing feature creep.

**Comment by crevete** [comment]
The setValue function is an API, which means it allows you to set the slider value programmatically, rather than manually clicking or dragging the slider. It's normal that a change event is fired when a value changes via a user interaction, but via API it's more flexible to have change event not always fired. Because sometimes you just want to set slider value graphically without any interaction.

Please take a look at http://www.bootstrap-switch.org/methods.html and many other JS widget libs.

**Comment by rovolution** [comment]
i can see the value in this

**Comment by crevete** [comment]
@rovolution :+1:

**Comment by rovolution** [comment]
@crevete just added this in. see the docs for ```setValue```
