### ISSUE TITLE
Modal dialog closes when dragging and releasing mouse button outside dialog

### ISSUE THREAD

**Issue by bgvianyc** [seiyria/bootstrap-slider#339]
When slider is used inside of a bootstrap modal and the user drags the mouse off the modal, under normal operation, the modal stays open, if the modal uses bootstrap-slider the modal closes. 

This used be an issue in bootstrap as well, but was fixed as per below thread:

https://github.com/twbs/bootstrap/issues/13816

**Comment by seiyria** [comment]
I'd need a demo, though it is more or less self-explanatory. What I don't understand is why it's an issue here if bootstrap fixes it, and presumably you're using a bootstrap modal to do display.

**Comment by bgvianyc** [comment]
It seems to trigger a click event when the user drags off the modal and then releases the mouse button.

**Comment by bgvianyc** [comment]
Here is a demo. Mouse is not displayed so I logged to console the events triggered.
![modal_close 2](https://cloud.githubusercontent.com/assets/4020296/6711897/22c24404-cd60-11e4-976f-0cb501accb65.gif)

**Comment by bgvianyc** [comment]
One more observation. This bug only happens in chrome

**Comment by ZeVS777** [comment]
Why this issue is closed? What was done to prevent this type of issue? I have this problem not only in chrome.

**Comment by ZeVS777** [comment]
This plugin does not bubble the mousedown event to bootstrap modal, so there no check close or not to close modal.
in the  
`_mousedown: function _mousedown(ev) { `
I change 
`this._pauseEvent(ev); `
on
`ev.returnValue = false;`

**Comment by seiyria** [comment]
Please submit a pull request if your fix works. We'd appreciate it!

**Comment by rovolution** [comment]
fix was merged/released in v9.5.4
