### ISSUE TITLE
Make demos auto-publish to gh-pages

### ISSUE THREAD

**Issue by seiyria** [seiyria/bootstrap-slider#34]
This way our demos are always up to date with master on the gh-pages branch

**Comment by rovolution** [comment]
@seiyria i am starting to begin work on this. Going to incorporate this into our `npm` postpublish script.

However, i may need to make some structural changes:

__1)__ For our jQuery,bootstrap, Modernizr dependencies, I will probably have to add copies of them to the js/css directories instead of depending on bower to get the dependencies.

__2)__ need to rename a few directories in the `gh-pages` branch

Just want to give you a heads up. Would you prefer that I submit these changes as pull requests or push the changes directly? Thanks!

**Comment by seiyria** [comment]
What if we use their CDN instead? No need to keep their deps around.

You can feel free to push them directly, though.

**Comment by rovolution** [comment]
I still like being able to work when i don't have an internet connection, so i was thinking of just keeping copies of the deps

**Comment by seiyria** [comment]
Ah, that's fair. If they're only there on gh-pages that'd be okay - but I'm not sure I would want them in the main repo.

**Comment by rovolution** [comment]
so the way i see it, the index.html page in both the main repo and the `gh-pages` would be the same. then on postpublish, i would just move the version of the src code from `master` to `gh-pages`

**Comment by seiyria** [comment]
Have you looked into a tool like grunt gh-pages before? You could always have a custom build in grunt to automate most of this. I think that's what I intended when I opened this issue a long time ago.

**Comment by rovolution** [comment]
@seiyria adding this to the postpublish script is really easy (and also automates the entire process)

**Comment by rovolution** [comment]
automation process for updating gh-pages
```sh
# Push new source code to gh-pages branch
	git checkout -B gh-pages
	git pull -r origin gh-pages
	git checkout master -- js/bootstrap-slider.js index.html css/bootstrap-slider.css
	git commit -m "updates"
	git push origin gh-pages:gh-pages -f
```

**Comment by rovolution** [comment]
> Ah, that's fair. If they're only there on gh-pages that'd be okay - but I'm not sure I would want them in the main repo.

this makes sense. i can do this

**Comment by rovolution** [comment]
done!

now all we have to do is 2 steps:

__1)__ bump version via grunt-bump tool

__2)__ type `npm publish`. that will handle publishing to npm, pushing up new git tag references, building a new version of the `/dist`, and auto publishing to the `gh-pages` branch!

**Comment by seiyria** [comment]
+1! simplicity is better
