### ISSUE TITLE
Using bootstrap-slider as dropdown menu[bug]

### ISSUE THREAD

**Issue by zzzhan** [seiyria/bootstrap-slider#340]
Everything is ok, except using it as a dropdown menu.When I move the slider after dropdown, it is not the exact position where I press.
http://stackoverflow.com/questions/29142031/using-bootstrap-slider-as-dropdown-menu

**Comment by KyleMit** [comment]
Just an update with a barebones reproduction of the issue.  It looks like it happens whenever the slider is inside of a parent with positioning applied. The calculated height of the mouse gets offset by any of the content above the slider.

Here's the minimal code to reproduce the issue:

```html
<div style="position:relative">
    <h3>Slider Offset</h3>
    <input type="text" class="slider"
           data-toggle="slider" data-slider-orientation="vertical" />
</div>

<script type="text/javascript">
    $('.slider').slider();  
</script>
```

[Here's a running sample in jsFiddle][1].

Just try to click on the dot and it will jump to the value below it.

This doesn't look *so* bad, but in less minimal examples, the difference gets less minimal

The difference occurs in the [`_getPercentage`][2] function when calling `this.offset.top`.  If you remove the relative positioning on the parent, `this.offset.top` should include the height of other elements in the HTML flow so they are not counted toward the event re-positioning.

[1]: http://jsfiddle.net/KyleMit/dy0qobyp/
[2]: https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L1238

**Comment by seiyria** [comment]
@KyleMit I see, that is an issue then. It also seems this is reproducible against master (not sure what version github.io is at currently).

**Comment by zzzhan** [comment]
@seiyria Will u fix such issue or any hack code to solve it?

**Comment by zedtux** [comment]
+1

**Comment by zedtux** [comment]
@seiyria any news ?

**Comment by seiyria** [comment]
Nope. I haven't touched it.

**Comment by KyleMit** [comment]
@zedtux, it's open source, so I'm sure any of the library maintainers wouldn't mind if you submitted a pull request.  If the problem is in the _getPercentage function, here's a fiddle you can use to work on it.

http://jsfiddle.net/KyleMit/dy0qobyp/4/

**Comment by rovolution** [comment]
if someone could submit a PR, that would be much appreciated!

**Comment by zedtux** [comment]
I still have this issue. I have upgraded the gem but still the slider has an offset between the point where I click and the position.

**Comment by seiyria** [comment]
We do not maintain the gem so we can't help there (unless you're saying you manually upgraded it).

**Comment by zedtux** [comment]
My bad ... I have realized that the gem I'm maintaining is not up-to-date ... I'll let you know.

**Comment by zedtux** [comment]
Cool, it's working now ! Sorry for the confusion.
