### ISSUE TITLE
Slider breaks if container is set position: relative.

### ISSUE THREAD

**Issue by crudd** [seiyria/bootstrap-slider#342]
The slider jumps to max value if the containers position is set to relative.  You can recreate the bug by setting slider-example class' position to relative on the demo page.  It breaks all the sliders on the page, they will go to max value when clicked and then remain immovable, until/unless you remove the position: relative style.

**Comment by crevete** [comment]
I guess you are talking about #327 which has been fixed in 4.5.6. The demo page still uses an old version of bootstrap-slider.js.

**Comment by crudd** [comment]
Ah, yes, that is the issue.  Thanks for the speedy reply and freeing up the rest of my Sunday. :)

**Comment by crevete** [comment]
@seiyria This may be closed.
