### ISSUE TITLE
Wrong cursor position with slider in vertical position

### ISSUE THREAD

**Issue by zedtux** [seiyria/bootstrap-slider#343]
I have tried this with the horizontal position and the slider works like a charm.

I'm trying to have the slider working vertically in my website using Twitter bootstrap. My website has a top menu and then the slider is in a `row`.
When I use the slider, the cursor is not aligned (I.e: I click at position '0' and the cursor move to position '4').

Removing the top menu makes the slider working perfectly vertically.

Is there a way to fix this or is it a bug ?

**Comment by seiyria** [comment]
Is this something to do with `position: relative`? Similar: https://github.com/seiyria/bootstrap-slider/issues/340

**Comment by zedtux** [comment]
Yep ! Seems to be the same.

**Comment by seiyria** [comment]
Cool, I'll close this as a duplicate. Follow along there please!

**Comment by zedtux** [comment]
Sure, thank you.
