### ISSUE TITLE
TypeError: 'undefined' is not a function with PhantomJS

### ISSUE THREAD

**Issue by zedtux** [seiyria/bootstrap-slider#344]
I'm using Cucumber in order to write the tests of my application. The stack is Cucumber + Capybara + Poltergeist + PhantomJS.

I have a simple test going to a page where the `bootstrap-slider` is used but when accessing the page I got the following error:

      TypeError: 'undefined' is not a function (evaluating 'this._applyPrecision.bind(this)')
      TypeError: 'undefined' is not a function (evaluating 'this._applyPrecision.bind(this)')
          at http://127.0.0.1:39721/assets/application.js:31722
          at http://127.0.0.1:39721/assets/application.js:31608 in createNewSlider
          at http://127.0.0.1:39721/assets/application.js:31294
          at http://127.0.0.1:39721/assets/application.js:31190
          at http://127.0.0.1:39721/assets/application.js:142
          at http://127.0.0.1:39721/assets/application.js:504
          at http://127.0.0.1:39721/assets/application.js:143
          at http://127.0.0.1:39721/assets/application.js:31194
          at http://127.0.0.1:39721/assets/rating_systems/edit.js:4 (Capybara::Poltergeist::JavascriptError)

The `edit.js` (which is in fact `edit.js.erb` as I'm developing an Rails application) file contains the following code:

```erb
$('.slider').slider({
  min: 0,
  max: 21,
  ticks_labels: <%= (0..21).to_a.inspect %>
});
```

The slider is working perfectly in the application (No JS error) but with PhantomJS, it seems invalid.

Can you please give me direction on how to make the slider working with my tests ?

**Comment by seiyria** [comment]
I'm not sure, honestly -- we use jasmine and that seems to work fine.

**Comment by zedtux** [comment]
:-(

I'm not going to change my Javascript engine just for this issue... (I have a lot of tests already). Then I have to find the solution by myself.

**Comment by seiyria** [comment]
That's fine, but we don't use it so it's a bit harder to diagnose, sorry! If you do find out what's wrong, though, please feel free to submit a PR!

**Comment by domness** [comment]
Having the same issue here, causing any tests related to this slider to completely fail.

**Comment by zedtux** [comment]
@seiyria is it possible that `_applyPrecision()` returns `undefinied` ?

**Comment by seiyria** [comment]
@zedtux it shouldn't; it simply changes the precision of a number. Unless you managed to pass in a bad precision option I don't think it would break.

**Comment by nobuf** [comment]
I was facing the same issue. I figured that phantomjs 1.8.2 / 1.9.8 have no `Function.prototype.bind`. It's supported on 2.0. (`brew install phantomjs`)

see https://github.com/ariya/phantomjs/issues/10522 https://github.com/teampoltergeist/poltergeist/issues/292

**Comment by seiyria** [comment]
Cool. Is it sufficient to say we should just require Phantom 2.0 then? @zedtux, @domness - would this work out, or are there other complications associated with upgrading?

**Comment by rovolution** [comment]
Yea for our test suite (which is running on an older version of phantom) we load in a `.bind()` polyfill

**Comment by zedtux** [comment]
I will give it a try but I don't think it will lead us to complications.

**Comment by seiyria** [comment]
Thanks. If that works out I think that will just be our resolution.

**Comment by stsims** [comment]
I was getting this error, and solved it by increasing from 1 to 2 virtual CPU's on my VM, plus increasing memory from 2gb to 4gb.
