### ISSUE TITLE
Can a number box be converted to a slider?

### ISSUE THREAD

**Issue by judgej** [seiyria/bootstrap-slider#345]
I am using a HTML5 number box in a form, with a min, max, step and value.

I was hoping that `jQuery("#my-number-box").slider()` would pick up all those attributes. It did not, and I had to copy them all across to the slider object manually. The min/max/step all defaulted to 1/10/5.

Either I did something wrong, or it is simply not supported. If the latter, then is there any chance that could change? This is my clumsy workaround, which seems on the face of it, totally unnecessary:

	var q4 = jQuery("#q4");
	var mySlider = q4.slider({"min": q4.attr('min'), "max": q4.attr('max'), "step": q4.attr('step'), "value": parseFloat(q4.attr('value'))});

I want to keep the number box as a fallback for older browsers.

**Comment by seiyria** [comment]
It is not currently supported, and the only way it would change is if you send a PR, probably.

**Comment by judgej** [comment]
Okay, I'll encapsulate the conversion from numberbox to slider into a method, and see what comes of that (whether it fills a need that others have or not). The numberbox questions tend to be asking for a percentage, with a range 0 to100, in steps of 10.

In a similar vein, I have questions that consist of radio buttons. I am also looking for a way to convert those radio buttons into a slider (with ticks and labels) automatically. Again, the radio button list and labels are there as a fallback for older browsers; without the conversion, those browsers see the radio buttons.

**Comment by judgej** [comment]
If I link code back to here, and see if there is interest from other people, would that be okay before I start trying to put PRs together?

**Comment by judgej** [comment]
My workaround on this at the moment, is to add the data-* attributes to my number box. The element ends up with duplicate attributes, such as "max" and "data-slider-max", but at least one element works as both a number box (for older browsers) and a slider (for newer browsers) without any messing around with JS to copy attributes between the source element and the slider object.

**Comment by judgej** [comment]
I'm going to close this as the workaround (if you can call it that) works.

The solution is to use both sets of attributes on the number box - the min/max/step attributes and the data-*  attributes. The two live together happily and don't interfere..

**Comment by seiyria** [comment]
Sure, that works for me. Thank you, and good job on that.
