### ISSUE TITLE
Support "undefined" state?

### ISSUE THREAD

**Issue by judgej** [seiyria/bootstrap-slider#346]
Number boxes and radio button sets both support an "undefined" state, if presented to the user without any initial value set. This is useful in surveys (which I am creating) to ensure the user makes a positive decision on the selected value rather than just presses "next" to select the default value.

Does this slider support an undefined state too, or does it *have to* have a value? In my head, I would see a "no value" state showing the slider in perhaps a different colour until the user starts sliding it, then it takes on a value.

Like required number boxes and radio sets, once a value is selected, the user cannot then unselect it. But that's fine - that would be the intended behaviour.

**Comment by seiyria** [comment]
I don't believe we support this, but it's not a bad feature to have. From a UX perspective, being presented with a blank bar is not helpful, so I think the way to do this would be to have it at the minimum, and in a different color. Or, maybe have the circle radius be smaller to indicate that it's not gotten a value yet.
