### ISSUE TITLE
Can tick labels auto-wrap text to the size of their containers? (was: Can width take account of tick labels)?

### ISSUE THREAD

**Issue by judgej** [seiyria/bootstrap-slider#347]
I have set the width of the slider to 100%

    .slider.slider-horizontal {
        width: 100%;
    }

This allows the slider to take on the size of the element that it is in, as is a common approach for column layouts such as bootstrap.

Now, this works, except where there are long tick labels. I have attached an example to this ticket, where the labels overlap the contaiining element of the slider.

Is there a way to set the *total* width of the slider to include the size of the labels that stick out the sides? I have noticed that when the viewport is resized, the slider resizes fine, but the tick labels stay where they were originally place, so there is something funny going on with those labels anyway.
![clipboard01](https://cloud.githubusercontent.com/assets/395934/6883203/93388850-d59a-11e4-8712-a3cb92c528e4.jpg)

**Comment by judgej** [comment]
Each tick label is in a div of a fixed width, and they are in a wrapper that has a negative left margin. If the whole slider is wrapped in a div with left and right padding equal to that negative offset then the total slider (including labels) can be made to fit into a given width. So far as I can see, this is only achievable using JavaScript.

It does move the issue on to another problem - long labels do not wrap. Given that the label containers are a fixed width, and the layout needs to fit into a page that does not expect any surprises, then the non-wrapping labels are a bit of a surprise to the page. The text needs to stay in the containers it is given. At the moment, the labels do not wrap, stay on a single line, and so long labels overlap each other and stick out the right-hand side.

Of course, this plugin may have been designed with the implicit decision that all labels will be very short (which is what the demos show). That is unfortunately not how our real-world project is working out :-(

**Comment by judgej** [comment]
Okay, being dumb, I just realised that I *do* know how much to pad the wrapper to allow the label containers to fit in: the padding is (total_width / (number of labels + 1) ) / 2

That works for pixels or percentages. So for a 100% wide slider with five labels, it is put into a div with left and right margins of (100/6)/2 or 50/6 or 11%. That's easy enough to calculate on-the-flay when the elements are put together dynamically in a template.

I hope that helps others having this issue of labels slicking out the sides.

I just need to get the labels to wrap so they stay in the left-right bounds of their containers now.

**Comment by judgej** [comment]
The labels seem to be able to take `<br />` elements nicely. It's not an automatic wrap, but the label can be split every second or third word with a `<br />` as a workaround.

**Comment by adonismedia** [comment]
What I did is change the parent div width to 80%:

`
.parent{
width: 80%
}
.parent .slider.slider-horizontal {
    width: 100%;
}`

The parent div also has a bootstrap class of 'text-center', which centres the slider.
