### ISSUE TITLE
Detect which browsers the slider will work on

### ISSUE THREAD

**Issue by judgej** [seiyria/bootstrap-slider#348]
Is there a way to determine programmatically from within this slider, whether the slider is supported by the  current browser? Or does that need to be done externally, just based on the detected browser name and version numbers?

I have JS replacing a radio button group with a slider. To do that, the slider starts hidden and disabled. The JS then hides the radio group and disables the radio buttons, and shows and enables the slider text field. Obviously I only want to do this if the slider is supported by the browser, otherwise the user may end up with a hidden radio group and a hidden or non-active slider.

**Comment by rovolution** [comment]
Our goal is IE9+. Anything less than IE9 we do not support.

**Comment by judgej** [comment]
So when you say "do not support" does that mean the slider will still attempt to create itself but leave the results undefined? You don't make any attempt to detect the browser and exit without adding a slider if it is not a supported browser?

**Comment by seiyria** [comment]
We do not even test functionality on IE9, period. If it works, cool. If not, we won't make any effort to do so.

**Comment by judgej** [comment]
Okay - "undefined" then :-)

I'll do a browser detect and bail out before converting the radios and number/text boxes if on IE8 or less. I don't want to leave it up to chance to maybe work and maybe not.

Ta.
