### ISSUE TITLE
data-slider-ticks-labels attribut not working on V 4.5.6

### ISSUE THREAD

**Issue by Doopin** [seiyria/bootstrap-slider#350]
Just to let you know that there's an issue with your fantastic bootstrap slider.
Remember this example
![eiejeigf](https://cloud.githubusercontent.com/assets/10206793/6917783/d9943176-d79f-11e4-9a0f-d7b1cfaf2617.png)

I tried with same params and it works only if i initialize it with JQuery and not HTML attribute.

I found what goes wrong in the plugins.
While initializing plugin with HTML att, result return by check condition is 'false'. So the code in is not executed.
![dehdccfj](https://cloud.githubusercontent.com/assets/10206793/6917798/fff78cdc-d79f-11e4-83fb-c985cef2169b.png)
But there is no problem while configuring with JQuery.
So, you have to remove the double code before check in this case.

Hope it will help :)

**Comment by puco** [comment]
jQuery does not correctly evaluate the data attribute http://stackoverflow.com/a/6071653/188987. So the correct HTML is:

```
<input id="ex13" type="text" data-slider-ticks="[0, 100, 200, 300, 400]" data-slider-ticks-snap-bounds="30" data-slider-ticks-labels='["$0", "$100", "$200", "$300", "$400"]' />

```

**Comment by Doopin** [comment]
Ok great!
thanks
