### ISSUE TITLE
Start from middle value from to left and right site 

### ISSUE THREAD

**Issue by tomrybok** [seiyria/bootstrap-slider#351]
Hi,

I have some questions:
I have slider (with ticks) from -10 to 10 (step 1). I want to start not from -10, but from 0 and choose -10 (on the left) and 10 (on the right). Slider should work like now, byt i want to choose start position. 
Is there any capabilities to do this ?

**Comment by seiyria** [comment]
Yes, set the value to 0 by default.

**Comment by tomrybok** [comment]
Thanks for reply.
But I want to have colored from 0 to 5, but not from -10 to 5, like below:
Now i have:
-10 +++++ -5 +++++ 0 +++++ 5 ------- 10
but want to have:
-10 ----- -5 ----- 0 +++++ 5 ------- 10

**Comment by seiyria** [comment]
You could use CSS to hide the other colors.

**Comment by tomrybok** [comment]
OK thanks - i will try :)
