### ISSUE TITLE
Honor step size with logarithmic scale

### ISSUE THREAD

**Issue by manthey** [seiyria/bootstrap-slider#353]
I'd like to see the step used with the logarithmic scale.  The step size would be a linear value (not logarithmic).  If you don't want a step size, then setting step to zero could disable it.

**Comment by manthey** [comment]
I'd be happy to submit a change to do this.

**Comment by seiyria** [comment]
Please do! Just make sure you have some unit tests to expedite the process.

**Comment by rovolution** [comment]
as long as you provide tests + appropriate documentation, it would be much appreciated!

**Comment by manthey** [comment]
Do I need to be given permission as a collaborator to push a branch?  I have a small change with a test.

**Comment by seiyria** [comment]
You should fork the code and work on your own fork, then submit a pull request.
