### ISSUE TITLE
Bug generating wrong 'in-selection' ticks when selection === 'after'

### ISSUE THREAD

**Issue by TheDartCode** [seiyria/bootstrap-slider#356]
When you set selection:'after' and use ticks, the wrong ticks are marked as 'in-selection'.

Fiddle: https://jsfiddle.net/zbc3gs1L/

**Comment by seiyria** [comment]
Which ones would you expect to be marked `in-selection`? It seems like everything after the cursor is being marked, which seems accurate.

**Comment by TheDartCode** [comment]
I would expect this: https://jsfiddle.net/en7wuh4L/

I have implemented the changes in this commit,
https://github.com/TheDartCode/bootstrap-slider/commit/e618a6a46d0266087fe316b72e133e1705f82660
I'll issue a pull request if you accept.

**Comment by seiyria** [comment]
Ahhhhh. I see how it works now. Yes, I think it's fine to submit that as a PR if you include a test as well. Thanks!

**Comment by TheDartCode** [comment]
Hehe, will do asap :)
Thank you for the great component!

**Comment by seiyria** [comment]
And thank you for using it and helping improve it!
