### ISSUE TITLE
Tick labels not working as data attributes

### ISSUE THREAD

**Issue by mglenn** [seiyria/bootstrap-slider#360]
When specifying tick labels via the data-slider-ticks-labels data attribute the options are parsed as a single string rather than an Array. I couldn't tell from a cursory overview of the comments where the parsing is being done and if there is an attempt to convert to an Array. The examples show it as a data attribute but the example itself works since the initialization and parameters are set via Javascript.

`<input class="form-term form-input slider" data-slider-id="termSlider" data-slider-ticks-labels="['1', '2', '3', '4', '5']" data-slider-ticks-snap-bounds="1" data-slider-ticks="[1, 2, 3, 4, 5]" data-slider-value="5" id="form-term" name="registration[term]" placeholder="Term (Years)..." type="text" value="5" />`

**Comment by vvo** [comment]
see https://github.com/seiyria/bootstrap-slider/issues/350
