### ISSUE TITLE
onmousedown does not trigger the change

### ISSUE THREAD

**Issue by flatr0ze** [seiyria/bootstrap-slider#362]
~line 1132 should be

`				this.setValue(newValue, true, true);`

instead of 

`				this.setValue(newValue, false, true);`

otherwise whenever I click on a slider instead of dragging it, it won't trigger the slide event and therefore the callback function would not fire

looks like a bug in production, please fix.

**Comment by rovolution** [comment]
@flatr0ze what event are you listening on? We only trigger 'slide' when the slider has actually been slid.

If you want to your listener to trigger whenever the value changes, bind to the `change` event instead

**Comment by flatr0ze** [comment]
but they provide different parameters for the callback function... so I can't just do `slider.on("slide change")`... it pushes users to write useless code, while essentially the slide _is_ being slid whenever somebody clicks on it

**Comment by seiyria** [comment]
If you have an idea of how to make it consistent, we love taking PRs!

**Comment by flatr0ze** [comment]
I guess you could add a "tap" or "click" event in addition to "slide" and "change", which would use the same data event object as the "slide" event, therefore making it possible to have all of them being responsible for each input method, while making things such as `slider.on("slide change", function(evt){...});` possible;

but having only the "slide" event makes the most sense, if you ask me... it's a slider, after all, not an input

**Comment by seiyria** [comment]
We've had numerous requests to separate them as they are currently. While it may not make sense to you, this is what the community wanted. If it can be streamlined in such a fashion, I'm all for that, but I'm not certain adding new events is the solution.

**Comment by flatr0ze** [comment]
around line 760:

```js
				if(triggerSlideEvent === true) {
					this._trigger('slide', newValue);
				}
				if( (oldValue !== newValue) && (triggerChangeEvent === true) ) {
					this._trigger('change', {
						oldValue: oldValue,
						newValue: newValue
					});
				}

```

I'd say it'd be nice to make both of them return the same data (both of them return oldValue and newValue?) then .on("slide change") would work just fine

**Comment by flatr0ze** [comment]
Right now I am doing it like this:
```js
		slider.on("slide change", function(event){
			var val = void 0 === event.value ?
						5000 : typeof event.value == "number" ?
							event.value : event.value.newValue;
```
but it's a huge mess, ashamed to show it to anyone...

**Comment by rovolution** [comment]
@flatr0ze the 'change' event still gets triggered on a slide if i am not mistaken

**Comment by flatr0ze** [comment]
I need to somehow update the UI through the callback whenever a user is clicking on the bar to put the handle at that point. I tried to do it with one callback function. Guess will use two separate ones next time.
