### ISSUE TITLE
min property causes problems with dynamic step adjustement

### ISSUE THREAD

**Issue by flatr0ze** [seiyria/bootstrap-slider#363]
Howdy.

This code that I have:

```js
		// Instantiate the slider
		var slider = $("#slider1").slider({ min:     5000
										  , max:     5000000
										  , step:    5000
										  , value:   5000
										  , tooltip: "hide"
										  // , scale:   "logarithmic"
										  });

		// Pointer to the data object
		// of the slider plugin instance
		var slider_data = $.data( $("#slider1")[0] ).slider;

		// Let's specify the pointers to the DOM elements
		var $marker = $("#marker");
		var $income = $("#income");

		slider.on("slide change", function(event){
			var val = void 0 === event.value ?
						5000 : typeof event.value == "number" ?
							event.value : event.value.newValue;

			$marker.text( "$" + format_1K(val).toLocaleString() );
			$income.val( "$ " + val.toLocaleString() );

			if( val > 50000 && val < 500000 ) { /* 50.000 - 500.000 */
				slider_data.options.step = 50000;
			} else if( val >= 500000 && val < 2000000 ) { /* 500.000 - 2.000.000 */
				slider_data.options.step = 100000;
			} else if( val >= 2000000 && val <= 5000000 ) { /* 2.000.000 - 5.000.000 */
				slider_data.options.step = 500000;
			} else { /* 5.000 - 50.000 */
				slider_data.options.step = 5000;
			}
		});
```
causes an extra "5000" appended to every tick I make during the slide, no matter what the step is.

The problem that I discovered lies around line 228:
```js
					var value = /*this.options.min +*/ Math.round(rawValue / this.options.step) * this.options.step;
```
(the commented-out var and the `+` operation is what's been causing this)

So far so good, everything works...

Probably not a bug, since this kind of usage has nothing to do with the features of your slider, just decided to let you know that I needed this feature and had to adjust the source code a little bit to achieve it.

Thants...

**Comment by seiyria** [comment]
Can you make a jsfiddle out of it? Much easier to work with that.

**Comment by flatr0ze** [comment]
Sorry, have to finish this task before midnight, it's for a job application... can't spend too much time outside the main task, maybe later if I won't be too exhausted

**Comment by seiyria** [comment]
Er, anyway, if it keeps getting appended, that means you have a string somewhere instead of a number.

**Comment by KRaymundus** [comment]
I had the same problem, and the provided solution solved it for me as well. I would suggest removing the `this.options.min + `.

**Comment by seiyria** [comment]
Closing due to lack of a proper demo.
