### ISSUE TITLE
ticks overlap

### ISSUE THREAD

**Issue by garemoko** [seiyria/bootstrap-slider#368]
HTML: ```<input class="speed-slider" type="text" data-slider-step="1"/>```

JavaScript: 
```
var sliderTarget = $(this).find('.vessel-turnTracker .move .speed-slider');
var currentSlider  = sliderTarget.slider({
                            min: minSpeed,
                            max: maxSpeed,
                            value: vesselStartSpeed,
                            tooltip: 'hide',
                            ticks: ticks,
                            ticks_labels: ticks,
                        });
                        currentSlider.slider("refresh");
```

When my slider generates the ticks overlap (they have a width of 0px). Clicking any part of the slider causes them to display correctly. I have tried refreshing the slider but that does not work. 

Tested in Chrome and Firefox on Mac.

Any ideas?

**Comment by garemoko** [comment]
You can see my full code here: https://github.com/garemoko/velocity-board-game

**Comment by garemoko** [comment]
I worked out the cause of the problem. When I create the slider, it's in a hidden div. If I call ```.slider('refresh');``` after displaying the div, the ticks display correctly. 

Leaving this issue open in case you want to fix this or update the documentation.

**Comment by seiyria** [comment]
Displaying things in a hidden container is a known issue and we have a few other issues about it, so I'll close this one.

**Comment by monolok** [comment]
I have the same issue, any solutions ? the .slider("refresh") does not work for me.
My slider is inside a hidden div.

**Comment by seiyria** [comment]
If it's hidden, it cannot calculate display attributes correctly.

**Comment by monolok** [comment]
I noticed. I cannot figure out a solution. do you know a way to re-calculate display attribute via javascript date the div is shown ?
