### ISSUE TITLE
Slider won't keep modified value on slideStop

### ISSUE THREAD

**Issue by deathwebo** [seiyria/bootstrap-slider#369]
Hi there!

I found that if I change the value on the fly of my slider on the **"slideStop"** event the value is overwritten right after the event. 

I'm trying to validate that the total amount of some related sliders is not greater than 100.

In case the value of a slider (added to the other slider's values) surpasses the 100 mark, I need to change that slider's value to the next available value. So if a slider is changed to 60, and the total of the rest of the sliders is 50, then I have to change the 60 value to 50.

Here's a working example of my bug:
https://jsfiddle.net/deathwebo/roks4ny0/

I found out on the code, in the **mouseup** and **keydown** events where the slideStop is triggered that if I change this piece of code
```
this._trigger('slideStop', val);
this._setDataVal(val);
```

To this 
```
this._setDataVal(val);
this._trigger('slideStop', val);
```
It gets fixed as the value is not overwritten by the _setDataVal method.
https://jsfiddle.net/deathwebo/Lvbq9uh8/

Cheers! And keep up the good work @seiyria & co

**Comment by seiyria** [comment]
I agree with your assessment; I think it's wise to emit the event after having changed the data (as that's what I would expect in an event emitter situation). If that would suffice, I think that change is simple enough to implement. If you send a PR, that'd be great too!
