### ISSUE TITLE
Passing slider any class via original input classes or via data-* attributes ?

### ISSUE THREAD

**Issue by baasha** [seiyria/bootstrap-slider#371]
Hi,
is there any possibility to either set class of slider via data- attribute or (better) get classes from original input element ?

For example - I want in my bootstrap enabled project those two sliders:
red slider and yellow slider:

```html
<input class = "slider slider-danger">
<input class = "slider slider-warning">
```

When using original bootstrap-slider, it works like a charm, but this (**much better** ;) ) slider ignores original inputs classes.

Is there any workaround ?

Thanks.

**Comment by seiyria** [comment]
It does not appear that we have support for that.

**Comment by Bhoft** [comment]
this would be a one liner which could be added in the create Markup section like below.
```
this.sliderElem.className = "slider";
// get classes from the this.element and add them to the slider
this._addClass(this.sliderElem,this.element.className);
```

**Comment by rovolution** [comment]
if you write automated tests, im all for it :)

**Comment by Bhoft** [comment]
sadly i have no clue how to write this automated tests.
I did the change in my fork and also added a possibility that the css classes are automatically set if a tick is reached.

see my pull request
https://github.com/seiyria/bootstrap-slider/pull/395

**Comment by rovolution** [comment]
Looks like an outdated issue...[since we do have similar functionality now with data-provide](https://github.com/seiyria/bootstrap-slider#using-bootstrap-slider-via-data-provide-api)
