### ISSUE TITLE
Invalid value passed

### ISSUE THREAD

**Issue by martinambrus** [seiyria/bootstrap-slider#373]
Took a few moments to figure this out - when a *STRING* value is passed to the `setValue` method, it will be refused, even if it contains a valid integer. It's fairly simple to do `slider('setValue', +var)` to convert it, however I think this could find its place as an enhancement in core of this project. If for no other reason, then at least simply because the error message that says 60 is an invalid value is very cryptic indeed.

**Comment by seiyria** [comment]
I disagree. This function takes either a number or an array (in the case of range sliders). Coercing it would not be a good solution.

**Comment by martinambrus** [comment]
That makes sense, I didn't notice it takes multiple argument types. In any case, perhaps a more explanatory error message could be provided, as seeing a '60' as incorrect value actually doesn't make sense, since it's an integer, albeit in a string form? This is basically the initial idea - the error message puzzled me there and it took valuable time to debug, since there is no mention of this, nor multiple argument types in the docs - https://github.com/seiyria/bootstrap-slider#functions

**Comment by seiyria** [comment]
I've updated the documentation, let me know if that works out for you.

**Comment by martinambrus** [comment]
Absolutely, thank you :)

**Comment by seiyria** [comment]
No problem, thanks for bringing it up. I'm sure it's come up for others too!
