### ISSUE TITLE
My formatter dose not work.

### ISSUE THREAD

**Issue by say8425** [seiyria/bootstrap-slider#378]
```java-script
$('#slide-visually').slider({
  	formatter: function(value) {
		return 'aaa' + value;
	},
	reversed: true,
	handle: 'square',
});
```

`reversed` and `handle` works. But `formatter` dose not work. What did I wrong? Thanks.

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can see what you're doing.

**Comment by say8425** [comment]
I got a 2.0.0. So it has bug and I must use `formater` instead of `formatter`.
Sorry I make a stupid issue.

**Comment by seiyria** [comment]
No problem. Great to hear it works.
