### ISSUE TITLE
setAttribute({min:value})

### ISSUE THREAD

**Issue by gagvirus** [seiyria/bootstrap-slider#379]
Hi. I am using Your library and like it.
In my application I have a case that I should change the min-max bounds when user changes product. On change event, I call this line 
myslider.slider('setAttribute', {min : minValue, max : maxValue});
and it does not work. 

 Also I tried changing the min-max values by simple js/jquery by changing the data-attribute. 

What am I doing wrong ? 

Thanks in advance.

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can see what you're trying to do.

**Comment by gagvirus** [comment]
I found the solution : instead of `slider('setAttrubute', {min : minValue, max : maxValue})`, should use 
`slider('setAttribute', 'min', minValue)` and so on. I understand it was my fault, but please add the example of using `setAttribute` so no one gets confused anymore ))
Thanks...

**Comment by seiyria** [comment]
This is already noted in the documentation:
setAttribute | attribute, value | Updates the slider's attributes

Using it the jQuery way is something that's supported, but you would have to do it the jQuery way.
