### ISSUE TITLE
Wrong slider position recognition with position:absolute

### ISSUE THREAD

**Issue by mitsos1os** [seiyria/bootstrap-slider#381]
Hi Guys.. When positioning the slider or one of its containers with ***position:absolute;*** css and maybe moving them with ex. ***left:50%;*** or something, (in my case I was using the slider in an off canvas sidebar that moved with css) the slider position inside its inner functions is not recognised correctly, with the result of it not working properly.

I discovered that this happens due to line 1414 where this function is used to track the offset of the slider, by browsing its offset parents and getting their offset left property. This is the code:

	_offsetLeft: function(obj){
		var offsetLeft = obj.offsetLeft;
		while((obj = obj.offsetParent) && !isNaN(obj.offsetLeft)){
			offsetLeft += obj.offsetLeft;
		}
		return offsetLeft;
	}},

for me a simple line fix worked, where replacing this function with the new one that simply returns directly the position of the slider in relation to the screen so it can be compared with touch position and compute distanceToSlide properly... fixed code:

	_offsetLeft: function(obj){
		return obj.getBoundingClientRect().left;
	}

Thanks!

**Comment by seiyria** [comment]
If you'd like, feel free to submit a PR!

**Comment by tialambi** [comment]
Thanks !  solved my problem!

**Comment by fabiohaertel** [comment]
My vertical-slider wasnt working because the _offsetTop function always returned a value higher than 500. I have a pretty tricky html structure and I cant change it. 

Just wanted to say that I fixed it using the same solution:

```
_offsetTop: function _offsetTop(obj) {
   return obj.getBoundingClientRect().top;
}
```
Hope it helps someone.
Thanks
