### ISSUE TITLE
On Click Value Does not change???

### ISSUE THREAD

**Issue by mravinash** [seiyria/bootstrap-slider#384]
I am using the example 6 version of the Slider where the data changes according to the scroll of the slider. But when i click on the sliders range it doesn't update the value in the right.

Waiting for response,

Regards,
Avinash K Singh

**Comment by seiyria** [comment]
It's quite possible the examples are out of date, and a bugfix has occurred since then.

**Comment by quentindemetz** [comment]
clicking on the slider does not seem to trigger the "slide" event

**Comment by seiyria** [comment]
@quentindemetz please provide a demo when you have a problem otherwise it is nigh untraceable

**Comment by quentindemetz** [comment]
This was fixed on my side when I restarted my browser... sorry for the false alarm
