### ISSUE TITLE
How to get value from mass initialised slider?

### ISSUE THREAD

**Issue by pjcardy** [seiyria/bootstrap-slider#386]
If I put the settings for my sliders in data-slider attributes like this:

    <input id="intensity" class="slider" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="12" data-slider-step="1" data-slider-value="1"/>
    <input id="size" class="slider" data-slider-id='ex2Slider' type="text" data-slider-min="0" data-slider-max="12" data-slider-step="1" data-slider-value="1"/>

And then initialise them all at once like this:

    $('.slider').slider();

It seems to be impossible to get their value

    var render_settings_intensity = $("#intensity").getValue();
    Uncaught TypeError: $(...).getValue is not a function

Is the documentation missing the explanation for the correct way to do this, or is it just not possible?

**Comment by seiyria** [comment]
If you're using jQuery, I believe the proper way is `$('#intensity').slider('getValue');`

**Comment by pjcardy** [comment]
Thank you for your fast response, you're quite correct that does work in my situation. Perhaps it's not an omission of the documentation, but rather I should already have known.

**Comment by seiyria** [comment]
Yeah, our documentation only really covers non-jQuery usage. I honestly don't like how jQuery does their function calling, but that ship sailed 10 years ago. Good to hear it's resolved though!

You're right, we kinda make the assumption that if someone wants to do it the jQuery way, that they know that. I'm not sure if that's good or bad -- this doesn't come up too often though.
