### ISSUE TITLE
Change Event Showing [object Object]

### ISSUE THREAD

**Issue by mravinash** [seiyria/bootstrap-slider#387]
On Example 6 I am using the change event instead of slide but i am getting an error of  [object Object]

**Comment by seiyria** [comment]
Please provide a jsfiddle to show what you're doing specifically.

**Comment by mravinash** [comment]
http://jsfiddle.net/mp2aLa4s/

**Comment by seiyria** [comment]
I'm not seeing the bootstrap-slider code in there at all.

**Comment by bratzelk** [comment]
I believe the example code has a small error in it which has been copied into the JSFiddle.

`<input id="ex6" type="text" data-slider-min="-5" data-slider-max="20" data-slider-step="1" data-slider-value="3"/&t`

The very last character on this line should be `>` or `&gt;` and not `&t`

**Comment by seiyria** [comment]
Fixing that doesn't fix the jsfiddle, so that's pretty much irrelevant.

**Comment by seiyria** [comment]
Closing due to lack of (suitable) example.
