### ISSUE TITLE
Ticks won't work for me.

### ISSUE THREAD

**Issue by TeknoGod** [seiyria/bootstrap-slider#389]
Hey, I was just looking for a range slider and found this was the best looking one.
The slider is working normaly for me, but ticks wont appear at all.
I know that i'm doing something wrong, but i can't seem to find out what it is.
Script:
<code>
$("#ex15").slider({
  ticks: [1000, 2000, 3000, 4000, 5000, 6000],
  scale: 'logarithmic',
  step: 30,
});

</code>
HTML:
<code> 
input id="ex15" type="text" data-slider-ticks="[1000, 2000, 3000, 4000, 5000]" data-slider-min="1000" data-slider-max="10000" data-slider-step="30"
</code>
Messing with ticks anywhere doesn't seem to do anything for me.
Alll CSS/JS files are loaded correctly. 
I know this is all from the example, but i thought it would work.
A hint at what i got wrong, would be a great help!
(Ignore the missing < />, i'm kinda new to github comments.)

**Comment by seiyria** [comment]
We'll need to see a demo for something like this.

**Comment by TeknoGod** [comment]
Never mind, i changed it to going 250 steps per slide, and it seems like that would work for me.
Thanks for your time dude even when i could just have thought about it, awesome work btw.
