### ISSUE TITLE
ticks_labels and ticks_labels - how it works?

### ISSUE THREAD

**Issue by moshfeu** [seiyria/bootstrap-slider#391]
I've tried something like this:

('.slider').slider({
	ticks_positions: [0, 20, 40, 60, 80, 100],
	ticks_labels:[1,2,3,4,5,6]
});

with:

<input type="text" class="slider" data-slider-min="1" data-slider-max="6" data-slider-step="1" data-slider-value="[2,3]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="hide">

and those options cause some problems to the slider.

1. The input get values NaN.
2. The labels are not take  the whole width.

![preview](https://cloud.githubusercontent.com/assets/3723951/8292951/342033b4-18e7-11e5-94d2-e5560d2334a6.png)

Thanks

**Comment by seiyria** [comment]
We'd need to see a jsfiddle to know what you're doing.

**Comment by moshmoblin** [comment]
Here:

http://jsfiddle.net/p43psbj5/

Thanks!

**Comment by moshmoblin** [comment]
Never mind. It was my mistake. You can close this issue.

Thanks!
