### ISSUE TITLE
Snap doesn't work with ranges

### ISSUE THREAD

**Issue by kjaquier** [seiyria/bootstrap-slider#392]
The slider doesn't snap to the closest tick when `range` and `ticks_snap_bounds` are set to `true`.

This is because the value is an array of two elements when the slider is a range. As a consequence, at [line 1286](https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L1286), we actually compare a number with an array :

``` javascript
_calculateValue: function(snapToClosestTick) {
    var val;
    if (this.options.range) {
        // Here we do val = [something, something]
    } else {
        // Here we do val = something
    }

    if (snapToClosestTick) {
        var min = [val, Infinity];
        for (var i = 0; i < this.options.ticks.length; i++) {
            // Number - Array === NaN
            var diff = Math.abs(this.options.ticks[i] - val);
            if (diff <= min[1]) {
                min = [this.options.ticks[i], diff];
            }
        }

    // etc.
}
```

To fix this we need to know which of the two sliders is being moved. I haven't browsed the code enough yet to know if it's possible and how.

**Comment by dandrei** [comment]
You do not need to know which handler is being moved. Here is how I modified my code (everything below if (snapToClosestTick) + one new function):

        if (snapToClosestTick) {
            if (typeof val === 'number') {
                return this._snapToValue(val);
            } else if (typeof val === 'object') {
                return [this._snapToValue(val[0]), this._snapToValue(val[1])];
            } 
        }

        return val;
    },
    _snapToValue: function(val) {
        
        var min = [val, Infinity];
        
        for (var i = 0; i < this.options.ticks.length; i++) {
            var diff = Math.abs(this.options.ticks[i] - val);
            if (diff <= min[1]) {
                min = [this.options.ticks[i], diff];
            }
        }
        
        if (min[1] <= this.options.ticks_snap_bounds) {
            return min[0];
        }
        
        return val;
    },

**Comment by gkop** [comment]
This bug is still valid on master.

**Comment by hermanbanken** [comment]
A same/comparable bug occurs when (accidentally) setting the `step` to `undefined`. The value becomes `NaN` and the slider stops working. Reproduce:

````javascript
slider.setAttribute('step', undefined);
// now slide slider
````

**Comment by seiyria** [comment]
Please send a PR.
