### ISSUE TITLE
ES6 rewrite with Babel

### ISSUE THREAD

**Issue by rovolution** [seiyria/bootstrap-slider#399]
@seiyria 

With everyone making the switch to ES6 thanks to Babel, I think its time we consider another rewrite to ES6.

Thoughts?

**Comment by seiyria** [comment]
I agree with this. I've been using ES6 for some time now (courtesy of Babel) and it's made my life quite simple. I think it would make our code a lot cleaner to look at as well (classes are really, really nice).

**Comment by rovolution** [comment]
Actively working on this right now look for a PR soon!

**Comment by rovolution** [comment]
This is ready to go

**Comment by rovolution** [comment]
https://github.com/seiyria/bootstrap-slider/pull/497
