### ISSUE TITLE
Idea: Discontinue support for all package systems except NPM

### ISSUE THREAD

**Issue by rovolution** [seiyria/bootstrap-slider#400]
@seiyria 

I feel that NPM has become the dominant package management system in the web development world. I feel there really is not any value from supporting Bower/composer/the rest of these various systems.

We can keep the existing package files for those systems, but I feel that we should discontinue maintaining those version numbers and only worry about NPM. Thoughts?

**Comment by seiyria** [comment]
I strongly disagree. 

* Not everyone uses npm, and even less people use browserify. I still personally find browserify a hassle to set up so I rarely use it myself.
* I still regularly use bower
* Having a bump task for grunt/gulp to manage this is really [not that bad](https://github.com/seiyria/c/blob/master/gulpfile.js#L222-L244)

**Comment by rovolution** [comment]
thats a very good counter-argument! will close this issue.
