### ISSUE TITLE
Click events ignored when using touch screens.

### ISSUE THREAD

**Issue by rbandegibksv** [seiyria/bootstrap-slider#401]
Slide events are not triggered when using a mouse on a touch screen device like a Microsoft Surface,

**Comment by seiyria** [comment]
Related to #312, #293, #284, #256, #167, and probably more.

We need to know your OS and _specific_ browser version, as this keeps coming up.

**Comment by Jamhug1993** [comment]
I am also experiencing issues with the slider on touch screens. It won't slide whatsoever. I have tried this on Google Chrome on a Samsung Galaxy S3 Android v.4.3, and on Safari on an iPhone 6 iOS 8.4.

**Comment by CMcDev** [comment]
Has there been any progress on this? Jquery ui-slider uses something jquery.ui.touch-punch in order for this functionality to work. Not sure if a similar solution can be implemented.

**Comment by seiyria** [comment]
I requested more info from the OP and haven't gotten it, so no progress could have been made. I don't have a Surface and I suspect @rovolution doesn't either, so even if we were to work on this (see all the issues listed above for where this issue has been worked on before), we couldn't test a fix reliably.

**Comment by ksnyde** [comment]
Just out of interest, are any of you using "fastclick"? If so then I think you need to add the `needsclick` class to cancel it out for the slider.
