### ISSUE TITLE
Possible to getValue and change div

### ISSUE THREAD

**Issue by dennissew** [seiyria/bootstrap-slider#405]
I am using example 6 of your demo.
http://seiyria.com/bootstrap-slider/

I have two extra divs.
One where I want to show the value in txt (that works like your example)
And a second one where I want to change an image depended on the value of the slider.

              <input id="ex1animated" data-slider-id='ex1animatedSlider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="14"/>
              <div class="imageslidertxt1">...</div>
              <div class="imageslider1"><img src="star.png" /></div>

Is this possible?
I tried the following but that is not working, I probably miss one small thing here.
Any ideas?:

        <script type="text/javascript" charset="utf-8">
        $("#ex1animated").slider();
            
            $("#ex1animated").on("slide", function(slideEvt) {
                $(".imageslidertxt1").text(slideEvt.value);
            });                

            /* TODO */
            var mySlider = $("input.slider").slider();
            var value = mySlider.slider('getValue'); 
           if value == '1'  {
                    $(".imageslider1").html("<img src='star1.png'/>");    
                };
           if value == '2'  {
                    $(".imageslider1").html("<img src='star2.png'/>");    
                };
  
            });            
        </script>

**Comment by seiyria** [comment]
Yes, if you do both of your sets in the `slide` event handler, it should do what you want.
