### ISSUE TITLE
Refreshing is not working correctly

### ISSUE THREAD

**Issue by action-this-day** [seiyria/bootstrap-slider#407]
When I use $("element").slider("refresh"), the slider refreshes but the value is getting weird.
Instead of the values 1, 2 and 3 I get values like 1,1, 1,2 and 1,3.

Update:
jsfiddle: http://jsfiddle.net/sntcry83/1/

**Comment by seiyria** [comment]
Please make a jsfiddle.

**Comment by action-this-day** [comment]
I've added a jsfiddle

**Comment by severinmoussel** [comment]
Just found another weird behaviour in this fiddel, the refreshed slider became a range slider.

**Comment by seiyria** [comment]
I thought that WAS the weird behavior.

**Comment by action-this-day** [comment]
That's probably why the value is 1,2 instead of just 2 for example.
Why would it change to a range slider?

**Comment by severinmoussel** [comment]
I found that this.options.value is transformed to an array (lines 747 and 749), but I don't see why. And in createNewSlider (line 571), if this.options.value is an array, the slider automatically becomes a range slider.

**Comment by rovolution** [comment]
Thank you for reporting this! Could you list out the steps to re-create each of these bugs? I'd like to start by covering them with automated tests to ensure that they won't reoccur once a fix is made

**Comment by action-this-day** [comment]
What do you mean by "list out the steps to re-create each of these bugs"?
The jsfiddle demonstrates the problem and how to re-create it.

**Comment by severinmoussel** [comment]
Just sent a Pull Request with a possible fix.
The JS Fiddel works well with it.

**Comment by action-this-day** [comment]
I honestly have no idea how to create a pull request. Also, I don't have a fix for this problem, I just know it's there.

**Comment by severinmoussel** [comment]
Sorry, I meant that I just sent one ;)

**Comment by action-this-day** [comment]
Ah haha. My mistake. Thanks!

**Comment by rovolution** [comment]
fixed in v4.14.5
