### ISSUE TITLE
How to use 'formatter' option in angularjs implementation ? 

### ISSUE THREAD

**Issue by anshul-shukla** [seiyria/bootstrap-slider#411]
I am implementing your plugin angularjs extention, I want to use formatter function for tooltip value manipulation. Is there is any way ?

**Comment by seiyria** [comment]
`<slider formatter="myFormatterFunction">`

In the future, please open these issues on [the relevant project](https://github.com/seiyria/angular-bootstrap-slider/blob/master/slider.js).
