### ISSUE TITLE
Spit Tooltip. Bad positioning when init.

### ISSUE THREAD

**Issue by bigkrp** [seiyria/bootstrap-slider#418]
In first init right tooltip in horisontal range slider positioned bottom. But when i click - it positioned well.

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can see what you're talking about.

**Comment by bigkrp** [comment]
http://jsfiddle.net/hhhn1vcw/

in firebug we can see, that "tooltip-max" has class "bottom" and style
"top:18px"

**Comment by seiyria** [comment]
Your jsfiddle appears to be broken. I'm only seeing an input box, not a slider.

**Comment by bigkrp** [comment]
try plunker http://plnkr.co/edit/Jll5UlApwFifdHA2za0P?p=preview

**Comment by seiyria** [comment]
Yep, that works. I'm not seeing any tooltips period, regardless of what I do now, though.

**Comment by bigkrp** [comment]
oh.. yes, because, Bootstrap framework is not added.

http://plnkr.co/edit/Jll5UlApwFifdHA2za0P?p=preview

**Comment by seiyria** [comment]
You are correct, this is a bug. Thanks for the example!
