### ISSUE TITLE
No event for 'click' only 'slide'

### ISSUE THREAD

**Issue by gurde** [seiyria/bootstrap-slider#421]
If you look at the Example 6 from the docs, while sliding the handle the value is updated, but when you click on the track or tick, the value is not updated. So if I would like to update the value when clicking and not sliding I can't.

**Comment by seiyria** [comment]
Can you give a use case for when you would actually want to do this? Presumably, this is bad UX because there would be a desync at some point. If you want to update the value always, just use `change`.

**Comment by hushaohan** [comment]
bugged by the same problem. could you please update your Example 6 then? otherwise it's just a broken example...

**Comment by seiyria** [comment]
@hushaohan if you are in a situation where you need a `click` event then I definitely am still interested in a use-case (see my post above).

**Comment by rovolution** [comment]
@hushaohan i agree that it is confusing. I'll try to update it when i get a chance. thanks for the feedback!

**Comment by hushaohan** [comment]
@seiyria just that a user could click the middle of the bar to set the slider in addition to dragging the slider to the middle of the bar. currently for Example 6, clicking does move the slider and update the value shown in the tooltip, but not the value on the label, which, regardless of whether clicking is of good UX design, is a broken behavior IMHO.

**Comment by tboby** [comment]
@seiyria I'm manually adjusting `snap-bounds` depending on the nearest ticks on a ticked slider with different scales between different ticks. I've got this bound to `slide`, but it should ideally happen on click, otherwise the next slide snaps incorrectly.

**Comment by Asinox** [comment]
I was looking for this too +1

**Comment by lformumm** [comment]
Bind to the change event instead of slide

**Comment by seiyria** [comment]
`change` covers all changes. OP was requesting for an event that fired only on click and not on slide (which is what `slide` does). I still don't really have a sufficient use case for this situation so for now I'm going to close this.
