### ISSUE TITLE
Ticks: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by ksnyde** [seiyria/bootstrap-slider#425]
When I add ticks to my slider I get the following error:

>Uncaught TypeError: Cannot read property 'style' of undefinedSlider._layout @ bootstrap-slider.js:1012
Slider.setValue @ bootstrap-slider.js:783
createNewSlider @ bootstrap-slider.js:633
Slider.refresh @ bootstrap-slider.js:884
$.fn.(anonymous function) @ bootstrap-slider.js:134
(anonymous function) @ ui-slider.js:88

The line of code it is complaining about is:

> this.ticks[i].style[this.stylePos] = percentage + '%';

And specifically the configuration for ticks that is passed in is:

    $(target).slider({
        ticks: [30,40,60],
        min: 10,
        max: 100,
        step: 1
    });

You can see an online demonstration of this issue here: [demo](http://v1.development.ui-slider.divshot.io/). In stepping over the debug it does appear that somehow the ticks configuration was not initialised and therefore trying to address the style property for the tick fails because no DOM element exists yet.

**Comment by seiyria** [comment]
I can't quite see what version is being used here, but could you make sure that it's the latest? If it is, could you try the last few versions to see if it's still a problem?

**Comment by ksnyde** [comment]
Oh, i have 5.0.11 and its up to 5.0.13 now. I'll update and check. I also need to check and make sure that I'm not passing in string values of the numeric values.

**Comment by ksnyde** [comment]
Ok I think we should close this based on a few things on my end plus updating to the latest.

**Comment by ksnyde** [comment]
BTW, it's not fully released yet but it's starting to look pretty good: [demo](http://development.ui-slider.divshot.io). Let me know if you'd be willing to list this as an Ember extension on your page where you mention the other wrappers.

**Comment by seiyria** [comment]
I have no problem adding it whenever you're ready to share it, just ping me either via this thread, or twitter.

**Comment by rovolution** [comment]
@ksnyde that looks like an awesome plugin! My name is **ro**volution not **re**volution :smile:

**Comment by ksnyde** [comment]
@rovolution ha, sorry about that. will get that corrected in a sec.

**Comment by ksnyde** [comment]
ok, i've pushed the `0.1.0` release which is ready to be used. All references to "the revolution" have been corrected to @rovolution :smile: 

Github: [https://github.com/lifegadget/ui-slider](http://development.ui-slider.divshot.io)
Demo Site: [http://development.ui-slider.divshot.io](http://development.ui-slider.divshot.io)

**Comment by seiyria** [comment]
On your github page, could you edit the demo site into the top area of the main page?

**Comment by ksnyde** [comment]
yup, done.

**Comment by seiyria** [comment]
Added you to the README. Thanks for supporting the ecosystem!

**Comment by ksnyde** [comment]
Thanks for a great slider :smiley:

**Comment by rovolution** [comment]
hahah thanks @ksnyde!
