### ISSUE TITLE
Point to Alternate NuGet Package

### ISSUE THREAD

**Issue by ChrisMissal** [seiyria/bootstrap-slider#426]
I added this to a .NET web project and wanted to maintain the dependency through NuGet. It wasn't straightforward to upgrade though because the current package that the readme points to is out of date. I contacted the owner and waited 10 days, but decided to create an alternate package: `bootstrap-slider`

If you'd like to change the link in the readme to [bootstrap-slider](https://www.nuget.org/packages/bootstrap-slider/), feel free (or I can create the PR). I'll keep it up to date. Also, I can make anybody else an owner of the package, just let me know.

**Comment by seiyria** [comment]
I'll just update it. I'm not sure either of us have any particular interest in maintaining more packages. Thanks for doing this!

**Comment by ChrisMissal** [comment]
Great, and no problem. Feel free to tag me in any NuGet related issues. :+1:
