### ISSUE TITLE
iOS touch vs scroll

### ISSUE THREAD

**Issue by jerrylow** [seiyria/bootstrap-slider#428]
On iOS and possible Android (I have no way of testing). If I'm just scrolling but happened to tap on the screen where the slider is it changes the position of the toggle. We should potentially have a quick delay to see if the user's intention is to scroll the page or the slider.

**Comment by seiyria** [comment]
Can you please make a demo or point one out where this behavior can be
viewed?

**Comment by jerrylow** [comment]
Sure, here's a demo: http://codepen.io/anon/pen/LVKeQq

And a video: http://jerrylow.com/demo/bootstrap-slider/bootstrap-slider-demo.mp4

**Comment by tobias-dev** [comment]
I'd like to see this too. Currently vertical scrolling on smartphones is basically not possible over slider elements. Maybe the slider should only work on tapping and horizontal scrolling/sliding on touch devices, but not on vertical scrolling (especially not prevent the vertical scrolling).

**Comment by rovolution** [comment]
if you have ideas for how this could be implemented, please feel free to submit a PR. This would be a great idea to submit a PR for

**Comment by jerrylow** [comment]
Alright, got a PR in there :)

**Comment by rovolution** [comment]
fixed in 6.1.7
