### ISSUE TITLE
How to reset the sliders to their initial values after form reset?

### ISSUE THREAD

**Issue by SpinyMan** [seiyria/bootstrap-slider#429]
Example: I fill a form, drug some sliders then I click reset button and all fields become reseted except sliders...

**Comment by seiyria** [comment]
You have to call the sliders `refresh` function.

**Comment by SpinyMan** [comment]
Could u gimme an example pls 'cause nothing happens when I call it((

**Comment by seiyria** [comment]
Could you show me what you're trying to do?

**Comment by SpinyMan** [comment]
var mySlider = $('input.sly').slider({
	   handle: 'round',
	   focus: true,
	   formatter: function(val){
			if (Array.isArray(val)) {
			   if(this.step == 1) return val[0] + ' - ' + val[1];
				return $.number(val[0]) + ' - ' + $.number(val[1]);
			} 
			if(this.step == 1) return val;
			return $.number(val);
	   }
   });
   
   $('.sly').closest('form').on('reset',function(){
	   mySlider.slider('refresh');
   });

**Comment by seiyria** [comment]
Sorry, I meant in a jsfiddle. It's much easier to see what you're doing if you have a small demo.

**Comment by SpinyMan** [comment]
Just gimme a line of code how can I do right call of refresh function, pls)

**Comment by ebauman** [comment]
Wut

**Comment by SpinyMan** [comment]
var mySlider = $('input.sly').slider();
mySlider.slider('refresh'); //doesn't work and I get "cannot call methods on refresh prior to initialization"
How to call function "refresh"?
