### ISSUE TITLE
Moving slider with arrow

### ISSUE THREAD

**Issue by PaoloLeva** [seiyria/bootstrap-slider#431]
Because of accessibility compliance I need the slider to be controlled by keyboard too. 
But when moving the focus to the slider the arrows keys have no affect at all on the slider. Any idea how to solve this?
You can reproduce easily the issue on the example page:
http://seiyria.com/bootstrap-slider/

**Comment by seiyria** [comment]
You could try setting `focus: true`.

**Comment by seiyria** [comment]
This appears to work fine, and I've not been given any reason to believe otherwise.
