### ISSUE TITLE
Irregular Step Values

### ISSUE THREAD

**Issue by naresh217** [seiyria/bootstrap-slider#434]
Is there a way we can have irregular step values ? 
like 14, 90, 220, 365 etc and not allowing to select in between values

Example
http://plnkr.co/edit/jLOA080eW89Dm39MZ6Dk?p=preview

**Comment by seiyria** [comment]
Yes, use a array/hash and formatter combination like so:

```js
let myValues = [14, 90, 220, 365];
let formatter = (sliderVal) => myValues[sliderVal];
```

The slider is on a scale from 0-3 in this example.

**Comment by naresh217** [comment]
I am not clear. Can you provide an example

**Comment by naresh217** [comment]
Thanks Perfect
