### ISSUE TITLE
Click on range slider to set value when two nodes are overlapping

### ISSUE THREAD

**Issue by ziofat** [seiyria/bootstrap-slider#435]
On a range slider, consider a situation when the upper value equals to the lower value.
Then, click on the range slider on the left of nodes. Now the upper value will be set as a lower number.
![1](https://cloud.githubusercontent.com/assets/8521174/9631247/f5305fa2-51c2-11e5-8091-a9d6188bed34.gif)

**Comment by Asinox** [comment]
+1

**Comment by MojioMS** [comment]
+1 still the case

**Comment by rovolution** [comment]
fixed in 7.0.2
