### ISSUE TITLE
Fails to render properly

### ISSUE THREAD

**Issue by wolfphantom** [seiyria/bootstrap-slider#436]
The sliders where rendering correctly on the page, but I have since moved the initialization code elsewhere and now it is not working.

// Not working (input field IS modified in some way)
$(id).slider();

// Not working (input field IS modified in some way)
$('.js-rankAB').each(function(index, element) {
	var mySlider = $(element).slider();
});

// Works for the first match but not the 2nd, etc.
var mySlider = new Slider('.js-slider');

**Comment by seiyria** [comment]
Please show a jsfiddle so we can see what you're doing more clearly.

**Comment by wolfphantom** [comment]
http://jsfiddle.net/txuyuqck/

the jsFiddle works just like I expect.  My input boxes are altered, but they do not render the actual slider.

Thank for looking at this btw

**Comment by wolfphantom** [comment]
![image](https://cloud.githubusercontent.com/assets/8176629/9669674/41f8435a-524e-11e5-97eb-1725da03f5e1.png)

**Comment by seiyria** [comment]
If the jsfiddle is working, then it's something with your setup. If that's the case, then your jsfiddle is going to need to have more information in it to closer mimic your setup.

**Comment by wolfphantom** [comment]
That's going to be hard.  They were working on the site, but I moved the code and now they don't render completely.

**Comment by wolfphantom** [comment]
![image](https://cloud.githubusercontent.com/assets/8176629/9669888/6174b154-524f-11e5-8434-1af7fb6446f9.png)

**Comment by seiyria** [comment]
If we can't look at an accurate demo, there's no tangible advice we can give you.

**Comment by wolfphantom** [comment]
I can certainly appreciate that response.  Do you have any direction as to why the CSS would be blocked?

**Comment by seiyria** [comment]
What do you mean blocked? Are you not using a local copy of the CSS?

**Comment by wolfphantom** [comment]
how would I know programatically if the bootstrap-slider object was created successfully?

**Comment by wolfphantom** [comment]
Using v5.0.12

**Comment by seiyria** [comment]
If you aren't getting any errors thrown, I'd imagine it's working.

**Comment by wolfphantom** [comment]
I copied the source from the browser into jsFiddle and it's working.  I'm more confused than ever as to why it isn't on my site.

http://jsfiddle.net/txuyuqck/2/

**Comment by seiyria** [comment]
That means it's something with your site configuration, and not with the slider.

**Comment by wolfphantom** [comment]
But what's so maddening is that this same page was working with embed <script> tags this morning.  I'm just trying to move the javascript to the bottom of the page. :cry:

**Comment by wolfphantom** [comment]
var mySlider = $('#220').slider();
mySlider.slider('refresh');  // Error: no such method 'refresh' for slider widget instance

**Comment by wolfphantom** [comment]
alright.  the weird why/how it went from working to not working revolves around how Coldfusion was rendering that HTML scope-wise.  There was still a reference to jQueryUI that earlier wasn't interfering with the slider (forgot about it), but when I moved the initialization it became a problem.

Thank you for taking some time to try and figure out what's happening.

**Comment by seiyria** [comment]
Glad you got it working.
