### ISSUE TITLE
Removing the SASS file?

### ISSUE THREAD

**Issue by rovolution** [seiyria/bootstrap-slider#438]
@seiyria I would like to remove the SASS file. I think it just adds another layer of confusion, and Bootstrap officially uses LESS anyways

**Comment by seiyria** [comment]
Bootstrap 4 will be using SASS though, so... I'm not sure if it's a good idea to change now. However, I also don't know if Bootstrap 4 will be adding a slider component (if they did, there'd be no reason to keep SASS b/c they'd have an official component).

I think if we cover it fully in the contribution guide and point people to that, it'd be ok.

**Comment by rovolution** [comment]
just saw the blog post for bootstrap 4...yea lets keep it until we find out if they have a slider or not

**Comment by seiyria** [comment]
Hoping, but not really sure: https://github.com/mdo/ama/issues/201
