### ISSUE TITLE
Tick start from bottom in vertical slider

### ISSUE THREAD

**Issue by ajay-agrahari** [seiyria/bootstrap-slider#439]
Hi,

I am using vertical slider. By default Tick starts from the top. Is there any way i can change it to start from the bottom. Something like desired section in the image.

![image](https://cloud.githubusercontent.com/assets/12930853/9707251/788151dc-5555-11e5-9e5d-10c093a540dc.png)

Thanks.

**Comment by seiyria** [comment]
Try setting `reverse = true`.

**Comment by ajay-agrahari** [comment]
Thank you for your reply. I tried setting reverse : true. But its not making any change. I also tried reversed: true , but tick is still starting from the top. 

    var slider = new Slider("#mySlider", {
                                ticks: [1, 2, 3],
                                ticks_labels: ["One", "Two", "Three"],
                                value: 3,
                                tooltip: 'hide',
                                reversed: true // reverse:true dosen't work.
                            });

Could you please suggest me where should i add this reverse=true? Thanks.

**Comment by seiyria** [comment]
Right there should work. Can you throw together a jsfiddle so I can see what's up?

**Comment by ajay-agrahari** [comment]
Thanks.

http://jsfiddle.net/ajay_agrahari/n8Lkuoxs/ 

I want it to start from bottom.

**Comment by seiyria** [comment]
Ah, so this is actually a bug. The ticks don't reverse even if the slider has.

**Comment by ajay-agrahari** [comment]
I think reverse property is not required in my case. While debugging i found that default value for selection property is "before". i added property selection:'after',  which did the magic.

http://jsfiddle.net/ajay_agrahari/n8Lkuoxs/2/

Thanks.

**Comment by seiyria** [comment]
Interesting. That works for me!
