### ISSUE TITLE
JQuery slider probably in conflict with Bootstrap

### ISSUE THREAD

**Issue by kdx2** [seiyria/bootstrap-slider#442]
OK, ladies and gentleman, here comes the problem. I'd like to achieve the following, to have jQ sliders and a BS menu. Up to now I've built sliders and everything was fine but after the work on the menu began and I initialized all the BS stuff - the .css/jq-min.js/js-min.js and I received weird 'cuts' on my sliders' handles as well as some odd front changes, like lowered letter size on my project. I've understood that this happens because jQ has .slider and BS has .slider which causes a namespace conflict. However, i've no idea how to fix this. Once again, the goal is to load use JQ slider  (which is actually a UI) with BS loaded on background without resulting in conflicts. If you'd need some code, feel free to ask me. I'll start with a slider and the libraries initialization.
![sadds](https://cloud.githubusercontent.com/assets/14055242/9790754/6ca7a860-57e0-11e5-84d2-fa87870a8fc6.png)

//Libs
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
 <link rel="stylesheet" href="jquery-ui-1.11.4.custom/jquery-ui.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="BS 3.3.5js/bootstrap.min.js"></script>
 <script src="jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>
   <script src="jquery-ui-1.11.4.custom/external/jquery/jquery.js"></script>

//a slider sample
$(document).ready(function(){
    $("#slangle").slider({
    	min:0,
    	max:89,
    	value:15,
    	range:"min",
      animate: true,
    	slide: function(event, ui){
         $("#angle").val(ui.value); 
        trajgen();
    	}
    });

**Comment by seiyria** [comment]
Please see this section in the readme: https://github.com/seiyria/bootstrap-slider#what-if-there-is-already-a-slider-plugin-bound-to-the-jquery-namespace

**Comment by kdx2** [comment]
The solution is to make it a bootstrap slider? That's what I'm aiming to avoid... hm
