### ISSUE TITLE
How refresh the slider when is an ajax call?

### ISSUE THREAD

**Issue by Asinox** [seiyria/bootstrap-slider#446]
Hi, nice bootstrap component, i have just a question, maybe the issue is my low jquery level.
I have 2 sliders, i call them using ajax, but i don't know how reset/refresh them.

The point is:

After the ajax call, there is a few buttons, the user can select just one button, with those buttons came the sliders, but if the user change and select other button i want to reset/refresh the slider, i can't figure out how.

I use a "delegate" for the buttons (after the ajax) like this: `$("parentElement").on('click', '.btn', function (el){ });`  to make the buttons works correctly but, i don't know how reset the slider when the button was clicked, remember buttons and sliders came after ajax call.

Any idea?
Thank you

**Comment by seiyria** [comment]
See [here](https://github.com/seiyria/bootstrap-slider#functions) for relevant documentation. Either call `setValue` or `refresh` depending on what effect you want.

**Comment by phlegx** [comment]
@seiyria read here #714. Refresh don't seams to work!

**Comment by tonyhogben** [comment]
@phlegx did you resolve this as I'm experiencing the same problem?
