### ISSUE TITLE
Can't create a slider on elements that are not yet in the DOM

### ISSUE THREAD

**Issue by cmdelatorre** [seiyria/bootstrap-slider#447]
Hello, I've run into this issue and would like to know if there's anything that can be done about it.

In our Backbone-based application, we usually "render" our widgets completely before inserting them in the DOM. This is not possible when using your slider, I get the following error:

```Uncaught TypeError: Cannot read property 'insertBefore' of null  (bootstrap-slider.js:497)```

Here's an example: http://jsfiddle.net/litox/yjqooxgq/

As long as I understand the problem is that the target ```input``` is not in the DOM. Is that right?

Any ideas?

**Comment by seiyria** [comment]
I've never used backbone before so I can't be much help here, sorry.

**Comment by cmdelatorre** [comment]
Ok, forget about backbone. The example in the fiddle (http://jsfiddle.net/litox/yjqooxgq/) is not even using Backbone but still exposes the issue. Any ideas?

**Comment by seiyria** [comment]
It's not on the DOM so it can't insert the slider container onto the DOM.

**Comment by cmdelatorre** [comment]
Ok. Thanks for the quick reply.

**Comment by cmdelatorre** [comment]
Obviously you are not interested in this issue. But in case somebody finds it useful, I found a workaround: apparently I don't need the target input or its container to be in the DOM. I just need that the target input have a parent. 

So, the following jsfiddle: http://jsfiddle.net/litox/yjqooxgq/1/  shows an example of the slider being created _offline_ and then appended to an existing element.

**Comment by seiyria** [comment]
I'll close this then, since you've resolved your issue.
