### ISSUE TITLE
change Event constantly fires

### ISSUE THREAD

**Issue by lformumm** [seiyria/bootstrap-slider#448]
I want to call a function, after the slider has changed. The problem is that, when I grab the slider and move it, the EventHandler constantly fires and calls the function. Is there a way just to fire at the end, similiar to SlideStop (which only works on sliding)? 

$("#rangeSliderPrice").on("change", function(slideEvt) {
//call function
}

**Comment by seiyria** [comment]
If you grab the slider and move it, that's sliding. It makes sense to bind to slideStop in this case as it's the only situation in which it will be moving around a lot. Otherwise, use change.
