### ISSUE TITLE
Slider resizes and then disappears

### ISSUE THREAD

**Issue by mingusthecat** [seiyria/bootstrap-slider#452]
Hi
we have implemented the slider on our page, but it has a strange behaviour. At the beginning it loads correctly, then when we slide it, it resizes in smaller and then it deseappers.
This is the page where the slider is implemented
https://www.neting.it/risorse-internet/generatore-lorem-ipsum-online.html
Probably is a conflict of some sort with other js. The same problem occurs on FF, Chrome and Safari.
Thanks for your help
Luca

**Comment by seiyria** [comment]
Please try to reproduce this on a jsfiddle - having a minimal reproduction case is very valuable for oddities like this.

**Comment by mingusthecat** [comment]
ok I got it, sorry to bother you. Its a conflict with mootools. Thank you

**Comment by seiyria** [comment]
No worries - this is why we have people make a jsfiddle :P
