### ISSUE TITLE
Use initial value specified in value=""

### ISSUE THREAD

**Issue by digerata** [seiyria/bootstrap-slider#455]
I'm curious as to the decision about not pulling the initial value of the slider from the value attribute of the input field.

It seems that would be the ideal place to initialize the slider control.  I see that adjusting the slider does update the value attribute and also the slider-value attribute.

It seems that it the best behavior would be to accept the value attribute first and the data-slider-value could override that if present.

**Comment by seiyria** [comment]
Not sure why you'd ever want to pass it in twice (ie, accept `value` but allow a `data-slider-value` override -- that'd basically be `<input value="1" data-slider-value="1" />` which makes no sense to me).

It was likely done to keep it consistent. This means we're not looking for `value` in some cases, but other cases we want `data-slider-reverse`. Introducing this as you're suggesting would add more (needless) complexity on top of the library.
