### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by localshop** [seiyria/bootstrap-slider#457]
bower seiyria-bootstrap-slider#*         mismatch Version declared in the json (5.0.13) is different than the resolved one (5.1.1)

**Comment by tayden-hakai** [comment]
Also, adding jquery and bootstrap as dependancies would be helpful

**Comment by seiyria** [comment]
Neither of them are dependencies.

**Comment by tayden-hakai** [comment]
My mistake, sorry. I'm trying to inject dependancies using bower and am also getting errors. I thought this was why.

**Comment by seiyria** [comment]
The versions match currently, so this should not be a problem going forward.
