### ISSUE TITLE
Bootstrap slider tooltip not working on mobile chrome browser

### ISSUE THREAD

**Issue by savinmb** [seiyria/bootstrap-slider#460]
Hi

Iam currently using bootstrap slider for age range in my project everything working fine in desktop but in mobile browser chrome tooltip is not showing.Please provide a solution

Url ->https://mixfame.com/talents

**Comment by seiyria** [comment]
Try using `tooltip: always` for mobile browsers. Also, please only link to a jsfiddle - it's hard to differentiate between an isolated problem and an integration problem otherwise.
