### ISSUE TITLE
Resize issues, not responsive labels!

### ISSUE THREAD

**Issue by adameska** [seiyria/bootstrap-slider#464]
I fixed a bug, your labels aren't responsive at all, can you please incorporate these changes?
line 649:
this.resize = this._resize.bind(this);
line 657:
window.addEventListener("resize", this.resize, false);

line 1134:
_resize: function (ev) {
				this._state.offset = this._offset(this.sliderElem);
				this._state.size = this.sliderElem[this.sizePos];

				this._layout();
			},

**Comment by seiyria** [comment]
If you could send us a PR and a jsfiddle showing that these changes do indeed fix the issue, plus a test or two to verify that it won't happen again going forward, that'd be awesome!

**Comment by adameska** [comment]
I'm having issues importing the bootstrap-slider.js file to the jsfiddle but here's basically what i'm doing:
http://jsfiddle.net/4e07rLz1/7/

**Comment by seiyria** [comment]
Try using this: https://rawgit.com/

**Comment by adameska** [comment]
Updated, forgot to remove the period in the url. You can see when you resize the screen the labels are stuck, but when you click on it then it redraws the labels correctly.

**Comment by adameska** [comment]
Also, is there anyway to default to null? I can't figure out how to initialize without a value selected in case they don't want to rate the app.

**Comment by seiyria** [comment]
There is no way to do that, no. It does not make sense for a slider to not have a value, as it would be confusing to interact with. Most users would wonder what it is.

**Comment by rovolution** [comment]
Fixed in [v5.3.4 and v5.3.5](https://github.com/seiyria/bootstrap-slider/blob/master/CHANGELOG.md#534--2015-12-27)
