### ISSUE TITLE
tooltip position is wrong

### ISSUE THREAD

**Issue by ldllidonglin** [seiyria/bootstrap-slider#465]
```
} else {
					tooltips.forEach(function(tooltip){
						this._addClass(tooltip, 'top');
						tooltip.style.top = -this.tooltip.outerHeight - 14 + 'px';
					}.bind(this));
				}
```
the code "-this.tooltip.outerHeigh" is "undefined" ,so the tooltip's position is in the bottom of slider.

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can double check that this is a bug.

**Comment by ldllidonglin** [comment]
sorry I was wrong.no bug,thinks
