### ISSUE TITLE
why set the width in the css not work,always 210px,but set width in the element.style is work

### ISSUE THREAD

**Issue by ldllidonglin** [seiyria/bootstrap-slider#466]
http://jsfiddle.net/lidonglin/kn39x8ps/

**Comment by seiyria** [comment]
please be more descriptive, I do not fully understand what you're talking about.

**Comment by ldllidonglin** [comment]
<div id="map-load1"></div>
#map-load1{
    width:800px;
}
$("#map-load1").slider();
i want the width of the slider is  800px,but the resutl is 210px,just as the jsfiddlehttp://jsfiddle.net/lidonglin/kn39x8ps/

**Comment by seiyria** [comment]
Change your markup to be more like this: http://jsfiddle.net/gvz3jn3a/

**Comment by ldllidonglin** [comment]
thinks，the recommended markup is to have a parent element wrapped slider element?
i look the source code .in the 389 lines 
```
var origWidth = this.element.style.width;
```
in the 573 lines 
```
this.sliderElem.style.width = origWidth;
```
if the above code is  used to set the width of slider,i can write like this http://jsfiddle.net/lidonglin/kn39x8ps/1/
