### ISSUE TITLE
Set Real values in slider input instead of tick values

### ISSUE THREAD

**Issue by naresh217** [seiyria/bootstrap-slider#469]
I would like to set Real values in slider input to be submitted after changing bootstrap slider

$(document).ready(function(){
  
  var realValues = [14, 60, 120, 365];
  var labelValues = ['14d', '60d', '120d', '365d'];
  
  var r = $('#ex1').slider({
    max: 3,
    min: 0,
    step: 1,
    ticks: [0, 1, 2, 3],
    formatter: function(val) {
      return labelValues[val];
    }
  })
  .on('change', function(data){
   
     $("#ex1").val(realValues[data.value.newValue])
  })
 ;

Plunker: http://plnkr.co/edit/Fnsbqw?p=preview

**Comment by seiyria** [comment]
I don't understand what you mean by "real value". If you want those values, set them on the slider (iirc there is an option for this). Otherwise, handle this in your validation logic.

**Comment by naresh217** [comment]
i have called slider on element #ex1, after an change i would like to modify its value
tried with below logic
 .on('change', function(data){
        $("#ex1").val("100")
  })

**Comment by seiyria** [comment]
Yes, that won't work, because your slider only goes from 0-3. If you want the values to be actually set on the slider you will need to use `ticks` to do so.
