### ISSUE TITLE
Detect change in range slider

### ISSUE THREAD

**Issue by diegoaguilar** [seiyria/bootstrap-slider#473]
When using a range slider, I want to get which, either start or end has changed. I'm trying to bind events or use a `$watch`  but it's getting buggy to know which is the one being changed:

Using a `$watch` this is what I try:

	$scope.$watch('rangeSlider.value', function (newValue,oldValue) {
		var changed = newValue[0] === oldValue[0] ? newValue[1] : newValue[0];
                ....
                ....
	});

But as I say, it's not reliable. Would you suggest any alternative?

**Comment by MojioMS** [comment]
this? https://jsfiddle.net/mr4q4Ltg/6/

**Comment by seiyria** [comment]
I would need to see an example and a better explanation as to why it's not reliable. Based on the example provided by @MojioMS it seems to be just fine. That said, it may be wiser to use the angular wrapper I've made ([see here](https://github.com/seiyria/angular-bootstrap-slider)), but I don't know your use case.
