### ISSUE TITLE
Use text-shadow for custom handle (symbol or font-icon)

### ISSUE THREAD

**Issue by bjarnef** [seiyria/bootstrap-slider#475]
When you set custom handle, it would be great if you could choose if it should use box-shadow for the handle (default) or text-shadow for the icon instead.

E.g. see Example 10 http://seiyria.com/bootstrap-slider/

You might noticed the box around the star. It is not very clear because of the opacity, but with set to more than 50% it might not be pretty.

In that case **.slider-handle** could have disabled box-shadow and instead use text-shadow for **.slider-handle.custom::before**

```
.slider-handle {
    -webkit-box-shadow: none;
    box-shadow: none;
}

.slider-handle.custom::before {
    text-shadow: 1px 1px rgba(0,0,0, .35);
}
```

When using a rect background-image it might be fine with box-shadow.

Of course I can always just overwrite the default css.

**Comment by seiyria** [comment]
I think this is a bit of feature creep. In this case, it would be better to use your own CSS to accomplish this task.
