### ISSUE TITLE
Tooltips showing up only when mouse over handle

### ISSUE THREAD

**Issue by drhouse82** [seiyria/bootstrap-slider#476]
Hi there,
I have a problem when using several sliders close to each other.
https://jsfiddle.net/txuyuqck/8/

As you can see, if one tries to grab the handle of the inner two sliders, the tooltip of another slider is showing up and is preventing you from reaching the handle.

Is it possible or feasible to only show the tooltip when the mouse is really over the corresponding handle? Right now, the tooltips also shows up when the mouse is moved over the still invisible tooltip.

Thanks in advance.

**Comment by seiyria** [comment]
You can do pointer-events: none to prevent this behavior, but this isn't anything we should build into the library, as it's a rather specific case fix.

**Comment by drhouse82** [comment]
OK.
For the record (and if there's any other noob like me with the same issue):
the jquery command $(".tooltip", $(".slider")).css('pointer-events','none') or likely similar css operations will do it. (for all tooltips of all sliders)
Thanks anyways.
