### ISSUE TITLE
Hide first and last slider-tick round

### ISSUE THREAD

**Issue by Valonix** [seiyria/bootstrap-slider#477]
Hello, how i can hide this elements? 
I try 

.round:first-of-type{display: none;}
and 
.slider-tick.round:first-child{display: none;}
.slider-tick.round:last-child{display: none;}

And it is not work....

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can see specifically what you're doing.

**Comment by Valonix** [comment]
i found solution by my self. Thanks for all :)
