### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jcbvm** [seiyria/bootstrap-slider#480]
Can you please provide a changelog for future releases. It's hard to see whats changed right now.

**Comment by seiyria** [comment]
I'm not sure either of us want to write something manually and I think we're too far along to add something like conventional changelog (you have to start with that for it to be effective imo).

**Comment by jcbvm** [comment]
I think a changelog for older releases is not needed, but a list of the main changes for new releases (notes added to the release tag) would be nice. So you can easily see if it has breaking changes for example.

**Comment by iagopiimenta** [comment]
+1

**Comment by n-rodriguez** [comment]
+1

**Comment by rovolution** [comment]
We can definitely start maintaining a changelog

**Comment by rovolution** [comment]
Just added this in

https://github.com/seiyria/bootstrap-slider/blob/master/CHANGELOG.md
