### ISSUE TITLE
How to set the value on slider after fetching the value from db

### ISSUE THREAD

**Issue by joyeshkakkar** [seiyria/bootstrap-slider#482]
I want to set the slider value to a specific location after fetching the text value from database.

I wrote the following code in document.ready

$('#distanceRadius').attr("data-slider-value",8);

where #distanceRadius is the id of slider component.

After executing above line, I try to print the value of slider component and it gives me the value 8 using below code.
console.log($('#distanceRadius').attr("data-slider-value"));

**Comment by seiyria** [comment]
According to [this list](https://github.com/seiyria/bootstrap-slider#functions):

`$('slider').slider('setValue', newValue);`

if you have further troubles please give us a jsfiddle.
