### ISSUE TITLE
Chrome/Split tooltip on range slider not aligned

### ISSUE THREAD

**Issue by dreamcasting** [seiyria/bootstrap-slider#483]
I'm using Chrome 47 for Windows and a range slider with split tooltips which are also set to always show. Until I click on the slider the tooltips are always misaligned, then they jump to the correct place. This is within a bootstrap modal. I've changed the tooltip CSS but then the tooltips will jump on click and be incorrect afterward. 

![image](https://cloud.githubusercontent.com/assets/4613308/11657757/28e6e136-9d7c-11e5-8c4f-2d2eb680cefd.png)

The code I'm using is pretty straight up -  `function gradeFilter() {
                    var slider = $("#gradeFilter").bootstrapSlider({
                        tooltip: 'always',
                        tooltip_split: true
                    });`

**Comment by seiyria** [comment]
Regardless of how simple the code is, we always ask to see an example. Please show one.

**Comment by dreamcasting** [comment]
You got it - sorry for the delay, had to extract the relevant code. 

http://jsfiddle.net/cwssL37d/

**Comment by ctrl-f5** [comment]
I'm having the same ussie, with without the split tooltip. It's also reproducable by the given example from @dreamcasting (change `tooltip_split: false`).

**Comment by fleiflei** [comment]
Having the same problem with tooltip_split:false. When initialized the tooltips inline css "margin-left" value is always set to "0px".

**Comment by golear91** [comment]
Having the same issue.  When the tooltip is initialized it has `margin-left: 0px` after I click on the tooltip it gets set to `-20.5px`.  I am getting around the problem by calling `$('#ex1Slider .tooltip-main').css({'margin-left': '-20.5px'});` after the initialization of the slider.

**Comment by sweco-senari** [comment]
@golear91 sweet workaround! 'margin-left': '-40.5px for me when using tooltip_split: false.

**Comment by sorryjack** [comment]
how to implement that css after initialization? I am having same issue.

**Comment by goleary** [comment]
@sorryjack just use the code I pasted above.  It is basically selecting the element using jquery and then applying a css attribute

**Comment by sorryjack** [comment]
@goleary was trying your code many times, seems not worked. then I found that it actually triggered. 
then I modify the .tooltip-main to .tooltip-min and .tooltip-max cz I did tooltip_split: true

$('.filter-harga .tooltip-min').css({'margin-left': '-21px'});
$('.filter-harga .tooltip-max').css({'margin-left': '-41px'});

now it worked. thanks man.
