### ISSUE TITLE
add new input value for ticks_labels

### ISSUE THREAD

**Issue by imado7** [seiyria/bootstrap-slider#484]
Is there any way to make (ticks_labels) as an input value and show it in tooltip or external div, like ticks. 

example 13
on:

http://seiyria.com/bootstrap-slider/

thanks
Imad

**Comment by seiyria** [comment]
If I understand you correctly, no, this is not possible.

**Comment by imado7** [comment]
i see, 
can replace the data assigned to :  ticks: [1, 2, 3, 4, 5],
and show instead  : ticks_labels: ['Early', 'Morning', 'Lunch', 'Afternoon', 'Evening'],
in hidden input.

**Comment by seiyria** [comment]
To do that, you can use the `formatter` function.

**Comment by imado7** [comment]
but i want them to appear in new div not the tooltip

**Comment by seiyria** [comment]
Then no, that's not possible, and it is not really in scope for this project. If you really want this, you'll have to make the formatter function do it all the same - just have the formatter function output to your div and also in the tooltip, you can try hiding the tooltip via CSS and doing that.

**Comment by imado7** [comment]
how to use the formatter to pass ticks_labels data value to appear in tooltip or new div, sorry i'm not that strong in javasrcript :)

**Comment by seiyria** [comment]
```formatter: function(val) {
$('#myplace').text(val);
return val;
}```

**Comment by imado7** [comment]
thats cool its work, but i need ticks_labels value to appear in ('#myplace') instead of ticks

**Comment by seiyria** [comment]
... then use the same array to look up the correct value?

**Comment by imado7** [comment]
i'm using text string if I change the numbers the slider wont work, i'm trying to replace the value of ticks with strings.
