### ISSUE TITLE
How to make slider line in 1 px width?

### ISSUE THREAD

**Issue by 1st** [seiyria/bootstrap-slider#485]
Hello.

I need to make scrolling line very light, in 1px width. How to do this?

Can I use parameters to constructor, or I need to hack the CSS to specify parameters?

Thanks.

**Comment by 1st** [comment]
I mean how to do this style:

![screen shot 2015-12-08 at 22 56 47](https://cloud.githubusercontent.com/assets/630224/11668274/00aa0f8a-9dff-11e5-8f9c-3b706658c0e5.png)

**Comment by seiyria** [comment]
Use CSS.

**Comment by 1st** [comment]
It will be good to use an option to configure the slider, instead of CSSing. Because time to time it can break slider from work properly when upgrading to new version of Slider with changes in the markup.

My results:
![screen shot 2015-12-08 at 23 07 12](https://cloud.githubusercontent.com/assets/630224/11668666/23754fd2-9e01-11e5-942c-bc340f1e2d1a.png)

And code (maybe someone will save few minutes on coding):
```
/*
 * Customize slider.
 */
#sidebar .slider-track {
  background: #51A7F9;
  height: 1px;
  margin-top: 3px;
}
#sidebar .slider-handle {
  background: #51A7F9;
  margin-top: -7px;
  width: 14px;
  height: 14px;
}
```

It will be good to turn-off the colour shadow on the slider at the left side of handle. Now it show a little bit lighter colour.

**Comment by seiyria** [comment]
This looks nice. I am not sure it's something we can pull upstream as it's mostly a cosmetic change - if we pulled in every cosmetic change we'd have a lot of maintenance to do. Nice work!

**Comment by 1st** [comment]
Thanks @seiyria. It's just a styling. Can be used as pluggable css files, like it does in Twitter Bootstrap, when you need to change style from one to another.

Aslo, can you advice me how to change the colour of line *before* the handle? Thanks.

**Comment by seiyria** [comment]
Yes, but I don't think the maintenance is worth it. 

Before the handle could be either `.slider-track-low` or `.slider-selection`

**Comment by 1st** [comment]
Thanks.
