### ISSUE TITLE
Use callback as part of passed parameters to constructor

### ISSUE THREAD

**Issue by 1st** [seiyria/bootstrap-slider#486]
Now I need to call `.on("slide", function() {...})` but it will be good option to pass this callback function to the `.slider()` when I initialise it. Something like this:

```js
$('#my-slider').slider({
    formatter: function(value) {
      return value + '%';
    },

    on_change: function(val) {
        console.log("Value changed to:" + val);
    }
});
```

Thanks.

**Comment by seiyria** [comment]
I would not oppose such a change if submitted via a PR, but what is the advantage of doing it that way as opposed to the current way?

**Comment by 1st** [comment]
It's a more convenient way to pass all in the constructor instead of adding dot and something. It's generally a style and don't add something in general.
