### ISSUE TITLE
Change width dynamically

### ISSUE THREAD

**Issue by 1st** [seiyria/bootstrap-slider#488]
I created slider in a sidebar. When I resize the window - the slider width don't changes according to new with of the main container.

![screen shot 2015-12-08 at 23 42 23](https://cloud.githubusercontent.com/assets/630224/11669490/96262796-9e05-11e5-967a-0b42092a89cc.png)

How to handle this situation to tell Slider to fill full width of a container? Does the `Slider` have an option for this?

**Comment by seiyria** [comment]
No. Set it to width: 100% and it should be fine.

**Comment by 1st** [comment]
Sorry, set to what? I crated the `<input ...>` and applied a `.slider()` to it. What I need to set to `100%`? Thanks.

**Comment by seiyria** [comment]
Set the CSS for `.slider` to `width: 100%`.
