### ISSUE TITLE
value selection

### ISSUE THREAD

**Issue by psuplat** [seiyria/bootstrap-slider#491]
Slider works correctly when sliding action is used. However if you click on the slider to set the marker at certain position it does not work.

Open the demo page and see example 6:
 - if you slide the marker the value is reflected on the right side label
 - clicking on any place to set the marker has no effect on the right side label value

**Comment by NikolinNgjela** [comment]
Hi Psuplat, 
I also had the same issue,

At the JavaScript  function you must  change the third line that is: $("#ex6SliderVal").text(slideEvt.value);

with ==> $("#ex6SliderVal").text(slideEvt.valueOf());  
and the value will be appeared on the right side label.

**Comment by MojioMS** [comment]
the value does update with .valueOf(), but(!) as psuplat mentioned: the "slide" event is not triggered, if a user clicks on the slider to set the marker at a certain position.

**Comment by seiyria** [comment]
Yes, you have to use the `change` event.
