### ISSUE TITLE
Setting range to [min, min]

### ISSUE THREAD

**Issue by JoannaFalkowska** [seiyria/bootstrap-slider#492]
It would be nice to be able to set range to [min, min].

Currently it's possible, but only with big step. When I use values from 0 to 100 and step 5, the minimum range I can set is [0,5].

(In my use case, I have prices from $0 to like $200 and it will be particularly important for users to be able to set "only free" option on the slider.)

Is there some workaround or solution I overlooked?

**Comment by seiyria** [comment]
Have a checkbox next to it that says "only free" and checking it disables the slider and makes the value 0 always. That's much more explicit. Having a slider set to [min, min] defeats the purpose of a slider.

**Comment by JoannaFalkowska** [comment]
Hey, I'm not to decide if there's a checkbox there or not, it's up to my UI designer. I'm asking for a funcionality for slider which actually IS there but not in all cases. Specifically I'm interested why doesn't it work in all cases.

**Comment by seiyria** [comment]
A slider is not a slider if there's only one value. This is not a case I think should be supported, either.

**Comment by JoannaFalkowska** [comment]
But is it supported right now. In some cases. Why wouldn't you support both [min, min] and [min, step] options and let people decide which one do they want to use, with [min, step] default? Or just make [min, step] the only behaviour if you really don't want to support something just because you don't want to. Right now it doesn't make any sense, it's inconsistent.
