### ISSUE TITLE
About textfield in the examples

### ISSUE THREAD

**Issue by fgfernandez0321** [seiyria/bootstrap-slider#493]
The example #8 uses type attribute as "text" for that reason when you open any view shows a textfield during the render. The solution in this case is to declare type as "hidden".

Example 8:
<input id="ex7" type="text" data­slider­min="0" data­slider­max="20" data­slider­step="1" data­slider­value="5" data­slider­enabled="false"/>

**Comment by seiyria** [comment]
I can't replicate this. This needs an example, browser, or maybe a gif.
