### ISSUE TITLE
Slider does not resize

### ISSUE THREAD

**Issue by kikrahau** [seiyria/bootstrap-slider#495]
Hi!
I would like to create a filter column which includes sliders. My problem is that the slider does not resize when the screen size changes from lg -> md -> sm. It overflows on the right.

I created a fiddle to show the problem: 
https://jsfiddle.net/3xjn8etd/1/

Would appreciate if someone has a solution.

Thanks a lot!

**Comment by seiyria** [comment]
Add this to your CSS:

```
.slider.slider-horizontal {
  width: 100%;
}
```
