### ISSUE TITLE
6.0 no longer allows loading of bootstrap-slider module.

### ISSUE THREAD

**Issue by bikrdotnet** [seiyria/bootstrap-slider#498]
building on heroku with npm was following #master, builds stopped succeeding with launch of 6.0.0.

**Comment by rovolution** [comment]
What error are you seeing?

**Comment by rovolution** [comment]
ah i see it (wrong pathname for main in package.json) fixing now

**Comment by rovolution** [comment]
try latest version on NPM it should be resolved

**Comment by rovolution** [comment]
@bikrdotnet did that resolve your issue?

**Comment by bikrdotnet** [comment]
Will test tonight, thank you for being so quick!!

**Comment by bikrdotnet** [comment]
Sorry I didn't get to reply but 100% fixed!
