### ISSUE TITLE
Implementing a minRange and maxRange

### ISSUE THREAD

**Issue by JasonMHirst** [seiyria/bootstrap-slider#499]
Love the plugin, but have encountered an issue which I don't know how to resolve without changes to the code and I think may benefit others.

Would it be possible to have two additional options, for the minimum and maximum values allowed in a range?

For example, I have 4 sliders on my page
* one 1985 to 2020,
* the other 1990 to 2014 and,
*  2 others 2000 to 2014

The problem is that if I selected 2010 on every slider, the circular handle is in a different horizontal position (apart from the last 2).

By having a minRange and maxRange I could set ALL sliders to start at 1985, end at 2020 BUT the minimum and maximum values I select are within the same range and thus the circular handle would appear in the same position on all.

This method also allows dynamic updates to the sliders, so I could allow the user to select dates from 2000 to 2008 (out of a slider of 1990 to 2030) but then, depending on other actions, extend the maxRange to 2015 without the circular handle jumping about.

**Comment by seiyria** [comment]
I'm not sure how I feel about this, but I'm mostly against it. It creates a lot of dead space and unselectable area, which is not particularly intuitive and is quite difficult to show to a user. If I were using something like this and I couldn't move the slider all the way to the left or right, I would be pretty frustrated, given that's what sliders are for.

**Comment by phazei** [comment]
+1 this sooo much.  I've been scanning the issues looking for exactly this.

Think of it more like disabling part of the slider.
I have 1-10 selection sliders, but if the user selects particular other options, they are limited to a calculated subset of that.  So perhaps 3-8.5.  1-3 and 8.5-10 would be grey, and 3-8.5 would have a blue background, so it would be obvious what range they have available to them.

The slider already has a min/max, which I'm using as well as ticks.  I thought if I had the ticks, outside the min/max values it would just work that way, unfortunately not.

**Comment by seiyria** [comment]
Fundamentally, I still don't agree. If you want to manipulate the display, then manipulate the min/max/ticks/etc. It's not obvious if part of a control is disabled. I can think of no components in any popular framework (especially a slider) that disable only a _part_ of a control, they generally hide the parts that aren't relevant. That is what you should do here. 

If you have a problem where you have too many sliders and they don't line up visually, then it's possible you have too many sliders and should attempt to design a more intuitive interface for users.
