### ISSUE TITLE
Disable a value

### ISSUE THREAD

**Issue by BenBish** [seiyria/bootstrap-slider#50]
Thanks for all your work on a great slider. I have an unusual case though where I need to disable a single value somehow.

An example illustrates this best.

Values: 1, 2, 4

I am not sure how to achieve this though. Thanks!

**Comment by pinkynrg** [comment]
I do have a similar problem. I have a setup where the valid and only values are 2,3,4,6,7. I would like them to be equidistant so this is my actual setup:
`var slider = $("#status_id").slider({
    id: 'status_id',
    ticks: [2,3,4,6,7],
    value: 2,
    ticks_labels: item['labels'],
    tooltip: 'hide',
    ticks_positions: [0,25,50,75,100]
});`

How can I have a setup where value 5 is disabled? Sorry if I'm asking an already solved issue but i coudn't figure out the solution by reading this ticket.

thanks,
