### ISSUE TITLE
Data attributes for individual tick marks

### ISSUE THREAD

**Issue by alexweissman** [seiyria/bootstrap-slider#500]
Is there a way to capture the values of individual tick marks based on their jQuery selectors?  For example, I'd like to tie in some functionality to show the corresponding tooltip when I hover over a particular tick mark.

**Comment by seiyria** [comment]
No. This is scope creep; you can do this in your formatter function.

```
var ticks = [0, 25, 50, 100];

var formatter = function(value) { 
  if(ticks[value]) return "custom" + value;
  return value;
}
```

**Comment by alexweissman** [comment]
That isn't quite what I meant.  For example, let's say I'd like the tooltip and low-track to "follow" my pointer as I hover over different tick marks.  To do this, I need some way of identifying which tick mark is being hovered at any given time.  But at the moment, all of the tick mark elements are completely identical with no unique identifying value.

The only way I could do this was by going back and manually calculating the relative index of the tick marks after initialization:

```
var ticks = [0, 25, 50, 100, ...];
$(".slider-tick").each(function () {
    var percent = $(this)[0].style.left;
    var idx = parseFloat(percent)*ticks.length/100;
    $(this).attr("data-index", idx);
});
```

IMO, this is something that the plugin should do.

**Comment by seiyria** [comment]
Okay, so what you don't want is an event, but rather, you want maybe a data attribute on each tickmark to identify it? That's a bit different than how I read your original request, but I think that's sensible.

**Comment by alexweissman** [comment]
yup, sorry I was tired when I first opened the issue.

**Comment by phazei** [comment]
I was thinking of something the same.
A data attribute wouldn't be bad, but it would still be difficult to target with that.
A css class would be good.
Though I think the easiest would be a simple grouping of the divs.
Currently all the ticks are inside div.slider-track.
Since there are a lot of other div elements in there, it makes it difficult to target with css.
If they were in say div.slider-track > div.slider-ticks then
.slider-tick:nth-of-type(n) could be used to selectively target each tick individually, presuming they are in the same order in the dom as they are in the array they're entered as, which seems to be the case.

Or that in combination with a class "slider-tick-{value}"

**Comment by phazei** [comment]
I was thinking of something the same.
A data attribute wouldn't be bad, but it would still be difficult to target with that. A css class would be better, maybe "slider-tick-{value}".
Although, along the same vein, it would also help to have a simple grouping of the tick divs in their own container, similar to how the labels have their own container.  Currently all the ticks are inside div.slider-track with  a lot of other div elements in there which makes it difficult to target with css.
If they were in say div.slider-track > div.slider-tick-container then .slider-tick:nth-of-type(n) could be used to selectively target each tick individually, presuming they are in the same order in the DOM as they are in the array they're entered as, which seems to be the case.

My particular case is wanting to individually style certain ticks.

**Comment by rovolution** [comment]
@phazei those are great ideas! let me see if i can whip something up

**Comment by rovolution** [comment]
@phazei 

> Currently all the ticks are inside div.slider-track with a lot of other div elements in there which makes it difficult to target with css.

I just did an inspect element on the examples page, and this does not appear to be the case:

![image](https://cloud.githubusercontent.com/assets/437318/16787169/438fee00-4868-11e6-8983-3061719912d1.png)

**Comment by rovolution** [comment]
@alexweissman adding a data attrib to each tick seems like a pretty reasonable request

**Comment by rovolution** [comment]
@phazei i see what you are saying now

![image](https://cloud.githubusercontent.com/assets/437318/16787257/f1ebfea8-4868-11e6-9d93-11dc885c29d3.png)

**Comment by rovolution** [comment]
alright so i am going to implement a container for all ticks (w/ the class `slider-tick-label-container`)

if we need more from there we can always re-open this issue

**Comment by rovolution** [comment]
will publish to 9.0.0 (this might accidentally break builds for people that may be targeting ticks to be within the `.slider-track` element)
