### ISSUE TITLE
How to know which slider changed?

### ISSUE THREAD

**Issue by houcros** [seiyria/bootstrap-slider#501]
In the documentation I can't find any way of knowing the id of the slider that changed inside of the callback. This is possible in the [jQuery slider plug-in](http://api.jqueryui.com/slider/#event-change), but I would like to use this one. 
If it is possible, where can I find the docs for that?

**Comment by seiyria** [comment]
Supposing that you bind an event to a slider (such as the change one), you should know what slider you bound it to. 

I'd need to see an example here to get why this is needed.

**Comment by seiyria** [comment]
Closing for now because this still appears to be a non-issue.

**Comment by houcros** [comment]
I'm sorry, I had forgotten about this issue because in the end I used another slider.
Anyhow I still think this would be useful. [Here](https://jsfiddle.net/houcros/ccycf7fL/4/) is an example of what I meant.

**Comment by houcros** [comment]
Damn it, I just realized this can be done with the event object, no need for a new functionality in the plug-in. I didn't see it when I started the issue but now it's clear. The [updated example](https://jsfiddle.net/houcros/ccycf7fL/10/) were I solved it, if it is any good to anyone.
