### ISSUE TITLE
Extended 5 Range Slider

### ISSUE THREAD

**Issue by hallard** [seiyria/bootstrap-slider#502]
Hi there,
Thanks for this really excellent bootstrap slider, I like it 

I'm searching for a more advanced range slider and I was wondering if it will be do able with this plugins

Let me explain, based on this slider
![image](https://cloud.githubusercontent.com/assets/2471931/12212414/71007c14-b66a-11e5-8844-5388f046a0af.png)

I would like to have 2 more range (so 2 more "round button") . I need to select OK/Warning/Error values for a sensor. Let's say I have a tempearature sensor and need to have :
- from -20 to - 6 => Error
- from -5 to 5=> Warning
- from 6 to 40 => OK
- from 41 to -60=> Warning
- from 61 to 85=> Error

Do you think it's simple to do this ? I thought about combining 2 sliders but may be will have some pain to have them in 'sync'.

Any ideas are welcome ;-)

Thanks for any help

**Comment by seiyria** [comment]
This isn't really doable and I believe we've suggested that it's out of scope (I can't find the issue in question, it's possible I'm imagining this). The slider above is a range slider, meaning you're technically selecting everything on the yellow track. What you want to do does not actually seem to make sense from a UX perspective. Regardless, I don't see a feature like this making it in upstream.

I personally think this particular control could be represented much better (or differently). You could:

* figure out some CSS magic to drop the colors you want on the slider, and have it be a single (not range) slider
* make it one range slider, and use form validation or some value display to suggest that the value might not be ok (in the case of error/warning).

**Comment by hallard** [comment]
@seiyria 
Yeah, for sure it's not an issue, sorry about this, In fact I didn't find the right way to ask my question.
I wanted something like this with each blue point not able to go over the over of course ;-)
![image](https://cloud.githubusercontent.com/assets/2471931/12212819/dcdd0296-b66e-11e5-8a2f-04dfec476262.png)
anyway thank for your fast anwser
