### ISSUE TITLE
More use of css classes

### ISSUE THREAD

**Issue by Jogai** [seiyria/bootstrap-slider#505]
Instead of setting all sorts of style and css properties it seems more in line with bootstrap to set different classes with different styles. That way you could re-use some bootstrap utility classes too.

**Comment by seiyria** [comment]
We don't actually use bootstrap anymore. The dependency was too big for what little we used. Additionally, we make [pretty big use of CSS](https://github.com/seiyria/bootstrap-slider/blob/master/src/less/rules.less), so I'm confused where this is coming from.
