### ISSUE TITLE
Add CDN links to README.md

### ISSUE THREAD

**Issue by benjamin-rood** [seiyria/bootstrap-slider#507]
Hi, I was going to do a pull request, but I couldn't find where the best place for it would be in the README, so I am just going to raise this as an issue:

**I really think you should post the CDN links for the releases on the README.** 
It's the very first thing people who might want to dabble with `bootstrap-slider` in JSFiddle or Codepen or Codeply would be looking for, not to mention all the developers who might want to include it. Sure, you can google it, but given that there is more than one version of "bootstrap slider" out there, it makes sure that people get the correct resource they are looking for.

Either just add this link: `https://cdnjs.com/libraries/bootstrap-slider` or add all four of the js and css links directly.

P.S. Thanks for making (and sharing) this great tool.

**Comment by seiyria** [comment]
I didn't even know we had CDNJS set up. I'll add this to the readme.
