### ISSUE TITLE
change and slide events are triggered on mouse move for me

### ISSUE THREAD

**Issue by gagariny** [seiyria/bootstrap-slider#510]
change and slide events are triggered on mouse move for me

**Comment by seiyria** [comment]
That is intentional.

**Comment by gagariny** [comment]
I tried to find an event which triggers only when value is changed (only once, but not on mouse move). Is there such event.

I want to make bold the selected lables.

**Comment by capegreg** [comment]
So you're saying that the slideStop event is required to cancel the on change event? Thanks.

$('#myslider').slider().on('change', function(values) {
    console.log(values.value.newValue);
});
$('#myslider').slider().on('slideStop', function(evt){
     console.log(evt.value);
});
