### ISSUE TITLE
clicking on handler or bar doesn't focus anything

### ISSUE THREAD

**Issue by phazei** [seiyria/bootstrap-slider#512]
The only way to focus is to tab to it with the keyboard, can't click it then use the arrow keys.

**Comment by seiyria** [comment]
Please provide a jsfiddle (or an example where this is present).

**Comment by phazei** [comment]
http://seiyria.com/bootstrap-slider/

every one of those

**Comment by rovolution** [comment]
@phazei yea that is not the default behavior. feel free to submit a pull request that exposes an option that allows for 'focus on knob click". Remember to add tests. thanks!

**Comment by phazei** [comment]
Oh, somehow there is one that I just entirely missed, "focus":"true"
