### ISSUE TITLE
_setText method: problem with innerText in Firefox

### ISSUE THREAD

**Issue by gio-js** [seiyria/bootstrap-slider#518]
Hi,
below I'm describing a strange issue using this library in Firefox.

My Firefox version: 44.0

Here is my code:
```
$item.bootstrapSlider({
            ticks: hours,
            ticks_labels: ["00:00", "05:00","10:00","15:00","20:00","24:00"],
            min: 0,
            max: 24,
            step: 1
        })
```

Here the error I have in the console:
`TypeError: setting a property that has only a getter`

The stack:
`_setText()                        bootstrap-slider.js:1464`
`_layout()                         bootstrap-slider.js:1087`
`setValue()                        bootstrap-slider.js:775`
`createNewSlider()                 bootstrap-slider.js:636`
`Slider()                          bootstrap-slider.js:298`
`bridge/$.fn[namespace]/objects<() bootstrap-slider.js:151`
`jQuery.prototype.map/<()          jquery-2.1.4.js:144`
`.map()                            jquery-2.1.4.js:467`
`jQuery.prototype.map()            jquery-2.1.4.js:143`
`bridge/$.fn[namespace]()          bootstrap-slider.js:143`

Here the mdn doc about innerText:
[https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText)

It seems innerText has been found, so it's not undefined, but it can not be assigned because it is a getter.
Thanks in advance for your support.

**Comment by seiyria** [comment]
Thanks, never would have noticed. After reading about the differences between `innerText` and `textContent` I think we can safely, essentially, ctrl-f-r and replace the former with the latter.

That said, feel free to submit a PR also! It's much easier for us to help with that.
