### ISSUE TITLE
[Bug] Position Tooltip Before Show

### ISSUE THREAD

**Issue by Undistraction** [seiyria/bootstrap-slider#52]
To Replicate:

Setup: Give slider a percentage width.
1. Resize browser window, or slider container so that its width changes.
2. Drag Slider Handle.

Result: Tooltip appears at old location for a moment before being correctly positioned/centred based on new width.

Fix: Calculate tooltip position before showing it.

**Comment by sergionegri** [comment]
Are there any news on this bug?

**Comment by seiyria** [comment]
No. This is not our active project; we merge pull requests that are ready and maintain the project but we're both pretty busy people.
