### ISSUE TITLE
Slider tooltip display issue

### ISSUE THREAD

**Issue by pedroadame** [seiyria/bootstrap-slider#523]
As seen in #303 
This happens to me after creating the slider on a bootbox.js modal.
Codepen: http://codepen.io/anon/pen/YwJNZP
My javascript and css are at the bottom. Needed to include all bootbox and bootstrap-slider code.
Run codepen and click on the button. See how the tooltip appears to the right of the handler.

**Comment by Kinnonii** [comment]
up

**Comment by jpontet** [comment]
Same for me as well

**Comment by berarma** [comment]
This is a well know problem. You must instantiate the slider after it becomes visible. In case you can't do it, there's a function to fix the tooltip positions, call _relayout_ when the slider becomes visible. In your example you're creating the slider and calling _relayout_ before the dialog is visible.

Try changing the call to _relayout_ with this code:
```javascript
  setTimeout(function() {
    slider.slider("relayout");
  }, 500);
```

The 500ms wait will relayout the slider when already visible. It would be better to use some event callback that triggers when the widget becomes visible. I don't know if or how bootbox.js would handle this. You could also use the _transitionend_ DOM event.

**Comment by lessaworld** [comment]
This seems to be still an issue with Bootstrap 4. Here's the solution that worked for me. 

<pre>
$('#myModal').on('shown.bs.modal', function (event) {
  setTimeout(function() {
      $('input[name=sliderName]').slider('relayout');
  }, 0);
});
</pre>

where myModal and sliderName can be seen in the following example snippet.
<pre>
&lt;!-- The Modal -->
&lt;div class="modal fade" id="myModal">
  &lt;div class="modal-dialog">
    &lt;div class="modal-content">
      &lt;!-- Modal Header -->
      &lt;div class="modal-header">
        &lt;h4 class="modal-title">Modal Heading&lt;/h4>
        &lt;button type="button" class="close" data-dismiss="modal">&times;&lt;/button>
      &lt;/div>
      &lt;div class="modal-body">
            &lt;div class="form-group">          
              &lt;span>Min Value&lt;/span>
		&lt;input
              	type="text"
              	name="sliderName"
              	data-provide="slider"
...
</pre>
