### ISSUE TITLE
Removing compass dependency

### ISSUE THREAD

**Issue by blackfyre** [seiyria/bootstrap-slider#529]
Not everyone who uses `SASS`/`SCSS` uses ruby compass to transpile these to CSS.
`libSASS` is almost a drop-in replacement if you don't use image sprites or some of compass's special CSS3 libraries..

**Comment by seiyria** [comment]
We don't even have a dependency on ruby-sass, sass, compass, or anything as far as I can tell, so I'm not sure what you're talking about.

**Comment by blackfyre** [comment]
Well, it's there: https://github.com/seiyria/bootstrap-slider/blob/master/src/sass/slider.scss#L11 :smile:

**Comment by seiyria** [comment]
Ah, I see. I figured it would have been somewhere in our package.json. 

Anyway, we'll take a PR on this but it's definitely not a priority.

**Comment by phazei** [comment]
@blackfyre 
I'm using their SASS files and don't use compass either.
The npm package:
```
"compass-mixins": "^0.12.7",
```
It's basically mixins to replace compass, it seems to take care of actually using the real compass and works with gulp-sass with:
```
.pipe(sass({ sourceComments:true, includePaths: [__dirname + '/node_modules/compass-mixins/lib'] }))
```
