### ISSUE TITLE
List of un-evenly distributed ticks

### ISSUE THREAD

**Issue by pinkynrg** [seiyria/bootstrap-slider#534]
I have a setup where the valid and only values are 2,3,4,6,7. I would like them to be equidistant so this is my actual setup:

`var slider = $("#status_id").slider({ id: 'status_id', ticks: [2,3,4,6,7], value: 2, ticks_labels: item['labels'], tooltip: 'hide', ticks_positions: [0,25,50,75,100] });`

How can I have a setup where value 5 is disabled? Sorry if I'm asking an already solved issue

**Comment by seiyria** [comment]
this feature does not currently exist.

**Comment by pinkynrg** [comment]
I may try implement it myself. One only question since you are the one who wrote this: do you think that a  mapper function would be ok? something like, if a pass an object instead of an array for the ticks, such as {'1':2,'2':3,'3':4,'4':6,'5':7} then a mapping feature will use the key as a tick value for the slider and pass the associated value to the hidden textbox. 

It may be a stupid idea for the current setup. Let me know.

**Comment by seiyria** [comment]
I didn't actually write this. The current version was by Stefan Petre, and @rovolution wrote the current (backwards-compatible with the version I maintained) version.

That said, if that's what you want - take a look at the `formatter` function for display, and use the `slide` callback to set the value wherever necessary.

**Comment by pinkynrg** [comment]
I did try using it like so:
`formatter: function(value) {
          switch (value) {
               case` 2: value = 1; break;
               case 3: value = 2; break;
               case 4: value = 3; break;
               case 6: value = 4; break;
               case 7: value = 5; break;
          }
     return value;
}`

but thus still seems to give me the possibility to set the tick in between (real) value 4 and (real) value 6.

**Comment by seiyria** [comment]
Set the ticks to 1,2,3,4,5 (min = 1, max = 5). Don't try to stop the slider from selecting values inbetween, just change how it displays using the formatter.

**Comment by pinkynrg** [comment]
os so far so good, but now the real value passed to the textbox is the not real one, is the one I used to setup the slider. How can I have the textbox filled with the real values?

**Comment by seiyria** [comment]
Add a handler for the `change` event that sets it to the real value based on the fake value.
