### ISSUE TITLE
how to set floating value ?

### ISSUE THREAD

**Issue by jothikannan** [seiyria/bootstrap-slider#536]
How to Use setValue with floating like 0.01 ,0.02 and so on when i setting value like below it thoughs a error

```
var Prog_slider = $("#seek-bar").slider();
 Prog_slider.slider('setValue', '0.01');

```
`Uncaught Error: Invalid input value '0:01' passed in`

**Comment by seiyria** [comment]
a) please provide a jsfiddle
b) you probably need to pass it in as not a string
c) you probably need to set some options like step, precision, etc.

**Comment by lauraannwilliams** [comment]
Your example error says ''0:01'' not "0.01" - maybe check for a typo and make sure you are using a . and not a : ?

**Comment by seiyria** [comment]
Closing due to lack of example.
