### ISSUE TITLE
tooltip_position not working

### ISSUE THREAD

**Issue by jibusayone** [seiyria/bootstrap-slider#539]
To make the tooltip appear at bottom, i gave:
`$('#job-salary').slider({
        formatter: function(value) {
            return 'Current value: ' + value;
        },
        tooltip: 'always',
        tooltip_position: "bottom"
    });`

I'm using version 3.1.0. Was tooltip_position param introduced in a later version?

**Comment by seiyria** [comment]
Probably. Best way to figure it out is to load up a jsfiddle (as our issue template suggests).

**Comment by seiyria** [comment]
Closing due to lack of example.
