### ISSUE TITLE
Plugin doesnot works with React.js

### ISSUE THREAD

**Issue by nishvs** [seiyria/bootstrap-slider#540]
I tried to use this control in my React page but was unable to do it. Basically in my page initially the slider loads but the min and max value for the slider is not set which will be set when the Ajax call retrieves the min max value. So for that i have used the following way i am passing the values in props to the component which has the slider control. 

`                    var BudgetPanel = React.createClass({

                      getInitialState: function() {

                        return {

                          slider:{}

                        };

                      },

                      render: function() {

                        var component = this

                        if(this.props.budget){

                          var minval = this.props.budget.min

                          var maxval = this.props.budget.max

                        }

                        return (

                        <div className="bud_get">

                          <a href="#"><i className="fa fa-bookmark-o"></i>Budget</a>
                            Filter by price interval: <b>€ 10</b>
                            <input id="ex2" ref="budgetinput" type="text" className="span2" value="" data-slider-step="5" data-slider-value="[250,450]"/>
                            <b>€ 1000</b>
                        </div>
                        );
                      },
                      onChange: function() {
                        // var minBudget = ReactDOM.findDOMNode(this.refs.minBudget).value;

                        // var maxBudget = ReactDOM.findDOMNode(this.refs.maxBudget).value;
                        // this.props.handleFilterInput("budget",minBudget,maxBudget);
                      },
                      componentDidMount : function(){
                        var newslider = new Slider(ReactDOM.findDOMNode(this.refs.budgetinput), {});
                        this.setState({
                          slider:newslider
                        })
                      },
                      componentDidUpdate : function(){
                        var currentslider = this.state.slider
                        var value = []
                        if(this.props.budget){
                          console.log("updating");
                          value.push(this.props.budget.min)
                          value.push(this.props.budget.max)
                          currentslider.setAttribute("data-slider-min",this.props.budget.min)
                          currentslider.setAttribute("data-slider-max",this.props.budget.max)
                          currentslider.refresh()
                          // this.setState({
                          //   slider:currentslider
                          // })
                        }
                      }
                    })
`

But i am unable to get it work.

**Comment by seiyria** [comment]
As stated in the issue template, please provide a jsfiddle, not a chunk of code.

**Comment by seiyria** [comment]
It might be worth checking out [this project](https://github.com/brownieboy/react.bootstrap.slidertest). Integration with other libraries is not on us, in general.
