### ISSUE TITLE
Add buttons

### ISSUE THREAD

**Issue by davidmegginson** [seiyria/bootstrap-slider#541]
While it's not hard to do manually, it would be nice to have an option to display buttons to the left and right of the slider, e.g.

```
[<<] [<] |------------------------------------| [>] [>>]
```

The outside buttons would jump to the start and the end of the range; the inside buttons would move backwards or forwards by a single step (useful for large ranges, e.g. in the thousands, where it's hard to be that precise with a tap or mouse slide).

**Comment by seiyria** [comment]
I think this is feature creep, and something that should be done per person; there's no way we can catch every useful use-case for them and it will end up requiring lots of support, I'm sure.

**Comment by davidmegginson** [comment]
It's a judgement call, of course, but I think it has a few points in its favour:

* It's an extremely-common use case (it's not a question of capturing every possible outlier).
* The behaviour is well-defined and well-understood (there aren't multiple competing popular ways of doing it).
* We already have an attribute for defining the step, so there's no ambiguity about what step back/forward should mean.
* We already have min/max attributes, so there's no ambiguity about what jump to start/end should mean.

I can think of two legitimate arguments against (avoiding the "all-or-nothing" fallacy):

* The buttons probably don't make sense with a range (vs a single slider).
* While buttons are common on horizontal sliders, they're rare on vertical ones.

So if most people are using the default single, horizontal slider, I think the buttons would be a big win for reusability and code reduction (just like the core slider widget itself); if most people are using the vertical and/or range variants, then less so.

**Comment by davidmegginson** [comment]
BTW, either way, thanks for a great widget.

**Comment by rovolution** [comment]
This sounds like something that should be done in an application, not this module

**Comment by seiyria** [comment]
I agree with @rovolution and disagree that this is a common use-case. I don't think I've ever seen this feature in any other slider library and I've never seen it requested in the ~3 years I've been helping maintain this widget. I think this is best implemented in the application, to augment the slider.

The big, unstated problem is positioning, styling, etc. If we were to provide buttons, we would either have to provide default styling, tie into bootstrap, make sure the positioning is correct (aligning 5 items horizontally is tough to keep consistent), allow for customizable text... this is a deep rabbit hole, and it's not one we should go down ourselves. Sorry!
