### ISSUE TITLE
How to set precsion for range slider

### ISSUE THREAD

**Issue by hoangphucvu** [seiyria/bootstrap-slider#549]
I have value between 100000,10000000 how can i set those 2 value into this 100.000 and 10.000.000.Some thing like number format do in php.
Here is my code
```
$("#allowance_filter").slider({
    min:100000,
    max:10000000,
    value:[100000,10000000],
    precision:0.000,
    step:100000,
    focus:true
});
```
Best regard.

**Comment by seiyria** [comment]
Use the formatter function.
