### ISSUE TITLE
Click on slider does not trigger slide event

### ISSUE THREAD

**Issue by andersHj** [seiyria/bootstrap-slider#555]
The event is only triggered when dragging.

Screenrecord from example page (http://seiyria.com/bootstrap-slider/)

![slider](https://cloud.githubusercontent.com/assets/2843210/14317505/db1fbc8e-fc08-11e5-9418-c8fd287155d4.gif)

**Comment by kcoderhere** [comment]
This may be intentional usage of the "slide" event, but the example text should be updated to call that out or be re-written to use the "change" event instead.

**Comment by seiyria** [comment]
This is 100% intentional and is written out [very clearly in our README](https://github.com/seiyria/bootstrap-slider#events).

**Comment by kcoderhere** [comment]
The example says "used" not "dragged."  If you change the text on the example page to clarify this behavior, people will stop opening this up as a bug every month. ;)
