### ISSUE TITLE
Display lables above horizontal slider

### ISSUE THREAD

**Issue by tonycobb** [seiyria/bootstrap-slider#556]
Issues
=============
How is this done?

**Comment by seiyria** [comment]
With a complete disregard to our template, demo, searching our issue tracker, or seemingly reading our documentation, I'm closing this.

**Comment by tonycobb** [comment]
This is not in the documentation.  Anywhere. You closed prematurely.

**Comment by tonycobb** [comment]
I've looked at all of the demos.  Feel free to prove me wrong.
