### ISSUE TITLE
Cannot load slider

### ISSUE THREAD

**Issue by Ekaterina9292** [seiyria/bootstrap-slider#563]
Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [ ] Instructions to replicate the bug in the Fiddle

**Comment by Ekaterina9292** [comment]
how to open https://cdn.rawgit.com/seiyria/bootstrap-slider/master/css/bootstrap-slider.css . Cannot get code and load slider :?

**Comment by seiyria** [comment]
1) Please do not send me 4 emails all at once, that's really annoying.
2) please actually fill out the issue template, not just leave it there
3) use bower or npm, not rawgit. rawgit caches aggressively so your code will be out of date.

**Comment by Ekaterina9292** [comment]
Oh my! I am so sorry, I did not know that I wad sending you emails!!

Please accept my apology!
Thank you!

Have a great day!
