### ISSUE TITLE
Examples page missing data-provide

### ISSUE THREAD

**Issue by kaiazeekee** [seiyria/bootstrap-slider#564]
On the HTML sections on the examples page, the examples do not have the attribute, data-provide="slider". It took me a longer than I wan to admit to realize that and to set up my slider bar.

**Comment by seiyria** [comment]
We'd be happy to have a PR that adds a data-provide example!

**Comment by rovolution** [comment]
Thanks for this valuable feedback @kaiazeekee!

Added it as `Ex. 21`: http://seiyria.github.io/bootstrap-slider/
