### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'function(e){this._addClass(e,"top"),

### ISSUE THREAD

**Issue by javadev** [seiyria/bootstrap-slider#565]
I found an error while setup tooltip relayout:

Error message:

TypeError: 'undefined' is not a function (evaluating 'function(e){this._addClass(e,"top"),e.style.top=-this.tooltip.outerHeight-14+"px"}.bind(this)')

Javascript code:

      $('.nav-tabs a').on('shown.bs.tab', function() {
        view.ui.slider.slider('relayout');
      });

**Comment by seiyria** [comment]
As per our contribution guidelines, a snippet of code is not enough, we also need a demo to reproduce this.

**Comment by javadev** [comment]
We found that it happened in BDD test, which uses phantomjs browser. Issue may be closed.
