### ISSUE TITLE
Q: How to adjust slider width to fill parent 100%?

### ISSUE THREAD

**Issue by attentiondmi** [seiyria/bootstrap-slider#566]
Using CSS to adjust the slider's width is possible, but it results in the labels underneath keeping their old positions, and thus looking incorrect.

What's the best way to get the slider to expand its width to fit it's parent width 100%?

Thanks in advance!

**Comment by AndreiRegiani** [comment]
Simply add this custom CSS, this class is already set to the input field, just override the value with !important

```
.slider {
    width: 100% !important;
}
```

or change this value from the library CSS itself

**Comment by attentiondmi** [comment]
Thanks Andrei! I have tried that, but there's a problem: If I increase the
.slider width, then the .slider-tick-label width expands far outside its
container.

**Comment by akitaylor** [comment]
The suggested solution works for me like a charm inside a bootstrap column, including the tick labels. The slider automatically relayouts itself when the width of the parent element changes.

**Comment by seiyria** [comment]
The solution we suggest is the CSS one shown above. If tick labels are displacing, that is a bug and should be reported in a separate issue.
