### ISSUE TITLE
 Function to reset the slider

### ISSUE THREAD

**Issue by stwe** [seiyria/bootstrap-slider#567]
I'm the maintainer of the [SgDatatablesBundle](
https://github.com/stwe/DatatablesBundle) and I use your great Slider as a filter for a table column. See as in action:

![heat](https://cloud.githubusercontent.com/assets/2964748/14926446/8fdda7b2-0e4c-11e6-9c75-bd1a96a31cfb.JPG)

What I need is a function to reset the slider, so that I have an empty value in the input field.

**Comment by seiyria** [comment]
please provide a demo so we can see specifically what you're trying to achieve.

it may also benefit you to look through our [api](https://github.com/seiyria/bootstrap-slider#functions). perhaps you can store a default value and reset to it where appropriate.

**Comment by elchesco** [comment]
erm maybe set it back to whatever initially you had, if using data attrs something like this works:

`		priceSlider.slider('setValue', jQuery('#mysliderId').data('slider-value'));`

**Comment by stwe** [comment]
@seiyria : The mission is simply formulated. I need to send an empty string to the server. Suppose I have a Slider with min = 0 and max = 12. Then I can send by clicking in the slider values from 1 to 12 to the server; however, no empty string. I can only add a button to disable the slider or activate. It would be great if I could determine a value representing an empty string. For example, min = 1, max = 12, and cancel = -1 (which means empty string). Otherwise, I have to use an additional button, which would be not so good. The daterangepicker for example clears the input field by cancel click.

**Comment by seiyria** [comment]
No, we're not adding any "cancel" or "empty" values. This is not how a slider should behave. See #403. This is also a duplicate or some other issue that I can't find.

**Comment by stwe** [comment]
You have a formatter for your tooltips. Why not for your min-max values? 
That was my idea above.

**Comment by seiyria** [comment]
That's feature creep, and something that, if desired, you can easily handle on your end.
