### ISSUE TITLE
Color parts of the slider?

### ISSUE THREAD

**Issue by RobertSmart** [seiyria/bootstrap-slider#569]
Hi,

I'm using the slider to represent a timeline and it is scrolled to move forward and back in the video time line. It works great.

A small feature I would like to implement though is to be able to display a different colored sections on the sldier to represent things like missing data or activity or something. 

Would this be easy to implement from a range of to-from values?

Any hints on where to start?

Thanks

**Comment by seiyria** [comment]
It's not possible to color more than before the marker, after the marker, and the marker itself. 

I don't think it would be trivial to implement because right now the slider track is just a track, there is no differentatiation between individual values on it. Given that the slider can go between many values (1-100000 just for a contrived example), we would have to create 100k DOM elements, and that would be gross.

I'd need to see a better example of what you're asking for, because the above is what I'm seeing when I read your questions.

**Comment by RobertSmart** [comment]
I don't think it would require that many elements. 

As an example i might have a timebar that represents time 0 - 100. There is are sections of data missing between values 20 to 35, and 70 to 92. So i would like the section of bar that covers these ranges to be coloured red or some such colour.

Does that make sense? Let me know if that is not clear.

Thanks

**Comment by seiyria** [comment]
Sure, it makes sense, but I don't know how you plan to know that a particular part of the track is 20, 35, etc. I think you'd be best off creating your own absolutely positioned element on top of it, covering these particular ranges. That said, until I've seen a concrete example I can't make a judgment either way, but for now I'm closing this since it seems like it's not something we should do. For possibly tangentially-related discussion, see #271.

**Comment by RobertSmart** [comment]
Those values relate to the slider values, so i'm assuming we know where each value sits along the bar?

**Comment by seiyria** [comment]
No, we don't. We can guess, but we don't know. Suppose you have an arcane combination of a slider in range 1-100000 (displayed logarithmically) and a step size of 10.4. You want to put a red border above all values from 16000.2 to 18002.4. To do so, you need to figure out where the red border starts, where it ends, and then put one on top of it. It's not impossible to do this, but it's a lot of math and computations that we would have to do. Sure, there is a simple case (ie, 1-100, step size 1), but we have to consider the most complex cases when evaluating features like this.

That said, I can't think of any reason why this should be included in the base slider. There are too many things to think about here, for example, if you want one red blob on top of the slider, what's stopping you from wanting N? What options should they support? How should they be styled? What do you even call them?

This really is something that's much more application-specific as this is the first time I've heard of something like this being used on a slider.

**Comment by RobertSmart** [comment]
I wasn't really implying that it be added as a feature as you are quite right, it is application specific.
For instance i know i will always use a linear scale with whole numbers for start, finish and values. But this would not be the case for all users.

 I was just looking for some pointers as to where i should start to look in the src code to implement a feature like this on top of the base slider.

**Comment by seiyria** [comment]
Sorry, I'm used to people wanting the feature to be added to the base slider.

Anyway, I'm not even sure you'd need anything in the base slider. I think the best idea is to just add a div with your desired color/width over top of the slider track, but below the slider handle.

**Comment by RobertSmart** [comment]
Yeah, i think i'll give that a go. 

You want me to let you know how it goes?

**Comment by seiyria** [comment]
Sure! we like success stories, especially with pictures.

**Comment by RobertSmart** [comment]
This was quite easy in the end.

I created a new css class:

.slider-gap{
    position: absolute;
    height:100%;
    top:0;
    bottom:0; 
    background:red;
}

then in my js where I pass the object that contains my slider information, for each gap I do a bit of math to calculate the pecentage left and width then add this div via jquery.

$(".slider-track-high").after("<div class='slider-gap' style='left: " + gapLeftPc + "%; width:" + gapwidthPc + "%; background:red'></div>")

The result is just what I need, and could also be used for something like highlighing a dangerous section of the slider range (like high volume, or high sampleing rate or something)

Here is pic as requested.

![image](https://cloud.githubusercontent.com/assets/12431905/15075512/ae08f700-139c-11e6-90e6-42a8e038ccf4.png)

**Comment by seiyria** [comment]
Nice job! Looks pretty good, too.
