### ISSUE TITLE
Slider Ticks/Labels are not wrapping and no tooltips available for Ticks

### ISSUE THREAD

**Issue by rajendra15** [seiyria/bootstrap-slider#570]
Issues
=============
Actually there is no properties to define horizonal slider width and vertical slider height.

I did a tweak to adjust height and width. 

But there is no such tool tips for ticks and the ticks text is not wrapping up.

Is there any config available or can anyone help with any tweak

![image](https://cloud.githubusercontent.com/assets/3041896/15073734/e0dea10e-13b8-11e6-9a1c-093cc6d84b82.png)

Thanks in advance,

**Comment by seiyria** [comment]
Use CSS. If you have any further problems you'll need to post a demo.

**Comment by rajendra15** [comment]
We can use CSS for text wrap but even thought the text is too long, will display few words and ends with ..(dots). So it requires the tool tip on the tick label. so then how can we display it

**Comment by seiyria** [comment]
If your text is too long, you'll have to make the slider vertical so the text can be much longer. You can either do that, shorten your text, or write some custom code to iterate over all of the slider text labels and add a tooltip with the proper text.
