### ISSUE TITLE
Issue with bootstrap Slider to  disabled

### ISSUE THREAD

**Issue by kavita2907** [seiyria/bootstrap-slider#571]
min =0 and max=20
Is it possible to disabled or stop drag slider less than particular value(e.g 10) and enable greater than the same value(e.g 10) between the min and max range of slider .

**Comment by seiyria** [comment]
I have no idea what you're asking about. You're going to have to clarify a bit before anyone can point you in the right direction.

**Comment by kavita2907** [comment]
I have slider with values ranging from 1 to 10. I do not want user to slide/select value below 5. Is there any way to set such bottom limit so that the slider cannot go below that value.

**Comment by seiyria** [comment]
Yes, set the min to 5. No, you can't disable just a part of the slider. If you really want to do that, intercept the `change` event and call `setValue` on your minimum.
