### ISSUE TITLE
Improving touch based user expecience

### ISSUE THREAD

**Issue by akitaylor** [seiyria/bootstrap-slider#572]
I experienced that if you try to use the slider in a mobile browser then the touch event often scrolls the whole page instead of moving the slider itself. It works almost fine if the width of the page fits the mobile screen (apart from the fact that the vertical scrolling still happens which also decreases usability slightly).

Is there a way to avoid scrolling of the page when touching the slider? (Sadly I could not find one)

Another aspect of improving the usability in mobile environment would be to make handles bigger. Is it possible now?

Thanks in advance!

**Comment by seiyria** [comment]
I'm not sure about your first question, but the second one is simply a CSS thing, which you can easily change. I imagine if you couldn't figure out a way to avoid scrolling, we can't either. Two ideas offhand:

* check the scroll of the page before sliding, then revert it after.
* try using e.preventDefault in slide? I'm not sure if this will do it.

Good luck!
