### ISSUE TITLE
Span not updated when clicking on the slider

### ISSUE THREAD

**Issue by Nicryc** [seiyria/bootstrap-slider#573]
Hi,
I don't understand why the value of the span isn't updated when you just click on the slider, when you slide it works fine but when you just click, it doesn't.

https://jsfiddle.net/qrs0ym7q

Thank you.

**Comment by seiyria** [comment]
Use the [`change` event](https://github.com/seiyria/bootstrap-slider#events).

**Comment by Nicryc** [comment]
Why console.log(changeEvt.newValue); return undefined ?
`$("#sphereg").on("change", function(changeEvt) {
    console.log(changeEvt.newValue);
  });`
