### ISSUE TITLE
bootstrap-slider with Laravel DataTables

### ISSUE THREAD

**Issue by SarahCSharp** [seiyria/bootstrap-slider#577]
I'm using bootstrap-slider to redraw Laravel DataTables on slide event but it doesn't work unless I refresh the page
```

$(function() {
		//creates bootstrap slider
        $( "#op-slider" ).slider({
        	range: true,
        	min: rangeMinOP,
        	max: rangeMaxOP,
        	value: [ rangeMinOP, rangeMaxOP ],
        }).on('slide', function(ev){
        	var min = ev.value[0];
        	var max = ev.value[1];
        	$("#minOP").val(min + "%" );
        	$("#maxOP").val(max + "%" );

        	table.draw();
        })
});
```

but it works perfectly fine with jQuery UI Slider with the same exact code, am I supposed to use a different slide event to redraw DataTables without needing to refresh?

**Comment by seiyria** [comment]
I'm afraid I'm not sure what the problem is. I'd need to see a demo (which is why we ask for one). You can try using the `change` event instead of slide, but I don't know if that will solve your problem.

**Comment by SarahCSharp** [comment]
My bad, I found an error in my code with global variables and now its working perfectly but I have another problem.

the 'getValue' function returns both minimum and maximum values of the slider is there a way I could get it to return only the first value ( minimum ) of the slider by using the array placement of 0 or 1?

something like this : 
```
//get first value ( minimum ) of slider and places it within textbox (#minOP)
$( "#minOP" ).val( $( "#op-slider" ).slider( 'getValue', 0 ) + "%" );
//get second value ( maximum ) of slider and places it within textbox (#maxOP)
$( "#maxOP" ).val( $( "#op-slider" ).slider( 'getValue', 1 ) + "%" );
```

**Comment by seiyria** [comment]
No, you're going to have to pull the data out. `.slider('getValue')[0]`.

Glad to hear your issue was solved.
