### ISSUE TITLE
Q: How do I listen to the events without JQuery ?

### ISSUE THREAD

**Issue by dnouls** [seiyria/bootstrap-slider#581]
I'm tyring to use the slider in a GWT application. The wiki explains how to install the slider without using JQuery, but it does not explain how to register for the supported events.

**Comment by dnouls** [comment]
I'm tyring to use the slider in a GWT application. The wiki explains how to install the slider without using JQuery, but it does not explain how to register for the supported events.

**Comment by seiyria** [comment]
You might want to check [the examples page](http://seiyria.com/bootstrap-slider/). For example:

```
var slider = new Slider("#ex6");
slider.on("slide", function(slideEvt) {
	$("#ex6SliderVal").text(slideEvt.value);
});)
```
