### ISSUE TITLE
text box showing instead of slider

### ISSUE THREAD

**Issue by momame** [seiyria/bootstrap-slider#582]
I want to implement example 6. I already link boostrap slider.JS and bootstrap slider.CSS in my HTML.
In addition I put this code at the end of my body
$("#ex6").slider();
$("#ex6").on("slide", function(slideEvt) {
	$("#ex6SliderVal").text(slideEvt.value);
});

but after pasting these HTML codes:

<input id="ex6" type="text" data-slider-min="-5" data-slider-max="20" data-slider-step="1" data-slider-value="3"/&t
<span id="ex6CurrentSliderValLabel">Current Slider Value: <span id="ex6SliderVal">3</span></span>

I just see a textbox in my web page. what is the reason. what should I do?
I really need it.
Regards
Mo

**Comment by seiyria** [comment]
Please provide a jsfiddle so we can see what you're doing.

**Comment by momame** [comment]
Thanks for your quick reply!
please take a look at it
https://jsfiddle.net/Mehrpak/5de3owrc/1/#&togetherjs=LRIxj6DKQj

**Comment by momame** [comment]
Did you get my fiddle?

**Comment by seiyria** [comment]
There were a few problems with your fiddle. Here is a working one: https://jsfiddle.net/5de3owrc/2/

First off, you have to include the JS/CSS for bootstrap-slider or else nothing will (predictably) happen.

Next, there was an error in the HTML:

![](https://dl.dropboxusercontent.com/u/28522694/ShareX/2016/06/chrome_2016-06-01_08-06-05.png)

`/&t` needs to be changed to `/>`
