### ISSUE TITLE
Slider ticks move after toggle got triggered

### ISSUE THREAD

**Issue by makxx91** [seiyria/bootstrap-slider#583]
Found a problem, when using toggle. I want to disable slider, when user picks a ticks. Call ajax request, then load data, and enable sldier back. Problem is that, when I'm enabling it back, slider keeps switching, like folows mouse movement. You can the problem here.
https://jsfiddle.net/ey56Lb1t/
I created a timeout function, which simply waits a second, and then enables slider back. Try to move your mouse over the slider, it will switch automatically, wich is not nice, because user will get different data. Is there a way to disable this mouse movement, to prevent auto switching?

**Comment by makxx91** [comment]
For now found a solution by using `slideStop`.

**Comment by seiyria** [comment]
This sounds like a problem with bootstrap-slider, not the angular wrapper.
