### ISSUE TITLE
Make it possible to remove slider knop

### ISSUE THREAD

**Issue by robsch** [seiyria/bootstrap-slider#585]
I would appreciate if a slider knop could be removed. I have situations where no value should be set and the slider shouldn't show any value. I could image that `$slider.slider('setValue', null)` could be used to achieve this easily. Currently, I can just disable the slider and set the value to 0. But I would prefer if I can set it to no value.

Is this possible in another way already?

**Comment by seiyria** [comment]
We talked about this a little in #346 and I believe another issue (can't find it atm) and the conclusion was that we will not do this because the blank bar is not helpful.

**Comment by robsch** [comment]
Thank you so far. However, it's not exactly the same because I didn't think that the control would be activated in a scenario. It's just disabled and will remain disabled. It could be activated only with JS, not by the user.

My example: I show a picture and have a zoom slider. If the picture is not available the zoom slider should be still visible but disabled. I would prefer that the slider then doesn't show any value, instead of 0 or 100% or 0,75 or whatever.

Couldn't you just implement this? Nobody would be forced to use `null` as value. It's just an option for a special situation. And it's another feature.

**Comment by seiyria** [comment]
This is feature creep IMO and I still hold that it's bad UX to allow this at all. You'll have to implement it in your own fork if you want it.

**Comment by robsch** [comment]
Ok, thank you.
