### ISSUE TITLE
Float step like 0.01 not supported

### ISSUE THREAD

**Issue by luciemannechez** [seiyria/bootstrap-slider#586]
If you set a step at 0.01, it's not working, the step stays at 1.

`<input value="1.90" id="taux" value="1.90" 
      data-provide="slider"
      data-slider-min="0"
      data-slider-max="10"
      data-slider-step="0.01"
      data-slider-tooltip="show"
      data-slider-value="1.90"
      data-slider-precision="2"
      />`

**Comment by seiyria** [comment]
please provide a jsfiddle

**Comment by Nil-Zil** [comment]
@luciemannechez You need to use `data-slider-` API, like the last example on [this](http://seiyria.com/bootstrap-slider/) page:
```html
<input id="ex23" type="text" data-slider-ticks="[0, 1, 2, 3, 4]" data-slider-step="0.01" data-slider-ticks-snap-bounds="200" data-slider-ticks-tooltip="true" ticks_positions="[0, 30, 60, 70, 90, 100]" />
```

**Comment by jespirit** [comment]
0.01 step is supported. See: https://jsfiddle.net/nqfvya47/1/
