### ISSUE TITLE
TypeError: Cannot read property 'slider' of undefined

### ISSUE THREAD

**Issue by bhoomit** [seiyria/bootstrap-slider#587]
/dist/bootstrap-slider.js
Line: 1604

$.fn is undefined.

**Comment by seiyria** [comment]
Please provide a jsfiddle.

**Comment by gutosanches** [comment]
I receive the same error from the [line 1870](https://github.com/seiyria/bootstrap-slider/blob/master/dist/bootstrap-slider.js#L1870).

Using [react-bootstrap-slider](https://github.com/brownieboy/react-bootstrap-slider) with React and server-side rendering.

**Comment by rovolution** [comment]
@gutosanches We would really appreciate a PR to fix this bug!

**Comment by rovolution** [comment]
fix should be available in v9.7.1

**Comment by josandi** [comment]
i like how this code looks like because its simple but,  first I fixed the "conflict" of its name then now that I  use the NAMESPACE_ALTERNATE the next error is that "app.min.js:28429 TypeError: Cannot read property 'getAttribute' of null" wth..,
