### ISSUE TITLE
Inconsistence between default states and usage

### ISSUE THREAD

**Issue by iBeb** [seiyria/bootstrap-slider#588]
The `inDrag` default/init value is `null`
In `_hideTooltip`, the value is tested with `false`

> this._state.inDrag === false

So before anyone drags one slider (which will set the inDrag to true then to false), the _hideTooltip never hides the tooltips.

**Comment by seiyria** [comment]
If you didn't mean to close this, feel free to reopen it. However, if you do, please provide an example of where this happens (jsfiddle or our own example repository).

**Comment by iBeb** [comment]
I went too fast on posting...
I thought we were using the last version, but no.
I saw the last version has `false` as default/init value.
Oops.
Thanks for the quick reply anyway

**Comment by seiyria** [comment]
No problem, glad to hear it's resolved.
