### ISSUE TITLE
How to Handle a Negative Value in Slider that is (-1,0,1) 

### ISSUE THREAD

**Issue by jamnicky** [seiyria/bootstrap-slider#590]
`var offerSensitivitySlider = new Slider('#offerSensitivitySlider', {
            min: -1,
            max: 1,
            value: offer,
            ticks: [-1, 0, 1],
            ticks_positions: [-1, 0, 1],
            ticks_labels: ['-1%', '0 %', '1'],
            ticks_snap_bounds: 0.5,
            step: 1,
            formatter: function (value) {
                return 'Current value: ' + value;
            }
        });
`
# Issues

**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:
- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [ ] Instructions to replicate the bug in the Fiddle

**Comment by seiyria** [comment]
Please provide a jsfiddle. Although, in this case, if for some reason this doesn't work, I'd recommend creating a slider from 0-2, and using the value function to transform the value.
