### ISSUE TITLE
support tick slider with no default value

### ISSUE THREAD

**Issue by jtauber** [seiyria/bootstrap-slider#591]
I'm using a slider with ticks for discrete values but which also needs to support a value of "unknown".

I think the clearest way to indicate this to users would be to support a slider having NO tick selected but I can't see how to do that.

Is this supported at all?

**Comment by seiyria** [comment]
No. It will [not be supported](https://github.com/seiyria/bootstrap-slider/issues/585).

**Comment by amaatouq** [comment]
It should be supported. For many uses, having a default value would lead to [anchoring bias](https://en.wikipedia.org/wiki/Anchoring) for the user. For behavioral experiments about charitable giving, contributions, estimation tasks, having a default value is a big no-no.

**Comment by seiyria** [comment]
Then this is not the slider control for you.

**Comment by amaatouq** [comment]
Sure it is not... it is just not a bad UX not to have the handle on a default value... if anything, it is the better UX if you want to elicit the true value from the user rather than 'nudging' them towards an engineered one! good luck
