### ISSUE TITLE
How to run a function when slider is created?

### ISSUE THREAD

**Issue by shubham994** [seiyria/bootstrap-slider#592]
I want to run a function in javascript/jquery as soon as the slider is created. But there is no such provision in the docs

**Comment by seiyria** [comment]
There is not, you're right. If you wrap your code in a setTimeout, it will probably work as expected.

**Comment by shubham994** [comment]
It would have been great if you added an onCreate event.But I will use setTimeout for now.
Thanks

**Comment by seiyria** [comment]
It hasn't come up in 2+ years, so it hasn't exactly been a priority - especially with alternatives that work. Glad to hear that it works.
