### ISSUE TITLE
The window has scroll,the slider calculate goes wrong

### ISSUE THREAD

**Issue by HuaGuoFeng** [seiyria/bootstrap-slider#594]
# Issues

I found that when i open f12 for debugger,the slider close to the right of the document,mouse event goes to a wrong position;
then i read node in bootstrap-slider.js,
in line 1392,the _getPercentage function calculate the slide move use mouse pos pageX,pageY,which makes the bug.
pageX:The mouse position relative to the left edge of the document. when i scroll from left to right ,the value changed.
The relative distance used to calculate the slide moves should based on an unchanged value,relative to the screen.

The solution:
**In line 573 and 580,I changed the mousePos from pageX,pageY to clientX,clientY,it works.**

**Comment by seiyria** [comment]
According to our contribution guidelines, please provide a jsfiddle. Additionally, if you have a fix, we welcome PRs.

**Comment by HuaGuoFeng** [comment]
I edit an example to describe the problem:
https://jsfiddle.net/HuaGuoFeng/p0ht2yut/

**Comment by seiyria** [comment]
I don't understand, there isn't even a slider?

**Comment by HuaGuoFeng** [comment]
sorry,scroll the div to the right,you will see a slider

**Comment by seiyria** [comment]
Not seeing anything: https://dl.dropboxusercontent.com/u/28522694/ShareX/2016/07/chrome_2016-07-10_22-53-06.png

**Comment by HuaGuoFeng** [comment]
scroll to the right ,the slider can only slide to 100%.


http://chuantu.biz/t5/16/1468209432x1035372886.png

**Comment by jerrylow** [comment]
I think if you change the Y value to client's Y value it might affect the vertical sliders. Just thinking on the top of my head, haven't tested. But I am able to reproduce the issue you've mentioned in your fiddle.

**Comment by HuaGuoFeng** [comment]
the example:https://jsfiddle.net/p0ht2yut/6/
scroll the div,try to slider to 60% ,it goes to 100%

**Comment by jerrylow** [comment]
Hey @HuaGuoFeng you don't have to convince me, I **was** able to reproduce the issue.

**Comment by x-yuri** [comment]
@seiyria, @jerrylow  I'm trying to create a PR, but `ScrollableBodySpec.js` fails. Can you suggest a way to open the page in the browser?
