### ISSUE TITLE
Disable some value 

### ISSUE THREAD

**Issue by ChhabraAnkur** [seiyria/bootstrap-slider#595]
This is rather a question than issue.
I want some value to be non selectable /disable in slider (I am using ticks slider), so that user can not select those those values.i have tried almost everything but still not able to achieve that . please help me here.
Thanks in advance.

**Comment by seiyria** [comment]
This might be possible, but not with any options. If you don't want a value selectable, you can try:

* storing the last value
* in the slide event, check if the value is disabled
* if so, setValue to the last value

good luck!
