### ISSUE TITLE
The `dist` folder is present with bower but not npm

### ISSUE THREAD

**Issue by simonc** [seiyria/bootstrap-slider#601]
Hi,

I'm trying to use bootstrap-slider with browserify and seem to be stuck when trying to `require("bootstrap-slider");`.

I inspected the `node_modules/bootstrap-slider` folder and it doesn't seem to contain the `dist` folder. This folder is present when installing with bower.

I'm a JS-tooling-noob so I'm not sure it's expected or not. All I know is that I can require other packages but not that one.

Thanks 💕

**Comment by seiyria** [comment]
Generally browserify just builds based on the `main` file specified in the package. Since ours specifies a file in dist it will probably have to be updated.

**Comment by rovolution** [comment]
@seiyria i think i know why this is happening (I added the `/dist` directory to our `.gitignore` to prevent people from comiitting it by accident)

we force add it in the release script (which the only time we want to add it to VC). We just need to add in an `npmignore` file that says do not ignore the dist. I can make the PR

**Comment by rovolution** [comment]
will be fixed by v9.1.1

**Comment by rovolution** [comment]
@simonc check v9.1.1. Thanks for reporting this!!

**Comment by simonc** [comment]
Thanks! :grin:
