### ISSUE TITLE
Need TickLable Value instead of Value

### ISSUE THREAD

**Issue by anandbohra** [seiyria/bootstrap-slider#603]
I liked this slider very much, I interested in using in my code
I created range slider
 data-slider-ticks="[1, 2, 3, 4, 5, 6]"
          data-slider-ticks-labels='["A", "B", "C", "D", "E", "F"]'

it select say 2-4 but is there any way I get B-D instead of 2-4
also I want to change slider using textbox but instead of typing 1 to 6 can I Type B & slider change its position

**Comment by seiyria** [comment]
Use the formatter function. To go in reverse, you're going to have to do a lookup on what number your letter corresponds to, and set the value accordingly.

**Comment by anandbohra** [comment]
formatter function needs value but I need to get text on slide event, pl help or provide link to check further
