### ISSUE TITLE
Question: prevent slider events from propagating

### ISSUE THREAD

**Issue by JVillella** [seiyria/bootstrap-slider#604]
I have two sliders and I want to restrict one's movement based on the other. E.x. they both have range [0, 100], but combined value can only be <= 100. My initial thought was the logic to do this could go into one of the slider's callbacks and I could call `event.preventDefault()`/`event.stopPropagation()` to restrict their movement. This however doesn't work - the events still pass through. Is there anything built-in to achieve this?

**Comment by seiyria** [comment]
What people have done in the past (too lazy to find the issue) is just watch for the value change, and if it exceeds their desired range based on any factors, set it back to it's old value.

**Comment by JVillella** [comment]
Cool, I'll give that a shot. Thank you!
