### ISSUE TITLE
Slider don't work with width:100%

### ISSUE THREAD

**Issue by dit-j** [seiyria/bootstrap-slider#605]
Setting `.slider.slider-horizontal {width:100%}` doesn't work. It is important for responsive design.

**Comment by seiyria** [comment]
As per our contribution guidelines, we need a jsfiddle.

**Comment by jerrylow** [comment]
@dit-j I've never had problems with this on my sites. Here's a sample, working perfectly in responsive:

http://codepen.io/jerrylow/pen/AXaxmq

**Comment by seiyria** [comment]
Going to close this due to contrary evidence. I'm sure if you made a jsfiddle it would be the same result.
