### ISSUE TITLE
Is there anyway to detect mouseup (or when sliding is finished to put it another way?)

### ISSUE THREAD

**Issue by wilsonf1** [seiyria/bootstrap-slider#613]
If I use "onchange" on these sliders, I'm sending far too many ajax calls to my system to update my overall prices. This is because I allow my sliders to go up in 1 increments with the range in the 1000's.

Is there any way to detect when a user STOPS sliding and releases the mouse (or their finger on smart phone / tablet) and only then fire off my ajax? 

This does not work on my sliders:

```
	$(" #contents_form :input").mouseup(function() {
	alert( "Handler for .mouseup() called." );
	});	
```

**Comment by seiyria** [comment]
use the `slideStop` event.

**Comment by wilsonf1** [comment]
Can you give me an example how to use it please? This is my code so far:

```
	$("#contents_extras_possessions_value").slider({
		formatter: function(value) {
			$("#contents_extras_possessions_value").parent().find(".current_slider_value").html(numberWithCommas(value));
			return 'Selected value: \u00A3' + numberWithCommas(value);
		}
	});

```

**Comment by seiyria** [comment]
```
var x = $("#slider").slider();
x.on('slideStop', function(val) {
  console.log(val);
});
```

**Comment by wilsonf1** [comment]
Works a treat. Only thing to note is "val" is an object. So **val.value** actually outputs the value of the slider.

**Comment by iandow** [comment]
@click works for me
