### ISSUE TITLE
Suggestion: slider handle should be centered if no data-slider-value is set.

### ISSUE THREAD

**Issue by ruSauron** [seiyria/bootstrap-slider#614]
String 734:12 of bootstrap.js v 9.1.3:
			defaultOptions: {
				min: 0,
				max: 10,
				step: 1,
				value: 5
			}

Limesurvey (i'm not contributor) set data-slider-value="" to check user activity with sliders in last git version. If data-slider-value keeps empty that mean user didnt interract with slider.
Downside: data-slider-value will be set to 5 on the screen even if data-slider-max is 1000 and data-slider-min is 500.
Is it possible to change default "value" from 5 to Math.round((data-slider-max - data-slider-min)/2)? Actual max and min if they are set, not default 10 and 0. data-slider-value should be unchanged. Or can you provide a vay to check, did user interract with a slider?

**Comment by seiyria** [comment]
You can always attach a `slide` event to a slider and set a boolean to check if the slider was changed.

If you want the slider value to be "in the middle" you can set the value. There's no need for us to provide that.
