### ISSUE TITLE
Undefined formatter response

### ISSUE THREAD

**Issue by IAMZEUS** [seiyria/bootstrap-slider#618]
I'm trying to enable the formatter function to change how the tooltip displays the data, but I'm getting an error. I've used the data-attribute method to setup the slider

`<input id="testSlider"
						    type="text"
						    name="somename"
						    data-provide="slider"
						    data-tooltip-position="right"
						    data-slider-min="200"
						    data-slider-max="2500"
						    data-slider-step="50"
						    data-slider-value="750"
						    data-slider-tooltip="always"
						    data-slider-orientation="vertical"
						    data-slider-reversed="true"
						    data-slider-id="RC"
						>`

and I initiate the formatter with:

`var slider = new Slider('#testSlider', {
	formatter: function(value) {
		return 'Current value: ' + value;
	}
});
`

But it doesn't effect the format, and when I try to enter the function manually through the console, it tells me that the value is undefined. Suggestions?

**Comment by seiyria** [comment]
Please provide a jsfiddle showing what you're trying to do.

**Comment by IAMZEUS** [comment]
In the JS fiddle it's creating a new slider when all I want to do is add the formatter functionality to pre-existing slider. Do I have to bail on the data-atrribute method, and fully create these using the js?

https://jsfiddle.net/iamzeus/mrtqhysp/3/

**Comment by seiyria** [comment]
So the thing is, if you use data-provide the slider is initialized for you. If you want a formatter, yes, you have to initiate it with JS.

**Comment by IAMZEUS** [comment]
Thank you
