### ISSUE TITLE
Initializing issues

### ISSUE THREAD

**Issue by IAMZEUS** [seiyria/bootstrap-slider#620]
So the slider is initializing in JSFiddle, but in Wordpress the script isn't firing when the page loads, however; it will work if it is entered into the console on that page. Any suggestions?

https://jsfiddle.net/iamzeus/w5rL9g9y/

**Comment by seiyria** [comment]
It's hard to say, but it looks like it works in your fiddle. We'd need an example that can showcase your environment because right now it looks like the environment is at fault, not the slider.
