### ISSUE TITLE
Except ticks

### ISSUE THREAD

**Issue by azjoss** [seiyria/bootstrap-slider#624]
Could be useful make disable some ticks
eg. I need selection with [1,2,4]
      settings are:
          ticks: [1,2,4]
          ticks_labels: [1,2,4]
     but value 3 is available - that is not preferable..

it can be solved to define power of number where value define power of step for example
eg. same settings with
          math: "power"

**Comment by cchubb** [comment]
I would also like to be able to use exactly this use case. I've tried all the combinations of ticks, ticks-labels, ticks-positions that I can think of and I still get "3" values to be acceptable.

**Comment by seiyria** [comment]
If you have a definable function, just use ticks 1,2,3 and use the formatter function to convert it.

**Comment by cchubb** [comment]
Using the formatter doesn't appear to alter the value returned from the "getValue" call though. Just what's displayed on the tooltip, which I don't use.

**Comment by seiyria** [comment]
Correct, and it won't. You can, however, use the same formatter function when you call getValue.

**Comment by cchubb** [comment]
That's not really going to work. I need that scale for 3 of the 20+ sliders on a page that I read in an .each() loop. I'll have to write a custom attribute to drive the conversions. I still think that this is a desirable use case. I may fork-n-fix it.

**Comment by cchubb** [comment]
I haven't forked the code yet, but I wrote this little **data-slider-tick-values** shim to help me out:

For a control like this:
```
<input id="id1" type="text"
data-provide="slider"
data-slider-ticks="[0, 1, 2]"
data-slider-ticks-labels='["No (0)", "< 25% (1)", "> 25% (3)"]'
data-slider-tick-values="[0, 1, 3]"
data-slider-value="0"
 />
```

I wrote some shims like this:
```
dao.prototype.sliderGet = function ($control) {
    //If this slider has the attribute 'data-slider-tick-values' then use the value as the index to this array
    var field_value = $control.slider('getValue');
    //If I have a set of values, dereference it. 
    if ($control.is('[data-slider-tick-values]')) {
        var tick_values = eval($control.attr('data-slider-tick-values'));
        field_value = tick_values[field_value];
    }
    return field_value;
}
```

and

```
dao.prototype.sliderSet = function ($control, field_value) {
    //If this slider has the attribute 'data-slider-tick-values' then use the value as the index to this array
    if ($control.is('[data-slider-tick-values]')) {
        var tick_values = eval($control.attr('data-slider-tick-values'));
        index = $.inArray(field_value, tick_values);
        if (index >= 0) {
            field_value = index; //I really want to set the slider to the index in the array
        }
    }
    $control.slider('setValue', Number(field_value));
}
```

It needs some input and bounds validation, but that lets me optionally de-reference slider value to "real" value.
