### ISSUE TITLE
Looks like apostrophes are used instead of single quotes around line 1077

### ISSUE THREAD

**Issue by george-viaud** [seiyria/bootstrap-slider#634]
Not sure why or if this is legal somehow, but IE11 is throwing an error regarding this which is fatal.

Going to pull this repo and make the fix / pull request.

**Comment by seiyria** [comment]
Please use dist and not src for inclusion in your code.

**Comment by george-viaud** [comment]
Ahhh that explains things indeed.  Many thanks for the direction, and apologies for the dust this has caused.

**Comment by seiyria** [comment]
Not a problem. Worse things have happened.
