### ISSUE TITLE
Error when using destroy & reinitialize slider

### ISSUE THREAD

**Issue by maydemirx** [seiyria/bootstrap-slider#640]
Hello,
i am trying to bind event 'slideStop' after destroy & reinitialize the slider then an error throwing 

> bootstrap-slider.js:970 Uncaught TypeError: Cannot read property 'push' of null

You can see the bug at https://jsfiddle.net/maydemirx/jcuo8ksp/

**Comment by maydemirx** [comment]
By the way you checking the variable is undefined but after destroy the variable value is null.

**Comment by rovolution** [comment]
found the issue i am making a fix

**Comment by rovolution** [comment]
@maydemirx fix is published to 9.3.2
