### ISSUE TITLE
Update NuGet Package

### ISSUE THREAD

**Issue by Almeonamy** [seiyria/bootstrap-slider#643]
Hello. I found your project in NuGet, but it is only about old version 5.0.13. Can you apdate this NuGet package to last version?

**Comment by seiyria** [comment]
Hi. We do not control the nuget package. Please check our Readme and post an issue in their tracker (or email the person who maintains it). Thanks!

**Comment by Almeonamy** [comment]
Ok, I understand. But can you create your own nuget package? Sorry, if I'm importunate.

**Comment by seiyria** [comment]
We can, but:

* we wouldn't use it
* it'd be another thing to maintain
* it would probably confuse people to see two of them

So, it's in everyone's best interest if we do not. Sorry.
