### ISSUE TITLE
Fail to access slider

### ISSUE THREAD

**Issue by rissom** [seiyria/bootstrap-slider#647]
I can't make it work :( 
==============

On my pc I get a nice slider, but I also get an error message:
Uncaught TypeError: Cannot read property 'getAttribute' of null(…)getDataAttrib @ bootstrap-slider.js:383createNewSlider @ bootstrap-slider.js:356Slider @ bootstrap-slider.js:314(anonymous function) @ perovskite.js:19

The slider function just returns null. On JSFiddle I don't even get the slider. Find it here:
https://jsfiddle.net/q5w07zdn/1/

I am sure I am missing something really dumb. But I need help.

Best regards,

Thorsten

**Comment by seiyria** [comment]
You have to use an appropriate selector (ie, `#slider` instead of `slider`): https://jsfiddle.net/q5w07zdn/2/
