### ISSUE TITLE
tooltip is offset, out of the parent div

### ISSUE THREAD

**Issue by sorryjack** [seiyria/bootstrap-slider#649]
thanks for making this awesome slider.

I implemented the tooltip_split : true

the minimum one, the left is offset the div, so does the max one. please see the screenshot.
![screenshot-local jack-2016-11-03-12-02-56](https://cloud.githubusercontent.com/assets/6811578/19956353/194818ac-a1be-11e6-8da7-ba1a477f6135.png)
is it possible to make the tooltip  auto positioned when the reach their edge wether min or max to keep the tooltip visible? 

thanks.

**Comment by seiyria** [comment]
I don't understand. The tool tips are centered on top of the handles, but
I'm not sure what you're getting at.

**Comment by sorryjack** [comment]
![cropped](https://cloud.githubusercontent.com/assets/6811578/19993924/cc41a2b2-a27b-11e6-9728-118433c6d7a2.png)
please consider as its on mobile device or full width view. the tooltip is only half visible.

Thanks.

**Comment by seiyria** [comment]
That happens with tool tips. Add some padding on the left and right until
it fits the way you want.

**Comment by roba91** [comment]
In fact, bootstrap is capable of keeping tooltips in bound.

> Appends the tooltip to a specific element. Example: container: 'body'. This option is particularly useful in that it allows you to position the tooltip in the flow of the document near the triggering element - which will prevent the tooltip from floating away from the triggering element during a window resize.

From http://getbootstrap.com/javascript/#tooltips

**Comment by seiyria** [comment]
Append to body would not solve this issue, it prevents it from getting clipped when it would otherwise overflow the container.

That said, if a fix is desired, then please send a PR.
