### ISSUE TITLE
Slider width bug in Bootstrap3

### ISSUE THREAD

**Issue by gslender** [seiyria/bootstrap-slider#65]
As per this jsfiddle...

http://jsfiddle.net/gslender/2DygG/1/

for completeness, here is the jsfiddle using the new/later JS that contains the fix

http://jsfiddle.net/gslender/2DygG/2/

**Comment by marven89** [comment]
hi,
can i fix this problem without editing the js file ?!

**Comment by seiyria** [comment]
This isn't a problem.

**Comment by marven89** [comment]
i am trying to put a slider in a "col-md-12" but i get width:"100px" in my site !

**Comment by marven89** [comment]
check this plz
![sans titre](https://cloud.githubusercontent.com/assets/10834343/6025266/5dce5a7a-abd1-11e4-8253-3dfab3421e57.png)

**Comment by seiyria** [comment]
You can always just change the css for the slider to be width: 100%.

**Comment by marven89** [comment]
it's already 100% but it is hashed :/
as you see the left one is ok !

**Comment by marven89** [comment]
look at this !
![sans gh](https://cloud.githubusercontent.com/assets/10834343/6025435/c4d86552-abd2-11e4-9d40-9447d790aefe.png)

**Comment by seiyria** [comment]
If you really need to, set !important on it.

**Comment by marven89** [comment]
thank you, i forget that ;)
