### ISSUE TITLE
Customisation tooltip

### ISSUE THREAD

**Issue by NicolasVanhecke** [seiyria/bootstrap-slider#650]
Is there a way to customise the tooltip a little?
Let's say, have the tooltip show under the slider instead of on the top.
Or change the ':' when having two inputs? Now tooltip is showing '10:100' and I would like something more like '10 - 100'.

Haven't found anything in the (million) tickets on here so.. let's hope someone has a solution for this already.

**Comment by seiyria** [comment]
* use `tooltip_position`
* this is not possible, but you can use `tooltip_split` to show two tooltips instead of 1, and there isn't a split character.
