### ISSUE TITLE
Allow Tick Labels without Ticks

### ISSUE THREAD

**Issue by sabbiu** [seiyria/bootstrap-slider#654]
Can I be able to place tick labels only, without creating bulge in the slider?
Similar to the one shown here: http://egorkhmelev.github.io/jslider/

**Comment by seiyria** [comment]
I don't believe this is possible, but I think it would make a good PR.

**Comment by rovolution** [comment]
not currently possible, but we would definitely accept a PR for it!

**Comment by sabbiu** [comment]
Hopefully, you all shall come up with better bootstrap-like CSS for this :)
