### ISSUE TITLE
"none" classes not removed when selection="after" is applied to existing slider

### ISSUE THREAD

**Issue by john-clarke** [seiyria/bootstrap-slider#658]
`.slider-track-low`, `.slider-selection`, and `.slider-track-high` elements maintain their `hide` class after a change to the slider's selection attribute. I will post a PR fix and tests shortly.

The first slider below displays correctly (select="after" defined at init). The second slider had its selection attribute changed, but does not update its appearance.
![image](https://cloud.githubusercontent.com/assets/1505085/20547769/6ec3bc40-b0ec-11e6-99bc-2535a96df9d2.png)

https://fiddle.jshell.net/jvx1fgof/2/

**Comment by john-clarke** [comment]
@seiyria @rovolution I have a fix (with tests passing) but can't publish it.

**Comment by seiyria** [comment]
you ... need to fork the repo, and submit a pull request.
