### ISSUE TITLE
tick labels are not correctly positioned under ticks when latter created at different step

### ISSUE THREAD

**Issue by ilychakov** [seiyria/bootstrap-slider#660]
See attached image that shows how tick labels positions are moving aside from its ticks
<img width="1124" alt="slider_tick_labels" src="https://cloud.githubusercontent.com/assets/1171411/20726411/775a4566-b643-11e6-8538-e7d831c415ae.png">

Please note that last tick (28) has different value from the step (5) that causes the issue.

The solution could be in using same HTML approach for tick labels as used for ticks.
- .slider-tick-label-container class should have 'position:absolute;', etc similar to .slider-tick-container
- .slider-tick-label class should be similar to .slider-tick in terms of absolute position and 'left: N%'
Making above simple change resolves the issue

**Comment by xakzona** [comment]
I have found the solution, usign PHP (you can use your own language):
`function bootstrapSliderTickPercents($min, $max, array $values):array
{
    $returns = [];
    $max = log($max);
    $min = ($min == 0) ? 0: log($min);
    foreach ($values as $value) {
        $v = ($value == 0) ? 0 : log($value);
        $returns[] = number_format(100 * ($v - $min) / ($max - $min), 4);
    }
    return $returns;
}`

and in slider definition added ticks-positions property (my example in html data attribute):
`data-slider-ticks-positions="[{{ implode(',', bootstrapSliderTickPercents($min, $max, $scale)) }}]"`

**Comment by ilychakov** [comment]
Hi xakzona,
that is great solution without changing css.
Attaching screenshot.
Thanks!
<img width="1092" alt="fixed_slider" src="https://cloud.githubusercontent.com/assets/1171411/21321004/ff8fa050-c5e0-11e6-8648-99a595745d31.png">
