### ISSUE TITLE
jquery is mandatory when using with Browserify

### ISSUE THREAD

**Issue by julienbachmann** [seiyria/bootstrap-slider#661]
If you want to use bootsrap-slider as a CommonJS module with Browserify, then you must have jquery otherwise you will have the following error at build time:
```
Cannot find module 'jquery' from '...../node_modules/bootstrap-slider/dist'
```

**Comment by rovolution** [comment]
Did you read the following section in our README? https://github.com/seiyria/bootstrap-slider#how-do-i-exclude-the-optional-jquery-dependency-from-my-build

**Comment by julienbachmann** [comment]
Oups, sorry. I didn't read that. I think you can close this issue 😊

Envoyé de mon iPhone

**Comment by julienbachmann** [comment]
In fact I had to add the following option to my browserify to make it work without jquery:
`ignore-missing: true`

Just using `exclude: "jquery"` was not fixing the compile issue

**Comment by rovolution** [comment]
@julienbachmann did you try just using the `--ignore` flag? https://github.com/substack/node-browserify#usage

if that works, i can go ahead and update the docs

**Comment by rovolution** [comment]
@julienbachmann did you get a chance to see my comment above? I would love to update our docs to more accurately reflect this scenario

**Comment by julienbachmann** [comment]
@rovolution sorry for my late answer. I forgot to answer you 😊.
I tested with `--ignore` but without any success. The only way I was able to make it work is by using `ignore-missing: true`

**Comment by rovolution** [comment]
@julienbachmann Thanks! Just went back and added this in to the README - https://github.com/seiyria/bootstrap-slider/commit/39def8a18a5dcf90a26197c981075338ba1d1fec
