### ISSUE TITLE
scss files are not up-to-date

### ISSUE THREAD

**Issue by julienbachmann** [seiyria/bootstrap-slider#662]
I would like to import scss files to style bootstrap-slider because I am using Saas. But it looks like the scss files are wrong.

less version 
``` 
&.slider-vertical {
		height: @slider-vertical-height;
		width: @slider-line-height;
		.slider-track {
			width: (@slider-line-height/2);
			height: 100%;
			left: 25%;
			top: 0;
		}
```

and the scss version:
```
&.slider-vertical {
    height: $slider-vertical-height;
    width: $slider-line-height;
    .slider-track {
      width: $slider-line-height/2;
      height: 100%;
      margin-left: -$slider-line-height/4;
      left: 25%;
      top: 0;
    }
```

you can see the the scss version has a margin-left for class `slider-track` that the less has not.
And this margin just break the layout.

Could you fix scss files or remove them if they are no more maintained.

Thanks,

**Comment by seiyria** [comment]
we would appreciate a PR! we don't actively maintain it but it was added due to community request so I'm not sure about removing it.
