### ISSUE TITLE
Not work in mobile browsers

### ISSUE THREAD

**Issue by Astraport** [seiyria/bootstrap-slider#666]
Hi,
I create new project with your range slider and all work fine in the desktop browsers, but in iPad or phones browsers the slider displayed as text input. How to fix it? Thanks.

**Comment by seiyria** [comment]
please create a jsfiddle so we can see what you're doing.

**Comment by Astraport** [comment]
https://jsfiddle.net/6s56ecd2/
An error probably is in line 53.

**Comment by seiyria** [comment]
It's not working in your jsfiddle either (on desktop).

**Comment by Astraport** [comment]
https://jsfiddle.net/6s56ecd2/9/
I see but why? 
This code works fine on the server http://vnushator.ru/russia/

**Comment by seiyria** [comment]
I'd wager because of these errors:

```
Refused to execute script from 'https://github.com/seiyria/bootstrap-slider/blob/master/dist/bootstrap-slider.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
jquery.min.js:4 Mixed Content: The page at 'https://jsfiddle.net/6s56ecd2/12/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://vnushator.ru/russia/data/data.csv'. This request has been blocked; the content must be served over HTTPS.send @ jquery.min.js:4
jquery.min.js:4 XMLHttpRequest cannot load http://vnushator.ru/russia/data/data.csv. Failed to start loading.
```
