### ISSUE TITLE
Slider grows out of control with width:100% in flex layout

### ISSUE THREAD

**Issue by nsoft** [seiyria/bootstrap-slider#674]
The tick labels don't place properly and when the window (or frame) is resized, the length of the slider element gets longer, aparently once per resize event. One very quickly winds up with a slider that is a million pixels wide. (that's not a joke https://snag.gy/owbBJe.jpg).

Here's the fiddle, just resize the window a bit and you won't miss it :)

https://jsfiddle.net/8jexax4k/

Here's one with a non-flex version of the layout. It's better behaved, though there seem to be some tick label migration problems (I don't see that outside of jfiddle though)

**Comment by seiyria** [comment]
Weird. If you have a fix, we'd appreciate it!

**Comment by nsoft** [comment]
I sure wish I did!

**Comment by TakesTheBiscuit** [comment]
Close this issue.
@seiyria wasn't using the bootstrap css file, but is trying to use this *bootstrap* targeted repo in a non-use case scenario (i.e running it without bootstrap css and without any bootstrap container DOM elements).

See my modification of the jsfiddle here: https://jsfiddle.net/eswoosh/wjaooop8/2/

**Comment by nsoft** [comment]
My skill with setting up fiddles is likely lacking, but bootstrap-slider was being pulled via npm in my build, and the bootstrap css was downloaded and supposed to be included, so the snarkiness about "this is a bootstrap repo" is not appreciated. With your improved fiddle example, I traced the build process and see the bootstrap css was probably being missed by the minifier. Since bootstrap was mostly brought in to support this nicely configurable slider library, this miss by the minifier wasn't immediately apparent. Unfortunately, I have long since ripped out the offending sliders, and coded a use case specific poor man's version. I do wish you had made your snarky comment several months ago...

Finally, If there is some requirement beyond invocation of the javascript as shown on the front page (such as it MUST live inside a particular type of bootstrap container), perhaps this could be documented there as well?

**Comment by TakesTheBiscuit** [comment]
Sorry it wasn't supposed to sound sarcastic. 😔 Friends?

**Comment by nsoft** [comment]
hehe sure we can be friends, just keep in mind that it's possible that (sometimes) I'm not an idiot :)

**Comment by seiyria** [comment]
[It is documented that you need js/css](https://github.com/seiyria/bootstrap-slider#basic-setup).

**Comment by nsoft** [comment]
I agree that both the need for css and js are documented. The comment above alleges that in addition to js and css, a boststrapified container is also necessary.

**Comment by seiyria** [comment]
Given that we don't have a hard dependency on bootstrap, I don't think that's necessarily true.

**Comment by LuckyLuzz** [comment]
struggling with the same problem. Has someone found a solution?
