### ISSUE TITLE
destroy() generates errors

### ISSUE THREAD

**Issue by matejlednar** [seiyria/bootstrap-slider#677]
Hi

I have following problem. I want update min and max values when slider exists. I didn't find any way how to do it. I tried to use destroy() method and create slider again, but I will get error. Now I am recreating Slider each time when I need to change min, max values without destroy() method. But I am using onchange event and not sure if I don't have memory consumption/leak because of existing events before (widget wasn't destroyed and registered events are probably still in memory).

**Comment by seiyria** [comment]
Please provide a jsfiddle and steps to recreate this.

**Comment by matejlednar** [comment]
I will do it next week.

**Comment by matejlednar** [comment]
Sorry for my delay, but I forgot it :-) Here is a sample with

 TypeError: Cannot read property 'removeChild' of null
    at Slider.destroy (bootstrap-slider.js:923)
    at issue-1.html:44
destroy @ bootstrap-slider.js:923
(anonymous) @ issue-1.html:44

Now I used version 9.7.3 and error still exists but don't remember if it is same error or not and therefore I wrote it above.

        <div class="container">
            <h1>https://github.com/seiyria/bootstrap-slider</h1>
            <p>https://cdnjs.com/libraries/bootstrap-slider</p> 
            <div id="slider"></div>
        </div>
        <script>
            $(document).ready(function () {
                function createSlider(options) {
                    return new Slider("#slider", options);
                }

                var slider = createSlider({
                    min: 1,
                    max: 10,
                    step: 1,
                    value: 3
                });

                setTimeout(function () {
                    slider.destroy();
                    createSlider({
                        min: 1,
                        max: 20,
                        step: 1,
                        value: 10
                    });
                }, 2000);
                setTimeout(function () {
                    slider.destroy();
                    createSlider({
                        min: 1,
                        max: 30,
                        step: 1,
                        value: 15
                    });
                }, 4000);
            });

        </script>
