### ISSUE TITLE
Add a general rtl mode ( !==inverse )

### ISSUE THREAD

**Issue by Shnoulle** [seiyria/bootstrap-slider#678]
Feature : rtl mode (option)
=============

Have a real rtl system :

1. currently have dir="rtl" in html (or elsewhere) don't change anything to slider. 
2. Using [reversed](https://github.com/seiyria/bootstrap-slider#options) seems to be a solution : but this not fix : not really rtl mode. slider-selection class are at left, must be at right
3. There are no other option to show slider 'right to left'
4. This is particularly demonstrated when you want something before/after the slider.

- **JSFiddle** https://jsfiddle.net/7rb7oed4/1/
- **Reproduce** : Just add dir="rtl" to HTML or wrapper element

## Example picture ##

ltr-mode (reversed or not)
![ltr-mode](https://cloud.githubusercontent.com/assets/1439428/21524205/a37796f2-cd14-11e6-88c9-0446b1d7192e.png)

rtl-mode (reversed or not)
![rtl-mode](https://cloud.githubusercontent.com/assets/1439428/21524217/b231abf6-cd14-11e6-80c4-1ba7b8eb4e4d.png)

## Some idea ## 
if OK : i start to work on "issue"

- [x] Add a rtl option (default false)
- [x] Set inlined style according to this option
- [x] Add slider-rtl class to wrapper ( slider (slider-horizontal|slider-vertical)
- [x] Fix css file according top this class
- [x] Set rtl mode automatic according to dir="rtl" (? unsure)

**Comment by seiyria** [comment]
I think we'd be ok with a feature like this. If you do it, I think detection of dir=rtl is fine.

**Comment by seiyria** [comment]
A forced option is also a good choice. Just in case someone doesn't like what auto-detection does.

**Comment by Shnoulle** [comment]
- [x] Set rtl mode automatic according to dir="rtl"
- [x] Add a rtl option (default 'auto')
- [x] Set inlined style according to this option
- [x] Add slider-rtl class to wrapper ( slider (slider-horizontal|slider-vertical))
- [x] Fix css file according top this class

Updated jsfiddle (using new js/css) https://jsfiddle.net/t7ccex4a/1/
