### ISSUE TITLE
Error compilation Sass

### ISSUE THREAD

**Issue by Schepotin** [seiyria/bootstrap-slider#682]
v9.6.0

![image](https://cloud.githubusercontent.com/assets/6001723/21638186/eeac64dc-d272-11e6-944c-f568d38a5d25.png)

**Comment by rovolution** [comment]
working to resolve this right now

**Comment by rovolution** [comment]
should be resolved in v9.6.1

thanks for bringing to our attention so quickly! I added a TODO to add linting to the SASS/LESS files so we can be more proactive about catching these issues in our CI check phase

**Comment by Shnoulle** [comment]
Oups ... sorry .... seems to be my pull request :blush:
