### ISSUE TITLE
Hey , i have an issue with this amazing slider. When I click on the slider selector, it remains selected and I can not release it

### ISSUE THREAD

**Issue by lolo4456** [seiyria/bootstrap-slider#686]
Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [x] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [x] Instructions to replicate the bug in the Fiddle

**Comment by seiyria** [comment]
Please actually fill out the checklist.

**Comment by lolo4456** [comment]
ok

**Comment by lolo4456** [comment]
sorry

**Comment by lolo4456** [comment]
Hello how are you? 
This is the issue 
https://www.rachatducredit.com/calculatrice-de-credit

**Comment by lolo4456** [comment]
I try to resolve this today but i can't

**Comment by lolo4456** [comment]
can you help me?

**Comment by seiyria** [comment]
If you want help, we ask that you make a jsfiddle to isolate potential environment problems (this means the site you linked above is not a sufficient example). Additionally, lots of people get emails you send messages and file issues, so please condense it down into one message that actually explains the problem and provides a suitable reproduction.
