### ISSUE TITLE
Does not work on a desktop Chrome since version 55 and above

### ISSUE THREAD

**Issue by tony-chupak** [seiyria/bootstrap-slider#694]
Hello guys!
Slider doesn't work on a desktop Chrome since version 55 and above.

**Comment by seiyria** [comment]
Is this replicable on the examples page?

**Comment by tony-chupak** [comment]
Nope, but when I run my site on BrowserStack, in Chrome 54 and below - all okay.

**Comment by seiyria** [comment]
You'll need to provide a jsfiddle then, because if our examples page works in chrome 55, but not your environment, I suspect something in your environment is broken.

**Comment by tony-chupak** [comment]
I'm sorry, work blocked the other plugin
