### ISSUE TITLE
Multiple sliders events not fired

### ISSUE THREAD

**Issue by mStirner** [seiyria/bootstrap-slider#699]
I have some trouble with multiple sliders:

`  $("input.fx-slider").slider({
    reversed: true,
    tooltip: "hide",
    tooltip_position: "top",
    orientation: "vertical",
    min: 1,
    max: 255
  }).on("change", function(){
    console.log("Value changed");
  });`

In this example no slider fire up an event.
How can this work ?

**Comment by seiyria** [comment]
Please provide a jsfiddle.
