### ISSUE TITLE
Slider handle has delayed response on Amazon Fire Tablet

### ISSUE THREAD

**Issue by lvecchio** [seiyria/bootstrap-slider#702]
Issues
=============

When attempting to drag the slider-handle on the Amazon Fire tablet, the dot does not register the touch action correctly and moves sporadically across the slider. This issue is specific to the Amazon Fire tablet and not the Apple devices.

**Comment by seiyria** [comment]
is there a place we can reproduce this?

**Comment by lvecchio** [comment]
Unfortunately this only lives in a non-production environment at the moment, but I will update the issue once the site has been deployed.

**Comment by seiyria** [comment]
if it's not reproduceable in a jsfiddle or on our examples page then it's very likely an issue with your environment and not anything we can control
