### ISSUE TITLE
.slider() is not triggered when clicking on a slider

### ISSUE THREAD

**Issue by yojick** [seiyria/bootstrap-slider#704]
When you click with a mouse somewhere on a slider, .slider() event does not trigger, so if there is some JS which changes the slider's caption, it does not work properly. See example 6: http://seiyria.com/bootstrap-slider/

STR:
----

* Go to http://seiyria.com/bootstrap-slider/
* Find example 6
* Click on the slider's scale with a mouse

**ER**: "Current Slider Value" changes to the new value
**AR**: "Current slider value" remains unchanged until you drag the slider

Chrome for Linux, version 53.0.2785.101 (64-bit)

**Comment by seiyria** [comment]
There is no `slider` event. There's `slide` and `change` - you want the `change` event in this case. Slide is literally only when people slide.

**Comment by yojick** [comment]
@seiyria  thanks Kyle! My fault, I hasn't read the doc thoroughly.
