### ISSUE TITLE
Always display labels

### ISSUE THREAD

**Issue by kpagcha** [seiyria/bootstrap-slider#708]
I am trying to use labels but they are only displayed when clicking on the slider. It also shows when showing the Chrome console for some reason (I guess because it triggers a window size changed event). When the page loads it looks like this:

![captura](https://cloud.githubusercontent.com/assets/3865095/23165152/05447516-f83b-11e6-9f16-915499c27b41.PNG)

I tried recreating a [jsfiddle ](https://jsfiddle.net/u3grng5u/)but the styles are messed up.

**Comment by seiyria** [comment]
please provide a jsfiddle or reference an example

**Comment by kpagcha** [comment]
I did include a jsfiddle. That's the code I'm using.

**Comment by seiyria** [comment]
whoops, sorry, I missed that.
