### ISSUE TITLE
Convert range slider into min/max selector

### ISSUE THREAD

**Issue by kpagcha** [seiyria/bootstrap-slider#710]
Since the range slider has two values I am trying to use it as a min & max selector. However there is just one tooltip that shows the value with the format `leftVal : rightVal`. Is it possible to show each tooltip separatedly right above each value?

**Comment by seiyria** [comment]
yes, use `tooltip_split: true`.

**Comment by kpagcha** [comment]
Great, awesome. Might be a good idea to include it in the [examples](http://seiyria.com/bootstrap-slider/), since that option is missing there and it's pretty handy and recurrent.

**Comment by rovolution** [comment]
@kpagcha we would welcome a PR with this addition to our examples page thanks!

**Comment by kpagcha** [comment]
@rovolution PR?

**Comment by seiyria** [comment]
@kpagcha a pull request - fork the repository, submit the changes, and we'll merge them

**Comment by kpagcha** [comment]
@seiyria sure, will do
