### ISSUE TITLE
setValue array exception

### ISSUE THREAD

**Issue by kpagcha** [seiyria/bootstrap-slider#711]
I am trying to use `setValue` to set the values for a ranged slider, so I am passing an array of integers. However, when trying to do this an exception is thrown:

`Uncaught TypeError: a.toFixed is not a function`

I am setting up the following slider:

```
var slider = $('input#minmax-constraint-select').bootstrapSlider({
    ticks: [0, 30, 60, 120, 180, 360, 720, 1440, 2880, 4320],
    // ticks_labels: ['0m', '30m', '1h', '2h', '3h', '6h', '12h', '1d', '2d', '3d'],
    ticks_snap_bounds: 30,
    scale: 'logarithmic',
    step: 15,
    tooltip_split: true
});
```

And then I'm setting the value as follows:

`slider.bootstrapSlider('setValue', [minVal, maxVal]);`

Being `minVal` and `maxVal` integers.

Here is a [jsfiddle](https://jsfiddle.net/j3uLb6wn/3/).

**Comment by sebcaps** [comment]
@kpagcha  add `range: true` in slider definition should do the trick ;-)

**Comment by seiyria** [comment]
@sebcaps is correct.
