### ISSUE TITLE
mousedown event at the beginning of the slide action

### ISSUE THREAD

**Issue by kpagcha** [seiyria/bootstrap-slider#713]
I am programatically changing the value of the tooltips so I set this up:

`slider.on('slideStop slide change', updateSliderTooltips);`

I am taking the values from the corresponding slider `aria-valuenow`. It works perfectly for the ranged slider.

However, I am having a slight issue with the normal slider. It does work when sliding, stopping or whatever. But there is a particular case where the original tooltip value is being displayed, and that's when holding the mouse on the slide handler without moving it. I tried setting up a way to respond to this event like this:

`$('.slider').find('.slider-handle').on('mousedown', updateSliderTooltips);`

But this didn't  help at all.

It's weird that the exact same action does not cause this problem with the ranged slider.

**Comment by seiyria** [comment]
Why don't you use the formatter function to change the tooltips?

**Comment by kpagcha** [comment]
@seiyria probably because I'm stupid and missed that feature haha! thank you! I wished I had asked this 2 hours ago because that's what took me to implement the custom tooltips.
