### ISSUE TITLE
Why is the initial slider value not zero ?

### ISSUE THREAD

**Issue by Legends** [seiyria/bootstrap-slider#717]
**Why is the initial slider value not zero ?**

[Demo](http://jsbin.com/yobiwu/4/edit?html,js,output)

**Comment by seiyria** [comment]
You didn't pass in `value: 0`.

**Comment by Legends** [comment]
Passing `value : 0` doesn't work, same issue:

```
$("#ex13").bootstrapSlider({
	ticks: [0, 100, 200, 300, 400],
	ticks_labels: ['$0', '$100', '$200', '$300', '$400'],
	ticks_snap_bounds: 30,
	value: 0
});
```

**Comment by seiyria** [comment]
It works for me: http://jsbin.com/sutonesoqe/1/edit?html,js,output

**Comment by Legends** [comment]
Sorry, you are right, it was a caching problem. Thanks !
