### ISSUE TITLE
Tooltip is not showing at all

### ISSUE THREAD

**Issue by StarNeit** [seiyria/bootstrap-slider#723]
Tooltip is not showing at all. Is there any solution?

code:

*<input id="ex8" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="14"/>*

#ex1Slider .slider-selection {
	background: #BABABA;
}

$("#ex8").slider({
	tooltip: 'show'
});

Demo version is working correctly. Can you please let me know the version that demo is using now?

**Comment by seiyria** [comment]
Please don't intentionally open duplicates. Closing as a dupe of #715.
