### ISSUE TITLE
Backticks in code breaking IE11

### ISSUE THREAD

**Issue by JamieBradley** [seiyria/bootstrap-slider#726]
The latest version of the code has incorporated some changes which cause the script not to load in IE11 (and possibly other browsers).

i.e. this.rangeHighlightElements[i].style.right = `${currentRange.start}%`;

Why are you using backticks here? The version of the code used by the examples works fine in IE11 - it doesn't have this sort of thing going on. Sorry not to be more technical, but I don't even understand this code - it looks like some sort of templating language?

Note github has removed the backticks there... But they are in the code.

Update: apparently these are called "template literals". Support is pretty much non-existant.
![screen shot 2017-03-09 at 15 14 56](https://cloud.githubusercontent.com/assets/23026769/23756350/4cdaecbe-04db-11e7-94f3-7197e74b4683.png)

**Comment by JamieBradley** [comment]
Note bootstrap has removed the backticks there... But they are in the code.

**Comment by seiyria** [comment]
Because we transpile our code from ES6 to ES5. Please use the code in `dist`, not `src`.
