### ISSUE TITLE
Error: Cannot read property '_bound' of undefined

### ISSUE THREAD

**Issue by johhansantana** [seiyria/bootstrap-slider#727]
The slider works normally in desktop but when I try to use it in a mobile device (android) it gives me the error and the slider doesn't behave normally.

```javascript
let mySlider = new Slider('#ex2', {
  formatter: function(value) {
    return `Entre: $${value[0]} a $${value[1]}`;
  }
});

$scope.sliderValue = [0, 400];
mySlider.on('slideStop', (ev => {
  $scope.sliderValue = mySlider.getValue();
  $scope.$apply();
}));
```

<img width="628" alt="screen shot 2017-03-16 at 4 41 51 pm" src="https://cloud.githubusercontent.com/assets/9933887/24017719/7e5e708a-0a67-11e7-9108-fae1d55948be.png">

**Comment by seiyria** [comment]
please provide a jsfiddle or some reproducible example page. it looks like you're using angular, also, so it may be of benefit to check out the angular plugin I made for this a while back.
