### ISSUE TITLE
Not working on mobiles and tablets

### ISSUE THREAD

**Issue by poco06** [seiyria/bootstrap-slider#728]
Hello,

I just tried your plugin and it works fine on my PC but I have an issue with mobile (Android smartphone and Ipad2 tablet).

I have placed a range slider and instead of displaying the slider, I can see only one text area.

Is there something special to do in order to make it work for mobiles?

Regards
Pat

**Comment by seiyria** [comment]
please provide a jsfiddle or example because as far as we know this works correctly.

**Comment by poco06** [comment]
Hi,
Thanks for your quick reply.
Here is the jsfiddle 👍 
https://jsfiddle.net/poco06/51vuowub/2/
Regards
¨Pat

**Comment by seiyria** [comment]
that doesn't seem to work in a browser either

**Comment by poco06** [comment]
Try it again. I miss to upload the js file.
https://jsfiddle.net/poco06/4y64ydny/2/
 Now it is done and the slider displays properly on PC, but if you use a smartphone to display the jsfiddle, then, only the text area is there !

**Comment by seiyria** [comment]
Works on my phone. It's likely something in your environment. Please double check that everything is being imported. If that seems to be the case then please give us an actual stack Trace.

![screenshot_20170317-105537](https://cloud.githubusercontent.com/assets/763609/24051569/768165f4-0b00-11e7-850b-7e4257a8aed2.png)

**Comment by poco06** [comment]
Hello,
I just recheck with my Ipad2 and only the text area is seenable.
If I look at the jsfiddle on my PC, evethinh is fine.
So, I'm not sure how the environnement of my Ipad could bring something bad?
I attach a sreenshot of my Ipad2
Any idea
![img_0851 2](https://cloud.githubusercontent.com/assets/6254894/24053664/0fd8509e-0b3a-11e7-88b8-f6da4ab1b4f6.PNG)

**Comment by seiyria** [comment]
we will need an actual stack trace to diagnose anything.

**Comment by poco06** [comment]
Sorry,
Not sure to understand.
Let me know if I can do something to help to movz forward.
Are you able to display it correctly on an Ipad?
I have the same display issue than the attached file with my smartphone (S7 android).
Pat

**Comment by seiyria** [comment]
I mean that we need an actual error, because "it doesn't work" is not good enough when it works for me but not for you.

**Comment by poco06** [comment]
What I could not understand would be that you are able to display the https://jsfiddle.net/poco06/4y64ydny/2/ page correctly on your smartphone and Ipad.
To my knowledge, there is no specific configuration in terms of file loading on these devices (as we could have on PC), and so, the same error shoudl occur on different Ipad !
Let me know

**Comment by poco06** [comment]
Hello,
I have made some additional verifications. Here the situation :

Android + Chrome : OK
Android + Internet app : Not OK
Ipad + CHrome : Not OK
Ipad + Safari : Not OK
PC + CHrome : OK
PC + Firefox : OK
PC + IE11 not OK
PC = edge : OK

As you can see,the result depends on the OS + browser association and you can see on that some of these associations do not work.
Let me know.
Pat

**Comment by poco06** [comment]
Hi seiyria

Some good news. I have updated your plugin with the latest version (972) and it's working now.
Sorry for the previews posts, but it would be good to clarify the guthub situation for downloading as currently, you are proposed to download the 971 version !!!
Regards
Pat
