### ISSUE TITLE
How to interface it within a search form

### ISSUE THREAD

**Issue by poco06** [seiyria/bootstrap-slider#729]
Hello,

I would like to use your plugin in a search form and propose my users to select a range thanks to the bootstrap-slider.
In this form, I have 2 variables ($min-value and $max-value).
What's the best way to affect the values of the bootstrap-slider to these variables, if possible in real time as this is a dynamic search form ?

Many thanks for your help.
Pat

**Comment by seiyria** [comment]
please provide a jsfiddle with your attempt at solving this

**Comment by poco06** [comment]
Hello,

Please find the fiddle 👍

**Comment by seiyria** [comment]
Sounds like you can use the `change` event to solve this: https://github.com/seiyria/bootstrap-slider#events

**Comment by poco06** [comment]
Hello seiyria,

Could you just give me an example on how to interface it. In the above code, I need to affect the result of the hight slider value to 'tarif-journee-bs'

[wpv-control field="tarif-journee-bs" url_param="tarif-journee-bs_max"]
<div class="labelslide">Prix jour:</div>
<input id="exprix" type="text" class="span2" value="" data-slider-min="1" data-slider-max="50" data-slider-step="1" data-slider-value="[1,50]"/>

Many thanks
Pat
