### ISSUE TITLE
Range slider with ticks

### ISSUE THREAD

**Issue by alexlavriv** [seiyria/bootstrap-slider#734]
Hello, thank you for your project.
Is it possible to create a range slider with two handles and ticks? For example 0---100---200---500
I have tried to make it by myself, but I believe that  I miss something.
Thanks in advance.

**Comment by seiyria** [comment]
Yes, just combine the `range` and `ticks` options.

**Comment by alexlavriv** [comment]
ff

**Comment by alexlavriv** [comment]
Thank you for your answer, I have finally succeed, but still have some issues:
1. I want set the initial value, but the control always sets it on the max value.
2. I have to use external css to position the tiks' labels, is there a better way to do so? 
Here is my jsfiddle  https://jsfiddle.net/AlexLavriv/yfp6dm9t/
