### ISSUE TITLE
jQuery .on("slide") not triggering on click

### ISSUE THREAD

**Issue by abagshaw** [seiyria/bootstrap-slider#736]
As shown here: http://seiyria.com/bootstrap-slider/#example-6

When you click along the slider instead of sliding the slider, the "Current Slider Value" text does not update.

**Comment by seiyria** [comment]
This is known behavior. Use `change` if you want to capture all changes.

**Comment by abagshaw** [comment]
I tried that...but I don't seem to always get the up-to-date value for some reason. Besides, even if this is how you want your slider to function maybe update the example as "Current Slider Value" does not always reflect the current slider value.

**Comment by seiyria** [comment]
This is [fairly well-documented](https://github.com/seiyria/bootstrap-slider#events) already. We encourage people to look at the documentation in tandem with the examples.
