### ISSUE TITLE
Cant use class as jQuery selector for multiple sliders

### ISSUE THREAD

**Issue by oobie11** [seiyria/bootstrap-slider#738]
Maybe I'm missing something, but it doesn't appear that I can use a html class as a selector in order to build multiple sliders on the same page. 
 I'm trying to add multiple sliders to a page, but it only works if I explicitly select each slider element in my js. 
Is there a way to initialize sliders on all elements with a specific class `$('.slider').slider()` instead of having to initialize each one separately `$('#slider1').slider()` `$('#slider2').slider()`?

**Comment by seiyria** [comment]
`$('.slider').each(sl => sl.slider())` would be one way.
