### ISSUE TITLE
No way to counter overflow hidden

### ISSUE THREAD

**Issue by kmccullough** [seiyria/bootstrap-slider#745]
Other angular-bootstrap components include an 'append-to-body' property, which allows displaying a tooltip, for example, outside of the overflow hidden area, by appending the tooltip to the 'body' element, rather than within/alongside the component. Currently there is no such mechanism in this library, and I cannot get a tooltip to appear, because it is cut-off by it's parent's overflow: hidden style.

**Comment by seiyria** [comment]
If you're referring to the angular wrapper, please file an issue here: https://github.com/seiyria/angular-bootstrap-slider

feel free to provide a patch for this if you have one.

**Comment by kmccullough** [comment]
https://github.com/seiyria/angular-bootstrap-slider/issues/150
