### ISSUE TITLE
Selection of DOM around while sliding

### ISSUE THREAD

**Issue by etlel** [seiyria/bootstrap-slider#746]
This is a great tool. I wonder if it is possible to prevent the selection of the DOM elements around the slider when sliding. The selection is a bit ticklish and easily catches the contents of the tooltip and beyond.

**Comment by seiyria** [comment]
Can you provide an example of what you mean? I don't quite follow.

**Comment by etlel** [comment]
Of course. On these screenshots im sliding and the text around is selected, if I don't stay straight on the handle.

![capture du 2017-05-07 22-32-40](https://cloud.githubusercontent.com/assets/17115179/25788190/31092b9a-3375-11e7-8cf5-93ff60d67b90.png)

![capture du 2017-05-07 22-29-32](https://cloud.githubusercontent.com/assets/17115179/25788150/f69cb7ce-3374-11e7-816f-d6855712ded4.png)

**Comment by seiyria** [comment]
The only thing we could really do is text-selection: none (or whatever) on the tooltip. I don't think I've ever seen this myself, so I think that's what I'd recommend you do.

**Comment by str** [comment]
This also happens to me

![selection_001](https://user-images.githubusercontent.com/123817/27735024-be246738-5d5a-11e7-8837-9c1aa50f294b.png)

**Comment by Fl0ux** [comment]
I can confirm this issue with Firefox at least.

Solution : 
```css
.tooltip {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by ktsaou** [comment]
I have the same problem.
@Fl0ux solution works for the tooltip, but selection is still enabled for the rest of the page:

![peek 2017-11-19 19-08](https://user-images.githubusercontent.com/2662304/32993196-295c42ce-cd5d-11e7-8f58-f2eb26a13369.gif)

**Comment by ktsaou** [comment]
btw, the problem is also reproducible at the project's home page:

![peek 2017-11-19 19-14](https://user-images.githubusercontent.com/2662304/32993255-f7a69206-cd5d-11e7-8764-5c54b5a4ec6d.gif)

**Comment by ktsaou** [comment]
I tried chrome, firefox, opera, edge, safari. It happens only on firefox on both windows and linux.
