### ISSUE TITLE
No default value (cleared slider)

### ISSUE THREAD

**Issue by mghilardelli** [seiyria/bootstrap-slider#747]
Possibility of setting a null value which results that an empty slider is shown. 
Is it possible to do it easy with the exisiting API?

**Comment by seiyria** [comment]
No. It will not be - this is bad UX.

**Comment by mghilardelli** [comment]
If you mean, okay. But could give me a hint, how I could do it easy as possible? Thanks

**Comment by seiyria** [comment]
It is not currently doable with the code we have and I do not know the level of effort required to make it happen.
