### ISSUE TITLE
Bootstrap-slider with Angular 4

### ISSUE THREAD

**Issue by tappella** [seiyria/bootstrap-slider#749]
Hi,

I was wondering a way to import the Bootstrap-slider in an Angular4 project. Has anyone tried that?
After browsing through the issue I didn't find anything related, I'm not able to get it working.

Thanks,

**Comment by seiyria** [comment]
This is for plain js/jquery usage only (wrappers are hosted in separate repositories). There is, AFAIK, no written component that wraps the slider in an ng2 component. You would have to make one.

There is no reason for it not to work but it just hasn't been done.
