### ISSUE TITLE
Centered slider with negative and positive end points

### ISSUE THREAD

**Issue by absessive** [seiyria/bootstrap-slider#754]
How do I configure a slider with index (0) at the center and end points both positive and negative with the selection being colored on either end from the center (0)?

Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [ ] Instructions to replicate the bug in the Fiddle

**Comment by seiyria** [comment]
Use the `formatter` function. If you have values -4 to 4, set the min to 0, max to 9, and when transforming the value subtract 4.

**Comment by absessive** [comment]
@seiyria does that also allow setting the color for either side of the 0
-4 to 0 -> Red
and 
0 to 4 -> Green

**Comment by seiyria** [comment]
yes, you can set the range highlights however you want.
