### ISSUE TITLE
Change event object doesn't match docs format?

### ISSUE THREAD

**Issue by NinoSkopac** [seiyria/bootstrap-slider#756]
Looking at the docs (https://github.com/seiyria/bootstrap-slider#events), I would expect this to work:

```
$('#slider').on('change', function(values) {
    self.updateSpeed(values.newValue);
});
```

But `values.newValue` is undefined. 
Instead, this works:

```
$('#slider').on('change', function(values) {
    self.updateSpeed(values.value.newValue);
});
```

Can anyone explain?

**Comment by jespirit** [comment]
What is happening is that you're attaching a jQuery event handler on the `input` DOM element when you use `.on()`. The slider code will trigger the "change" event with `.trigger()` and will call your callback function and pass an eventData object with a `type` and `value`.

```js
$('#slider').on('change', function(values) {
    self.updateSpeed(values.value.newValue);
});
```

It makes more sense when you change the name of the argument of the handler.

```js
$('#slider').on('change', function(eventData) {
    self.updateSpeed(eventData.value.newValue);
});
```

https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L1853-L1860
