### ISSUE TITLE
Parent with 'hidden' attribute scrambles labels

### ISSUE THREAD

**Issue by jmaru** [seiyria/bootstrap-slider#757]
Issue:
"Scrambled" labels when parent container has "hidden" attribute while using '**data-provide**' (don't know if exclusive of this). The slider is properly rendered as soon as you touch the slider.
=============
**- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug**
[JSFiddle](https://jsfiddle.net/jmaru/pn5L8mr4/)

**- [ ] Instructions to replicate the bug in the Fiddle**
**EDIT:**Changed the order of the examples to match the ones in the Fiddle
- In order to trigger the bug, the slider input must be inside of parent with the 'hidden' attribute (Example 1).
- If the parent is hidden in Javascript with jquery's ".hide()" method, the slider is not affected (Example 2)
- It doesn't matter what parent, and it doesn't have to be an inmediate parent either, all the sliders contained within an ancestor with a hidden attribute are messed up (Example 3).

It looks like "the slider-tick-label-container" div is styled with "margin-left: 0px" and the "slider-tick-label" div is styled with "width: 0px". Those values change as soon as the slider is touch.
```
<div class="slider-tick-label-container" style="margin-left: 0px;">
    <div class="slider-tick-label" style="width: 0px;">S</div>
    <div class="slider-tick-label" style="width: 0px;">F</div>
    <div class="slider-tick-label" style="width: 0px;">T</div>
    <div class="slider-tick-label" style="width: 0px;">I</div>
    <div class="slider-tick-label" style="width: 0px;">A</div>
    <div class="slider-tick-label" style="width: 0px;">D</div>
</div>
```

**Comment by seiyria** [comment]
You probably have to do a refresh when unhiding it.

**Comment by jmaru** [comment]
That could work too, for now I'm hiding it via code with jQuery's ".hide()" method (I.E. $(".hidden").hide() ). Just wanted to mark this issue in case somebody run into it, I know is a minor thing, but caused me a lot of headaches.

**Comment by michaelvaneck** [comment]
There are 2 ways to fix it, Using the jquery hide or using Visibility:hidden instead of display:none

**Comment by jespirit** [comment]
You have to call `.slider('refresh')`. I forget where exactly in the code, but to layout the slider elements, it needs to know the properties of the elements (height, width, offsets, etc.), but some of that information cannot be calculated until the elements are displayed on screen when, the browser at that point, will actually calculate the dimensions.

https://jsfiddle.net/t4jabu10/
