### ISSUE TITLE
How to bind 'slide' JQuery event on slider, while using 'Range selector'

### ISSUE THREAD

**Issue by lechKurant** [seiyria/bootstrap-slider#760]
How can I display separately values of the 'range' slider?

For code (modified example 2):
`<b class="min">€ 10</b> <input id="ex2" type="text" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[250,450]"/> <b class="max">€ 1000</b>`

and (modified example 6):
```
$("#ex2").slider();
$("#ex2").on("slide", function(slideEvt) {
	$(".min").text(slideEvt.value);
});
```
I will get - for example - an answer: 

> 250,450

How can I split these values to replace the text in the ".min" class by first value, and in the ".max" class by the second value?

**Comment by seiyria** [comment]
If you console.log slideEvt.value, it is an array, meaning it will look like that. slideEvt.value is an array, so just destructure it like so:

var [min, max] = slideEvt.value

From there you can do your thing.
