### ISSUE TITLE
showTooltip and hideTooltip functions are not documented

### ISSUE THREAD

**Issue by NinoSkopac** [seiyria/bootstrap-slider#764]

**Comment by seiyria** [comment]
This is intentional. They are prefixed with underscores, meaning they're private in this case. You should use the tooltip option to manage this.

**Comment by NinoSkopac** [comment]
I saw those, but I also saw un-prefixed versions, so I thought it's public
<img width="1055" alt="screen shot 2017-07-15 at 01 44 37" src="https://user-images.githubusercontent.com/1783732/28234380-3bb67e34-68ff-11e7-8ad6-f7895eb7a787.png">

**Comment by NinoSkopac** [comment]
What I am trying to achieve is display tooltip on mouse hover over the round slider. Do you have an idea on the top of your head how would you do it?

I can't even seem to listen to `mouseover` event, i.e. this does nothing

```
        $(document).on('mouseover', '.slider-handle', function() {
            console.log('mouseover');
        });
```

**Comment by seiyria** [comment]
Use the tooltip property, as specified earlier. You can see a demo on the
demo page.

**Comment by NinoSkopac** [comment]
> Use the tooltip property, as specified earlier. You can see a demo on the
demo page.

You mean example 8? I don't want to show it always, only on hover.

**Comment by seiyria** [comment]
Having tooltip set to show is the default behaviour and it should do what you want.

**Comment by NinoSkopac** [comment]
> Having tooltip set to show is the default behaviour and it should do what you want.

You're right, I'm sorry, I forgot the key part, **on mobile**. So, when I drag it on mobile, I want it to display the tooltip (which I thought was equivalent of hover on desktop, but was wrong).

**Comment by seiyria** [comment]
It does that on my phone. This behaviour should already happen.

**Comment by NinoSkopac** [comment]
> It does that on my phone. This behaviour should already happen.

I tried both in Chrome for Android and Chrome for iPad, it doesn't display the tooltip when I drag the slider, only after pressing somewhere on the horizontal line (sorry for the limited vocabulary, it's 2am here).

I recorded a video for you: https://photos.app.goo.gl/vZMeeAYlmdyWjGz62

**Comment by seiyria** [comment]
That's strange. If there isn't already an issue for that, feel free to open
one.

**Comment by NinoSkopac** [comment]
will do, thanks for your instant responses.
