### ISSUE TITLE
Increasing the length between the ticks

### ISSUE THREAD

**Issue by hanseller** [seiyria/bootstrap-slider#766]
First, thank you for the great effort for this slider.
I just have a question, how can i increase the length between between ticks.
If i have 6 options instead of the three shown in example 19 or 21, the words mixed one of another.
what is the solution for this, is there a property to add to solve it?
Thank you so much again for the great effort

**Comment by seiyria** [comment]
You'll need to make the slider wider, make the slider vertical, or put
expanded info in a tooltip. There's really not many viable solutions here.

**Comment by hanseller** [comment]
Thank you. my values are text not numbers as i am trying to make a survey using the slider.
