### ISSUE TITLE
Using arrow keys

### ISSUE THREAD

**Issue by sitdeveloper** [seiyria/bootstrap-slider#773]
When I set up a slider like this.

var slider = new Slider("#frm_demo_frm_demo_age", {
        value: document.getElementById('frm_demo_frm_demo_age').value,
	min: 0,
	max: 100
});

When using arrows key to move the slider the value can be out of range, -1 or 101.

**Comment by seiyria** [comment]
Please provide a jsfiddle or a replicable example.

**Comment by sitdeveloper** [comment]
Check this page :-)
- http://seiyria.com/bootstrap-slider/
- Example 1.
- Check the value of input (id=ex1). 
- When moving to right the value become 21 but max value is 20.
- When moving to left the value become -6 but min value is -5.

**Comment by jespirit** [comment]
This was addressed in #877. The values were being reported out of range in the `slideStart` event.
