### ISSUE TITLE
Problem before click

### ISSUE THREAD

**Issue by fturiot** [seiyria/bootstrap-slider#774]
Hello,
Before click on slider, i have probleme with position of ticks label (all in small space) and tick-tooltips not in good positions.
After click all is ok
How can i solve this ?
thanks for all

**Comment by seiyria** [comment]
Please provide an example of this.

**Comment by fturiot** [comment]
Before click
![selection_004](https://user-images.githubusercontent.com/3075612/29871715-21497076-8d8d-11e7-8ecb-a00e3efb3008.png)

After click
![selection_005](https://user-images.githubusercontent.com/3075612/29871714-2147e0bc-8d8d-11e7-9dcd-d7346a261553.png)

**Comment by fturiot** [comment]
And how can i keep color wen disable ?

**Comment by WouterDeketelaere** [comment]
I have exactly the same problem. You have to click on the slider before it is displayed correctly.
See pictures below:
Before clicking
![selection_140](https://user-images.githubusercontent.com/31070619/29875319-f2d3aaec-8d99-11e7-8f77-353795ec7256.png)
After clicking
![selection_141](https://user-images.githubusercontent.com/31070619/29875321-f49cf0ea-8d99-11e7-9433-3403234fa847.png)
I use bootstrap 3.3.7

**Comment by fturiot** [comment]
yes but i would like display correctly directly without click

**Comment by fturiot** [comment]
the problem that slider-tick-label have style width 0px
<div class="slider-tick-label" style="width: 0px;">100%</div>

**Comment by fturiot** [comment]
ok solve for me angularjs $timeout must be use .
But one point to solve have colors when disable 
thanks

**Comment by fturiot** [comment]
all solve
thanks

**Comment by prphntm63** [comment]
This may be because you are using tab or panel navigation with bootstrap, which sets 'hidden' panes by display:none which does not allow the slider to render on a hidden pane.

This solution seems to work for me:

https://stackoverflow.com/questions/17206631/why-are-bootstrap-tabs-displaying-tab-pane-divs-with-incorrect-widths-when-using
