### ISSUE TITLE
2 sliders are showing

### ISSUE THREAD

**Issue by YuriZakaria** [seiyria/bootstrap-slider#776]
The issue is that the slider is showing 2 times next to each other when I add the following code, one of them is functioning 100% and the other is disabled.

in the DOM explorer its showing 2 divs, the first one is without the id, and the second is with an id attached

**HTML:**
```
                  <input
                    type="text"
                    name="input"
                    id="gridSlider"
                    data-provide="slider"
                    data-slider-min="10"
                    data-slider-max="100"
                    data-slider-step="5"
                    data-slider-value="20">
```
**JS**
```
var gridSlider = $("#gridSlider").slider();
var gridSliderValue = parseInt(gridSlider.slider('getValue'));
```
![gridslider](https://user-images.githubusercontent.com/28672133/29935066-330115f4-8e86-11e7-819a-b0f0519eeb3a.png)

**Comment by seiyria** [comment]
You can't use data-provide and also initialize the slider with JS.

**Comment by YuriZakaria** [comment]
thanks for the fast reply, n sorry for disturbing once again,
I've replaced my codes with these, the data is passed but when I try to drag it on it doesn't work!
Is there any other initiation I am missing?
**HTML**
`<input id="gridSlider" type="text"/>`
**JS**
```
var gridSlider = $("#gridSlider").slider({
  id: 'gridSlider',
  min: 10,
  max: 100,
  step: 5,
  value: 20,
  enabled: true,
  tooltip: 'show',
  handle: 'square',
  rtl: 'auto',
});
```

sorry again, am new to dev.

**Comment by seiyria** [comment]
Please make a jsfiddle with your code.
