### ISSUE TITLE
Can we get color variables (utilizing the brand-primary variable) in the source SCSS/LESS files?

### ISSUE THREAD

**Issue by jmarikle** [seiyria/bootstrap-slider#778]
I'm using bootstrap-sass on my project and I noticed that after changing the `$brand-primary` variable in bootstrap, it didn't change the color for the slider handle.  Can we get the slider to use the bootstrap color variables and maybe get the other hardcoded colors like the grays into variables too?  I can create a pull request if you need.

**Comment by seiyria** [comment]
something like this would definitely require a pull request, however we do not have a hard dependency on bootstrap, just a soft one, so it might just be easier to change the color of the slider to match.
