### ISSUE TITLE
Slider tooltip always shown

### ISSUE THREAD

**Issue by Chestroled** [seiyria/bootstrap-slider#787]
Hello, 

trying to include this great plugin in an interface but facing a problem.
I'm really not professional so I will do my best to explain the problem and hope to have some help.

Using the template SB admin based on Bootstrap 4 => https://github.com/BlackrockDigital/startbootstrap-sb-admin

Simply invoke a slider by this way : 

HTML `<input type="text" id="ex7" data-slider-enabled="false" data-slider-max="20" data-slider-min="0" data-slider-step="1" data-slider-value="5">`

JS `    $("#ex7").slider({
                    });
                    $("#ex7-enabled").click(function() {
                      if(this.checked) {
                        $("#ex7").slider("enable");
                      }
                      else {
                        $("#ex7").slider("disable");
                      }
                    });`
All working well except the tooltip is always show as picture : 

![bootstrapslider](https://user-images.githubusercontent.com/4404704/31583317-949bc8aa-b199-11e7-848d-a270ecae017e.jpg)

Can't find what's going bad, I've checked the console, when I put cursor on the slider the class change from `tooltip tooltip-main top` to `tooltip tooltip-main top.in`
maybe it's an "opacity" conflict ?

If anyone tell me how to investigate deeper ? 

Many thanks

**Comment by seiyria** [comment]
Can you provide a jsfiddle that replicates this issue? If not, I'd hazard a guess that the CSS included with that theme is messing with things.

**Comment by Chestroled** [comment]
Hey Seiyria, thanks for your quick reply ! 

Not been so familiar with JSfiddle but seems to have replicated the bug.

Please found it here : https://jsfiddle.net/eh91qbv4/1/

Hope is simply as CSS bug, but can't find where... Also, I have seen a tooltip overlap the navigation bar beacause of a bad "z-index"

Thanks for your help !

**Comment by seiyria** [comment]
At a glance, we do not support bootstrap 4. Check #689 and if that's of interest please feel free to send a PR.
