### ISSUE TITLE
Gulp build

### ISSUE THREAD

**Issue by armpogart** [seiyria/bootstrap-slider#790]
Any plans (or would you accept PR) to migrate to gulp build instead of grunt? It will make contributions easier as more people use it nowadays.

Some other advantages of gulp over grunt:
- Gulp is speedier (as it uses streams and can process several tasks at the same time)
- Gulp is easier to read (code vs configuration)
- Gulp community is more active (stats from github repo)

Another option would be to go with webpack, but I'm not sure that it will make things easier.

**Comment by seiyria** [comment]
I understand the differences between the two, but there is literally no reason to change.

**Comment by armpogart** [comment]
The only difference that is relevant for open source project is the one I mentioned first - more people know it, more people use it, so more people can contribute easier.

**Comment by seiyria** [comment]
That's actually entirely untrue. It doesn't matter if you know what my build system is, you only need to know what commands to run to test it. There should be no reason for you to care about the inner workings of the build system if you're contributing to the project. In the case of this project specifically, it is fairly "complete" in regards to the build system so there should be no need for any contributors to change it, either.
