### ISSUE TITLE
Help to change the design - CSS

### ISSUE THREAD

**Issue by Florianp123** [seiyria/bootstrap-slider#795]
Hello guy,

I love this slider. I have check all your example but it was wondering if it is possible to change the style so it looks like this :
<img width="737" alt="capture d ecran 2017-10-30 11 50 53" src="https://user-images.githubusercontent.com/12236580/32179658-4301fd2c-bd90-11e7-9b13-bb51f4796adb.png">

If you can provide me some guidlines on how to change the style it could be great.

thanks in advance !

Florian

**Comment by seiyria** [comment]
Yes, you can do that, or at least some of it. Just look into lowering the width/height of the ticks, changing the opacity of the tracks, etc.

**Comment by Florianp123** [comment]
thanks for you feedback. it helps. i have manage to change the style of the ticks but i would like the slider bar to be above the ticks. How can i achieve this ?

thanks in advance for your help.

**Comment by seiyria** [comment]
Above it, vertically? Or on top? The former you would change it's position,
the latter you'd change zlayer
