### ISSUE TITLE
Meteor prints jQuery missing warning

### ISSUE THREAD

**Issue by avanthay** [seiyria/bootstrap-slider#796]
I'm using this awesome slider for a project based on Meteor. Since I use ReactJS in the frontend, I do not use this package directly, I got it as a dependency from this [ReactJS wrapper provided by brownieboy](https://github.com/brownieboy/react-bootstrap-slider). Moreover I use bootstrap-slider without jQuery, since I don't need jQuery for my project.

Meteor does some static code analysis for its own package bundling logic (Meteor has an own package system) which locates every `require(<string literal>)` in the code. When using bootstrap-slider without jQuery, Meteor prints a warning about being unable to locate jQuery. With static analysis, there is no real way of investigating if a package is really required or not, without executing the code itself. As @benjamn described [here](https://github.com/meteor/meteor/issues/8768#issuecomment-306962795), the best way to get around this problem is to require a dynamic value containing the string literal instead of having the string directly as argument of the `require` function for optional packages.

That why, I would like to adapt bootstrap-slider as follow:

from

```js
try {
  require("jquery");
}
```
to 

```js
try {
  var jQueryPackage = "jquery";
  require(jQueryPackage);
}
```

Let me provide you with a merge request containing the change.

**Comment by seiyria** [comment]
I'm not sure why it's trying to statically analyze something in an if/elseif, that seems like it would break for literally every other package that supports AMD. I'm skeptical about your patch, since it seems like:

- it would have to be sent to every other package that supports optional AMD deps
- static analysis shouldn't have a very tough time differentiating `require('jquery')` from `x='jquery';require(x)`

**Comment by avanthay** [comment]
I agree on that it's not fixing the "real" problem, but technically my dynamic value solution shouldn't make a difference.

Let me correct this: Meteor don't realise when a statement is in if/else statement, it just statically collects all packages required and checks if they are installed. As I don't have jQuery on my project, I get the warning message. On the other side, Meteor will not resolve dynamic values during its static analysis, thats why my proposed change makes the difference.

I searched for AMD packages with optional dependencies without success. I'm wondering how other packages may implement optional dependencies, maybe there is an other way of doing it, which will work with Meteor, I don't know. We have have many dependent packages in the project I'm working on, but they all don't have optional dependencies. Do you have some samples of such packages?

**Comment by seiyria** [comment]
No, I haven't used meteor in years. I looked around but didn't find
anything in an issue tracker or otherwise. It may be worth opening an issue
there to see if this is a more widespread issue.

**Comment by avanthay** [comment]
I finally managed to find [the boilerplate](https://github.com/desandro/jquery-bridget) `bootstrap-slider` is build on. It seems, they must be more npm packages building on it.

I just opened [this issue](https://github.com/meteor/meteor/issues/9285) at the Meteor repository. I think, it make sense to resolve the issue at its root.

**Comment by avanthay** [comment]
I just moved [the existing issue](https://github.com/meteor/meteor/issues/9285) to [a feature request](https://github.com/meteor/meteor-feature-requests/issues/228) at meteor.

Let me close this issue, since the fix has to be done on the meteor side.
