### ISSUE TITLE
is this compatible with Bootstrap 4 already?

### ISSUE THREAD

**Issue by skeith69** [seiyria/bootstrap-slider#800]
Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [ ] Instructions to replicate the bug in the Fiddle

I'm wandering if this is already compatible with BS4?

if not, does anyone know how to make it compatible with BS4? cause I think its a really plugin

**Comment by seiyria** [comment]
If you'd read the issue template, you would have searched through the issue list and found [this](https://github.com/seiyria/bootstrap-slider/issues/689).
