### ISSUE TITLE
Angular 4 - Bootstrap slider

### ISSUE THREAD

**Issue by babupca** [seiyria/bootstrap-slider#801]
Hi Kyle,
I'm using this plugin in the angular 4 application, where i have a difficulty in one scenario. 

Dynamically i'm setting High, Medium, and low as a three range and setting the id also dynamically, from the angular 4 typescript http service. This service returns an array, from this array i get the range value high, medium, low as range value and set in the slider.

Now when the user click the slider, the user should open a bootstrap modal window, where user should capture current range selected, select some date(from bootstrap slider), and text-area (which contains the summary) and finally i should submit it.

But problem i could not able trigger a click on the slider with a dynamic id, which i have appended in the input field and get the selected range. 

I could not able to figure out how to do this scenario.  Please help require.

Thank You.

**Comment by seiyria** [comment]
Please add a jsfiddle with your attempt thus far.

**Comment by babupca** [comment]
Hi Kyle,

I'm Sorry still i could not able to share the code in jsfiddle, . But i will definitely share the code.

But if possible  please tell me the some idea, how to access the event with in the slider

I still don't know how to capture the event with in the angular 4, when i click on the slider.  So for that what i did was i added this jquery $.fn.initValueDriverPage() and i called with in the typescript file. so when ever i click the slider, the slider with slider stop event will trigger. But this is creating lot of problems for me.

If you can tell me how to capture the event on click of the slider with the typescript file, it will easy for me proceed further.

I have many slider, displayed (PFA), so when i click any of the focus, point i should able get the event details

     ```
<input id="{{item.focusId}}" 
                                #{{item.focusId}}
                                type="text"  
                                data-slider-min="0" 
                                data-slider-max="10" 
                                data-slider-step="1" 
                                data-slider-value="0" 
                                [attr.data-budgetdate]="item.focusEta"
                                [attr.data-budget]="item.focusBudget"
                                [attr.data-details]="item.focusDetails"
                                [attr.data-fname]="item.id.focusName"
                               
                                />  
```

![value-details](https://user-images.githubusercontent.com/2504343/34487928-6a103750-effc-11e7-9c49-6662c1337512.png)




```
getSliderRefresh(opportunityObj: any) {
    setTimeout(() => {   
      opportunityObj.forEach(data => {
        var setvalue = 0;
        if (data.focusPriority === "High") {
          var setvalue = 8;
        } else if (data.focusPriority === "Medium") {
          var setvalue = 5;
        } else if (data.focusPriority === "Low") {
          var setvalue = 2;
        } else {
          if (data.focusPriority === "None") {
           // var setvalue = 0;
            var setvalue = 2;
          }
        }
        $("#" + data.focusId).slider({
          handle: "square",
          tooltip: "hide",
          disable: true,
          id:"slider-"+data.focusId,
          reversed: true,//revering the value, since high, low, medium are not correct with the sliding values.
          max: 10,
          value: setvalue
        });
      });

    }, 100);
    $.getScript("/assets/scripts/value-driver.js").done(function (script, textStatus) {
      console.log("Value driver script initialized!...");
      $("div#page-value-driver").initValueDriverPage();
    });
  }
```



```
(function ($) {

  $.fn.initValueDriverPage = function () {
  
    // init sliders in focus table
    (function (head) {
   
      head.find(".focus-slider-wrapper input[type=text]").each(function () {
        var slider = $(this);
      
        slider.on("slideStop", function (e) {
       
         console.log("e.target.id-----",e.target.id);
         console.log(" e.target", e.target.dataset);
          var val = e.value;
          var id = e.target.id;
          var prorityVal = e.target.val;
          var sliderValue = "";
          
          console.log(val, id, prorityVal)
          if (val >= 7) {
            slider.slider("setValue", 8);
            sliderValue = "High";
          } else if (val > 3 && val <= 6) {
            slider.slider("setValue", 5);
            sliderValue = "Medium";
          } else if (val >= 0 && val <= 3) {
            slider.slider("setValue", 2);
            sliderValue = "Low";
          }else {            
            sliderValue = "None";
          }
        
          $("#modal-focus-details").find("message-heading").html("");
          //Show the modal
          $("#modal-focus-details").on("shown.bs.modal", function () {
            currentSelectedSlider = id;

        
              $(this).find(".message-heading").html(e.target.dataset.fname);
             
                if(e.target.dataset.budgetdate != " "){
                  $(this).find("#budgetdate").val("");
                  if(e.target.dataset.budgetdate != undefined){
                  
                    var getFormattedDate = dateFormat(e.target.dataset.budgetdate, 'mdy', '-');
                    $(this).find("#budgetdate").val(getFormattedDate);
                  }
                }
                if(e.target.dataset.budget !== " "){
                  // console.log("budget line 55",e.target.dataset.budget);
                  $(this).find("#budgedVal").val("");
                  if(e.target.dataset.budget != undefined && e.target.dataset.budget != 0){
                    console.log("budget line 57",e.target.dataset.budget);
                    $(this).find("#budgedVal").val("");
                  $(this).find("#budgedVal").val(e.target.dataset.budget);
                  }
                }
                $(this).find("#otherdetails").val('');
                $(this).find("#focusttcontent").val('');
                if(e.target.dataset.details !== "" || e.target.dataset.details != undefined){   
                    $(this).find("#otherdetails").val(e.target.dataset.details);          
                    $(this).find("#focusttcontent").val(e.target.dataset.details);         
                         
                }

                $(".input-eta .selSlider").val(currentSelectedSlider);
                $(".input-eta .fpriority").val(sliderValue);
          }).modal({ show: true });

          //hide the modal
          $('#modal-focus-details').on("hidden.bs.modal", function () {
              console.log(" e.target.dataset", e.target.dataset);
              e.target.dataset = {};
              $("input").val('');
              $("textarea").val('');
          });

        });
     

      });


    })($(this).find("#main-content .focus-table"));
  };
})(jQuery);
  

function dateFormat(date, format, separator) {
  var date = new Date(date);
  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();
  var dateObject = {
    d: day,
    m: month,
    y: year
  };
  var formatArr = format.split("");
  return dateObject[formatArr[0]] + separator + dateObject[formatArr[1]] + separator + dateObject[formatArr[2]];
}
```

**Comment by seiyria** [comment]
There is way too much code there for me to consider this a minimal test case.

**Comment by babupca** [comment]
Sorry Kyle

Can you give me some idea, like how to attach an event in the input field, or if you have any other solution i can follow that.

> <input id="{{item.focusId}}" 
>                                #{{item.focusId}}
>                                type="text"  
>                                data-slider-min="0" 
>                                data-slider-max="10" 
>                                data-slider-step="1" 
>                                data-slider-value="0" 
>                                [attr.data-budgetdate]="item.focusEta"
>                                [attr.data-budget]="item.focusBudget"
>                                [attr.data-details]="item.focusDetails"
>                                [attr.data-fname]="item.id.focusName"
>                                **(change)="onChange($event.target.value)"**                              
> /> 

**Typescript File**

> onChange(event){
**> console.log(event.target.dataset);**
> }

So with this, i can access the target dataset and send the form data to the Save API Service.

Thanks
Babu

**Comment by seiyria** [comment]
`event.target.dataset` should always be undefined, because event.target is an HTMLElement, which will have an `event.target.value`, not a `dataset`.
