### ISSUE TITLE
Can I replicate tooltips without Bootstrap and jQuery?

### ISSUE THREAD

**Issue by NinoSkopac** [seiyria/bootstrap-slider#802]
Howdy, thank you for the great plugin. I've been using it on my site (https://read2me.online/) for a few months now.

I'm building an HTML player with the plugin and since it's going to be a redistributable (i.e. a widget), I really don't wanna have dependencies like jQuery and Bootstrap, not just because they require additional network requests, but also because people using the widget could end up having dependency version conflicts.

So what I did was a bit silly - I simply removed BS/jQ, and the slider still works - great. 
However, I also had to disable tooltips to avoid UI issues. 

Can I somehow still have tooltips?

**Comment by seiyria** [comment]
Since we have a dependency on bootstrap, this is not possible. Code here: https://github.com/seiyria/bootstrap-slider/blob/master/src/less/bootstrap-slider.less

If you want to remove bootstrap, just copy the relevant CSS.

**Comment by NinoSkopac** [comment]
> If you want to remove bootstrap, just copy the relevant CSS.

By relevant, do you mean tooltip-related code? And I should copy it from Bootstrap, is that the idea?

**Comment by seiyria** [comment]
Yes,

**Comment by NinoSkopac** [comment]
Thank you for the advice, seems promising.
