### ISSUE TITLE
rangeHighlights not showing

### ISSUE THREAD

**Issue by interludic** [seiyria/bootstrap-slider#803]
Hi Guys,

I am new to bootstrap-slider, i have everything working except the rangeHighlights 

please advise...

https://stackoverflow.com/questions/47402564/rangehighlights-not-showing-with-bootstrap-slider

Harry

**Comment by xakzona** [comment]
https://github.com/seiyria/bootstrap-slider/issues/676

**Comment by jespirit** [comment]
Seems to work fine. Closing.
