### ISSUE TITLE
Setup for angular 4

### ISSUE THREAD

**Issue by Quentinvk** [seiyria/bootstrap-slider#804]
Hi, 

I'm very new to Angular 4, and wanted to use your sliders for a personal project. 
But I'm stuck because "Slider" isn't recognized.  (Error : "Cannot find name 'Slider'" )

I installed bootstrap 4 and your package.
From the basic setup chapter I understood "grab" as in putting them in angular-cli.json. (after I installed bootstrap)
Is there something I'm missing? 

Please don't hate me for my ignorance. 
Your help is much appreciated.

Quentin

**Comment by seiyria** [comment]
All you should have to do is `import * as Slider from bootstrap-slider` after installing it via npm.

**Comment by Quentinvk** [comment]
Thank you!
