### ISSUE TITLE
How can I reset the values of the range slider ?

### ISSUE THREAD

**Issue by ShaheryarAbid** [seiyria/bootstrap-slider#805]
Hi there,

I hope you shall be fine. My name is Shaheryar Abid. I am using your slider on my project. I am using the example 2 of your demos. The range slider. Now I have created a link and on click I am running a function that will reset the range slider's values. But I can not figure it out how to reset the values on the range slider. 
Here is my jsfiddle code.
https://jsfiddle.net/ShaheryarAbid/rw5ubgno/1/

**Comment by seiyria** [comment]
[There is no reset function in the api](https://github.com/seiyria/bootstrap-slider#functions), so you just have to do a setValue with an array.
