### ISSUE TITLE
Slider appears as textbox on iPad and Windows mobile

### ISSUE THREAD

**Issue by studiorobl** [seiyria/bootstrap-slider#808]
On iPad mini 3 and Windows mobile the slider appears as a textbox.

In the console I get the error 'bootstrap-slider.js:477 SyntaxError: Unexpected identifier 'j'. Expected either 'in' or 'of' in enumeration syntax.'

**Comment by studiorobl** [comment]
I found a fix: I ran the bootstrap-slider.js through http://babeljs.io/ which stripped out the backticks and other things that were causing issues in older browsers.

**Comment by seiyria** [comment]
Uhhh... you're not supposed to use the version in `src`. There is a pre-compiled `dist` available to you.

**Comment by studiorobl** [comment]
Huh, I didn't realise I had! Thanks.
