### ISSUE TITLE
To copy the code of example 13 directly, why not come into effect(Novice)

### ISSUE THREAD

**Issue by 489405826** [seiyria/bootstrap-slider#809]
I see example thirteen for my needs is direct copy of the code to think that it will be directly used, the result is the following effect.

![image](https://user-images.githubusercontent.com/10294125/34594212-b00bfbe4-f20a-11e7-9800-bff64e1996d9.png)
![image](https://user-images.githubusercontent.com/10294125/34594223-c0e821ea-f20a-11e7-919b-3dc33f78eb35.png)

**Comment by seiyria** [comment]
What is different from the example exactly?

**Comment by 489405826** [comment]
![image](https://user-images.githubusercontent.com/10294125/34598020-4a6a5054-f225-11e7-84de-090b96de98dc.png)
This is the example of the example. There are several label in the example, and I don't have any of them.

**Comment by seiyria** [comment]
ok, well if the example works but your code doesn't you'll have to make a jsfiddle.

**Comment by 489405826** [comment]
I found the problem, the question of the JS file I quoted！
