### ISSUE TITLE
Separator for values when using single tooltip text

### ISSUE THREAD

**Issue by juanpablob** [seiyria/bootstrap-slider#811]
Hi! I couldn't find an option to configure the separator of min and max when using `tooltip_split: false`… I'm trying to display money range but it turns out that the separator is a comma with no space, just like this: `13000,20000` so after using the `formatter()` the tooltip text looks like this: **$13.000,$20.000** and I'd like something like this **$13.000 — $20.000**, does anyone has any workaround for this?

Cheers!

**Comment by ishegg** [comment]
You need to use the `value` parameter when it's an array, then you can join the values however you want:

```javascript
formatter: function(value) {					
    if (!Array.isArray(value)) {
        return;
    }

    return value[0] + " ---- " + value[1];
}
```

**Comment by juanpablob** [comment]
👏 👏
