### ISSUE TITLE
[question] How to detect when the slider is released and has a different value

### ISSUE THREAD

**Issue by jamesqo** [seiyria/bootstrap-slider#812]
After the slider is clicked, dragged to a different value, and released, I want to fire a JS handler. I tried using the `mouseup` event, like this:

```html
                <input id="csharpLangVersion"
                       type="text"
                       data-provide="slider"
                       data-slider-id="csharpLangVersionSlider"
                       data-slider-min="0"
                       data-slider-max="9"
                       data-slider-value="5"
                       data-slider-tooltip="hide"
                       onmouseup="onOptionValueChanged();" />
```

but it doesn't seem to be working. Are there APIs for dealing with this?

**Comment by seiyria** [comment]
Use [the provided events](https://github.com/seiyria/bootstrap-slider#events).

**Comment by jamesqo** [comment]
@seiyria Damn, that was an impressive response time. Thanks!

**Comment by alisson04** [comment]
Muito obrigado, não estava conseguindo resolver ;)
