### ISSUE TITLE
Display tooltip hovering on tooltip area

### ISSUE THREAD

**Issue by ZecaoLuKolmostar** [seiyria/bootstrap-slider#814]
In [Example 1](http://seiyria.com/bootstrap-slider/), when the tooltip is hidden, I move my mouse on the area of tooltip, the tooltip would appear, but it should not. 

Sometimes it will cause inconvenience. For example, there are a button on the top of the slider, and I cannot click the button because the tooltip hide it. 

So can I disable it?

**Comment by seiyria** [comment]
You could try messing around with CSS, but my gut inclination is that no, you cannot. Use margins to make your button farther away from the tooltip.

**Comment by ffont** [comment]
`pointer-events:none` for the `tooltip` CSS class worked perfectly. Thanks @sainagendra!
