### ISSUE TITLE
Slider not 100% of container

### ISSUE THREAD

**Issue by MrNorth35** [seiyria/bootstrap-slider#815]
Hi!

This slider control is awesome. There is one issue I have not been able to solve.

When putting in into a simple bootstrap 3 column, the slider control is not adapting to the full width of the column.

Example:

` <div class="row">
                        <div class="form-group form-group-sm">
                            <div class="col-sm-4">
                               Select a value:
                            </div>
                            <div class="col-sm-7">
                                <input id="ex6" type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="0" />
                            </div>
                            <div class="col-sm-1">
                                <strong><span id="ex6SliderVal">@Model.TickerCount</span></strong>
                            </div>
                        </div>
                    </div>          `

The above code is copied from the example page, and seems to work nicely, but for some reason the slider get a fixed width of 210px, even if the column is more than double that size. We need it to be responsive in width, so when changing the window size, teh slider should match the bootstrap column width.

**Comment by seiyria** [comment]
You have to use CSS to make it stretch I think.
