### ISSUE TITLE
WARNING: $.fn.slider namespace is already bound.

### ISSUE THREAD

**Issue by hezanathos** [seiyria/bootstrap-slider#818]
Hi,

I'm using JqueryUi in my project and i'm getting this warning :
`bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.`

I perfectly understand why its there, and i have no problem with my slider, i'm properly calling $.fn.bootstrapSlider.

I'm not using JqueryUi Slider.

I understand warning developers about this is important. But when you are aware of that this warning is a problem. I don't want any warning on my application :-).

I can't remove the JqueryUi dependency from my project, nor can I remove the widget part ( i'm using yarn to manage my dependencies )

I can work on a PR if you say what you want to do about this. Just remove the warning or something better...

**Comment by seiyria** [comment]
I think we want to keep this. There are a lot of issues for people not figuring it out, we don't want more of those.

**Comment by hezanathos** [comment]
Would it be possible to disable this on demand ? I understand this problem but i don't think disturbing all users for some confused user is a good idea.

**Comment by seiyria** [comment]
if you're not using `$.fn.slider` then set it to null and the warning will go away.

**Comment by hezanathos** [comment]
@seiyria did you see my message ? What do you think ?

**Comment by seiyria** [comment]
It sounds like you want a very environment specific thing. I'm not inclined to believe it's for the greater good. You're welcome to take it out in a fork but I think this is a "disturbance" worth having.

**Comment by hezanathos** [comment]
This fiddle is not environment specific :-(. I think none of your user likes having this warning, they just don't take the time to write an issue. The solution you mentioned is not working ( for anyone ). I'm disappointed.

**Comment by seiyria** [comment]
You could very easily do this:

```
<script src="jqueryui.js">
<script>$.fn.slider = null</script>
<script src="bootstrap-slider.js">
```

**Comment by seiyria** [comment]
Anyway, as with everything that exists, when you use two libraries that conflict with each other, there is no guarantee of compatibility, and that's what warnings are for. If the warning wasn't there, we'd get plenty of issues for people saying "$.fn.slider isn't working!!! why???" and that's frankly worse. At least people can use the library this way.

As I said earlier, you're welcome to fork it to remove the warning if that suits you better.
