### ISSUE TITLE
error Uncaught TypeError: Cannot read property 'on' of undefined using jquery-3.3.1.min.js

### ISSUE THREAD

**Issue by alhavizd** [seiyria/bootstrap-slider#821]
error Uncaught TypeError: Cannot read property 'on' of undefined using jquery-3.3.1.min.js
![image](https://user-images.githubusercontent.com/23514820/37238501-123d8c5c-245a-11e8-9c58-613febbc6cbd.png)

**Comment by seiyria** [comment]
going to need a jsfiddle for this.

**Comment by coma0815** [comment]
I had the same problem but then realised, that my slider was dynamically generated after document ready. So the event listener did throw the same error as you had because the slider-element hasn't been created yet. Also using jquery-3.3.1. Maybe that helps..

**Comment by alhavizd** [comment]
you can try like this

![image](https://user-images.githubusercontent.com/23514820/40694149-539f877a-63e5-11e8-80c8-14e25df56f18.png)

**Comment by coma0815** [comment]
Thank you - I solved my problem by adding the event listeners when I add the slider-element. Did you manage to solve your problem?
