### ISSUE TITLE
add next , prev button 

### ISSUE THREAD

**Issue by bahrammzm** [seiyria/bootstrap-slider#822]
is it possible to add Next and Prev buttons to slider? How can i do that ?

**Comment by seiyria** [comment]
Yes. Make two buttons that either set the slider to value plus one or minus one. You can use the setValue function for this.

**Comment by bahrammzm** [comment]
how would be if value is not numeric value ? for example timestamp

**Comment by seiyria** [comment]
The value is always numeric, you just display it differently depending on
what it is, using the formatter function.
