### ISSUE TITLE
Modifying value before _mouseup is called will cause _mouseup passing the wrong value to callbacks

### ISSUE THREAD

**Issue by purpose233** [seiyria/bootstrap-slider#824]
If user sets the value before the ```_mouseup``` function is called,  ```_mouseup``` function will pass the modified value to user's callback function instead of the real value when ```mouseup``` event happened.
This problem happens in specific situation, like using slider to control video player which frequently calls ```setValue``` function. 
Calculating the value by event like what ```_mousedown``` and ```_mousemove``` do might be fine.

**Comment by seiyria** [comment]
We'd accept a PR to change this behavior!
