### ISSUE TITLE
Mobile > Current Slider Value not updated on tap

### ISSUE THREAD

**Issue by shanebp** [seiyria/bootstrap-slider#830]
Thank you for this plugin.  Works great, except... 

On mobile, tested on Galaxy phone, Example 6 on this page: 
http://seiyria.com/bootstrap-slider/

The slider tooltip shows the value change when the slider position is changed with a tap. 
But the text value for the span does not update when the slider is tapped. 
The text value for the span only updates if the slider is dragged.

**Comment by seiyria** [comment]
That's because it uses the `slide` event. Check using the `change` event instead.
