### ISSUE TITLE
Slider in webView Android

### ISSUE THREAD

**Issue by neotic82** [seiyria/bootstrap-slider#834]
Hello,

I am integrating the slider in an android webview but I can not load the slider correctly, only the input is left for you to set the value. 
Has anyone else had this problem? I've tried it with android API versions 25/27 and not working, but in version 23 work perfectly. 

I do not understand anything :/

**Comment by seiyria** [comment]
You'll need to create a jsfiddle for this. There is no reason for it to not work, so it sounds like you're getting an error.
