### ISSUE TITLE
Hiding the tooltip doesn't seem to work

### ISSUE THREAD

**Issue by euoia** [seiyria/bootstrap-slider#847]
From the documentation it sounds like it should be possible to hide the tooltip with `slider.setAttribute('tooltip', 'hide')` but this doesn't seem to be working for me.

I would like the tooltip to be hidden when the slider is disabled.

Here's a JSFiddle: https://jsfiddle.net/qhe1m9cf/7/

**Comment by jespirit** [comment]
You have to call `slider.refresh()` after setting the new option(s), which will construct a new Slider object using any new options you've set.

JSFiddle (forked): https://jsfiddle.net/1xbLnwra/
