### ISSUE TITLE
SSL error and redirect error on demo

### ISSUE THREAD

**Issue by jywarren** [seiyria/bootstrap-slider#848]
Hi, I tried opening the demo linked to from the GitHub header, and got an SSL warning -- then when i bypassed it (chrome) I got a "too many redirects" error. 

Looks like a great library - thank you! 

Link in question: http://seiyria.github.io/bootstrap-slider/

**Comment by seiyria** [comment]
this should hopefully be resolved now. githubs "force ssl" doesn't seem to work as expected in some cases.

**Comment by jywarren** [comment]
OK, thanks!
