### ISSUE TITLE
How to set max value?

### ISSUE THREAD

**Issue by ethemkizil** [seiyria/bootstrap-slider#851]
How to set max value without attribute?

**Comment by seiyria** [comment]
You have to use `slider.setAttribute()`.

**Comment by ethemkizil** [comment]
setAttribute not work 
------------------
var slider2 = $("#perPost_slider").bootstrapSlider({
    	id: "perPost_slider",
    	tooltip: 'always',
    	formatter: function(value) {
    		return 'Miktarı: ' + value.toLocaleString();
    	},
	});
    
    $("#perPost_slider").on("slide", function(slideEvt) {
    	$("#perPost").val(slideEvt.value);
    })

    $('#perPost').on('input',function(e){
    	slider2.bootstrapSlider('setValue', $(this).val());
    });
	    
    var slider = $("#quantity_slider").bootstrapSlider({
    	id: "quantity_slider",
    	tooltip: 'always',
    	formatter: function(value) {
    		return 'Sipariş Miktarı: ' + value.toLocaleString();
    	},
	});
    
    $("#quantity_slider").on("slide", function(slideEvt) {
    	$("#order_quantity").text(slideEvt.value.toLocaleString());
    	$("#quantity").val(slideEvt.value);
    	slider2.bootstrapSlider('setAttribute', 'value', slideEvt.value);
    })

    $('#quantity').on('input',function(e){
    	slider.bootstrapSlider('setValue', $(this).val());
    	slider2.bootstrapSlider('setAttribute', 'value', 1000);
    });
