### ISSUE TITLE
Disable click/change on slider

### ISSUE THREAD

**Issue by millykat** [seiyria/bootstrap-slider#855]
Hello,
I need to disable the click option on the range bar.
I would like the user to be allowed only to slide/drag the mouse in the range bar and not to click on it.
How can I acieve this? 
Thank you

**Comment by seiyria** [comment]
You could use CSS to set the track to `pointer-events: none`.

**Comment by millykat** [comment]
Thank you for the soon reply.
I added this in the .slider-track class all the related track classes but click still works.
And if add it in the .slider class neither slide neither click is working.

You mean some other way?

**Comment by Sentence** [comment]
+1
