### ISSUE TITLE
Click track to advance value +/- 1

### ISSUE THREAD

**Issue by capegreg** [seiyria/bootstrap-slider#857]
First off, this is a fine control that works and looks very good on my site. For my question, and this may be an enhancement request or maybe there is a solution. The motivation for this question is due to the sensitivity of the slider when the track width is very small. I am using the slider to choose days of the year 1 - 365. Basically, the day is used to perform a calculation...anyway, it is very difficult to narrow down to single digits when sliding, e.g., stopping on 17 often skips past it by 5 or more values in either direction making it frustrating to stop on the value you want. I want to allow the track to be clicked on the track both before the handle and after which would allow a single tick to advance the handle. So, if the user stops on 14 because they can't land on 17, they can just single click three times to advance to 17. I am already using the change\slide\sliderStop events to retrieve values when sliding, but this is very different. Thanks.

**Comment by seiyria** [comment]
For this feature, you'd be better off implementing buttons on either side to increment/decrement.

**Comment by capegreg** [comment]
I have no room for the buttons. I may have to swap out for a number spinner. Thanks.
