### ISSUE TITLE
single ticks array not work?

### ISSUE THREAD

**Issue by djmisterjon** [seiyria/bootstrap-slider#861]
it possible to add a single ticks data?
On my side it not work, it work only with multi ticks?
i want to allow my slider to **ticks** when near to the default value.
```javascript
     // create multi sliders light falloff for Coefficient light attenuation
    function create_sliderFallOff(dataValues){
        function upd() { this.asignValues(dataValues, false) };
        const Kc = new Slider("#Kc", { tooltip: 'always', ticks: [0.75], ticks_snap_bounds: 0.1, ticks_labels: ['0.75']});
        const Kl = new Slider("#Kl", { tooltip: 'always'});
        const Kq = new Slider("#Kq", { tooltip: 'always'});
        
        Kc.tooltip.style.opacity = 1, Kl.tooltip.style.opacity = 1, Kq.tooltip.style.opacity = 1;
        Kc.on("slide", (function(value) { dataValues.falloff[0] = value; upd.call(this) }).bind(this));
        Kl.on("slide", (function(value) { dataValues.falloff[1] = value; upd.call(this) }).bind(this));
        Kq.on("slide", (function(value) { dataValues.falloff[2] = value; upd.call(this) }).bind(this));
    };
```

as you can see the slider freeze to 0.75 and cannot move!
![image](https://user-images.githubusercontent.com/24865815/46241172-1d53dc00-c382-11e8-81ff-ea28cacc31d0.png)

thanks guys

**Comment by seiyria** [comment]
Please provide a jsfiddle

**Comment by djmisterjon** [comment]
@seiyria sure, here and thanks for help
https://jsfiddle.net/jonforum/1pkzj92a/8/

**Comment by djmisterjon** [comment]
hum, i think a found a easy way.
i can maybe add 3 ticks, and with `document.querySelectorAll(`#slider-tick`);`
add attribute display none to index array 0 and length-1;
![image](https://user-images.githubusercontent.com/24865815/46241641-0d8cc580-c38b-11e8-8547-a5b0102b445e.png)

If you don't have alternative , i will proceed with this way.
The start and end will tiked , i dont want , but it will be ok if you don't have solution.
![image](https://user-images.githubusercontent.com/24865815/46241718-dcf95b80-c38b-11e8-9f91-60b8f297085c.png)

**Comment by seiyria** [comment]
That was going to be similar to my recommendation. What you want isn't possible currently. Glad we came to the same conclusion!
