### ISSUE TITLE
data-slider-rangehighlights="[{start: 0, end: 100}]"

### ISSUE THREAD

**Issue by Fenny** [seiyria/bootstrap-slider#890]
``
<input type="text" data-slider-min="0" data-slider-max="200" data-slider-tooltip="show" data-slider-tooltip-position="bottom" data-slider-rangehighlights="[{start: 0, end: 100}]">``

rangehighlights not working

**Comment by Fenny** [comment]
https://jsfiddle.net/zeuwgcLy/

No highlight to be found :|

**Comment by seiyria** [comment]
You need to assign a class and style it with CSS, per this example: http://seiyria.com/bootstrap-slider/#example-22

**Comment by Fenny** [comment]
Nope, doesn't work what you suggested. Because even in the example it has objects without class.

If you look in the sourcecode you see that is should assign the default class on line 474

``
/* Create highlight range elements */
        this.rangeHighlightElements = [];
        var rangeHighlightsOpts = this.options.rangeHighlights;
        if (Array.isArray(rangeHighlightsOpts) && rangeHighlightsOpts.length > 0) {
          for (var j = 0; j < rangeHighlightsOpts.length; j++) {
            var rangeHighlightElement = document.createElement("div");
            var customClassString = rangeHighlightsOpts[j].class || "";
            rangeHighlightElement.className = "slider-rangeHighlight slider-selection " + customClassString;
            this.rangeHighlightElements.push(rangeHighlightElement);
            sliderTrack.appendChild(rangeHighlightElement);
          }
        }
``javascript

Even if I assign a class, it doesn't work
https://jsfiddle.net/zeuwgcLy/5/

**Comment by seiyria** [comment]
It seems like it works if you add it in there like so: 
https://jsfiddle.net/zeuwgcLy/4/

I'm not sure why it works on the example page

**Comment by Fenny** [comment]
Weird :|

**Comment by jespirit** [comment]
> Weird :| maybe because the code has issues parsing the data-attribute array?

Right on the money. The `data-slider-rangeHighlights` attribute should be parsed as an array, but it's being treated as a string instead. See image below.

I will look into it.

![issue-890-rangehighlights](https://user-images.githubusercontent.com/5477929/49825797-4960e580-fd53-11e8-9553-0b9335ce3f7d.png)

```js
function getDataAttrib(element, optName) {
    var dataName = "data-slider-" + optName.replace(/_/g, '-');
    var dataValString = element.getAttribute(dataName);

    try {
        return JSON.parse(dataValString);
    }
    catch(err) {
        return dataValString;
    }
}
```

**Comment by jespirit** [comment]
Found it. JSON expects double quotes for keys and strings, single quotes are not allowed.

https://stackoverflow.com/questions/14355655/jquery-parsejson-single-quote-vs-double-quote

Fix:

https://jsfiddle.net/zeuwgcLy/6/

**Comment by Fenny** [comment]
@jespirit nice catch man, any idea how we can adjust the parse function to accept single or no quotes?
