### ISSUE TITLE
Feture request: a slider that allows outer min/max values

### ISSUE THREAD

**Issue by robsch** [seiyria/bootstrap-slider#894]
I would like to show a slider with values from 0 to 100. However, the user should only be able to choose values between 20 and 80. So min/max would be 20/80. Then there are ranges from 0 to 19 and 81 to 100 where one cannot put the handle to (not to be confused with the default meaning of 'range' with this control). 

Ideally there should be configuration settings like outerMin/outerMax. Shouldn't be too hard to implement, I guess. What do you think?

What would be a workaround for now? Checking and canceling slider events?

**Comment by seiyria** [comment]
You could already do this by blocking the event that changes the slider, and this is the way I would recommend doing this.

**Comment by jespirit** [comment]
Here's an example of how you can do it.

https://jsfiddle.net/g64m7r9s/

**Comment by robsch** [comment]
The event blocking is actually sufficient. 

@jespirit Thank you for this example!
