### ISSUE TITLE
Wrong change detection for range change event

### ISSUE THREAD

**Issue by ViceIce** [seiyria/bootstrap-slider#898]
Wrong change detection on line 962:

https://github.com/seiyria/bootstrap-slider/blob/d41fa60264f5177a9c4e646b8a8a641b44e1cda2/src/js/bootstrap-slider.js#L960-L973

`&&` should be `||`, otherwise hasChanged is always false if only one value has changed.

I can send a PR if required.

**Comment by ViceIce** [comment]
This was introduces with by PR #879

**Comment by ViceIce** [comment]
And is related to #878

**Comment by ViceIce** [comment]
Ups, #897 was opened a few minutes before mine :joy:

**Comment by jespirit** [comment]
Wow, just a few minutes apart.
