### ISSUE TITLE
locksToTicks is not a known property of mv-slider

### ISSUE THREAD

**Issue by shreeshmishra28** [seiyria/bootstrap-slider#908]
Issues
=============
**NOTE:** Before filing a new issue, please search through the open issues list and check to see if an existing issue already exists that describes your problem. If so, leave a comment within that issue with the checklist items described below.

Please make sure you include the following in your issue report where appropriate:

- [ ] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug
- [ ] Instructions to replicate the bug in the Fiddle

**Comment by seiyria** [comment]
You need to provide an example. This doesn't sound like our library so you should open an issue an their repository.
