### ISSUE TITLE
Ability to drag the range

### ISSUE THREAD

**Issue by PBrockmann** [seiyria/bootstrap-slider#912]
Is there a way to drag the range as explained in
https://stackoverflow.com/questions/5955343/drag-the-range-of-a-ui-input-range-slider/6095941#6095941 ?

**Comment by jespirit** [comment]
This feature is not implemented. That feature was mentioned 4 years ago:  https://github.com/seiyria/bootstrap-slider/issues/173

**Comment by seiyria** [comment]
That is open still, so I will close this as a duplicate.
