### ISSUE TITLE
$(el).slider() returns undefined if target element does not exist in DOM

### ISSUE THREAD

**Issue by ollycross** [seiyria/bootstrap-slider#916]
Fiddle: https://jsfiddle.net/aduw6L0p/

Bootstrap Slider v10.6.1
Jquery v3.3.1
Tested using Chrome v72

__Description__
If you call `slider()` on a jQuery object which has matched no elements, it will return `undefined` which will break chaining.

__Steps to reproduce__
- Call `slider()` on a jQuery object which contains no elements
- Examine the returned value

__Expected behaviour__
The return value should be an empty jQuery object, the same as if you had called `$()`.  This would allow safe chaining with further jQuery functions such as `on()` regardless of whether the element has been matched or not.

__Actual behaviour__
The return value is `undefined` and calling other jQuery functions will throw an error.  The original object is unchanged (i.e. what you called `.slider()` on is unchanged.

**Comment by ollycross** [comment]
Should note - as a workaround (as demonstrated in the fiddle) you can still attach events without chaining them:

```
const $el = $('#iDontExist');
$el.slider() // returns undefined
$el.on('slide', handleSlide);
```
Works fine, whether or not `#iDontExist` is present in DOM.

**Comment by ollycross** [comment]
Upon investigation this may be an error with `Bridget` implementation in `bootstrap-slider`.

I'm not sure how you handle this dependency as it is bundled into the main `src/bootstrap-slider.js` file.  I've created a pull request which fixes the issue: https://github.com/seiyria/bootstrap-slider/pull/917

**Comment by jespirit** [comment]
Issue fixed. Closing.
