### ISSUE TITLE
wai-aria : slider need aria-labelled-by or aria-label

### ISSUE THREAD

**Issue by Shnoulle** [seiyria/bootstrap-slider#920]
Issues : [wai-aria-practice for slider](https://www.w3.org/TR/wai-aria-practices/#slider)
> If the slider has a visible label, it is referenced by aria-labelledby on the slider element. Otherwise, the slider element has a label provided by aria-label. 

There are system to set it after, but it can be great to have directly in options.

- [x] JSFiddle (or an equivalent such as CodePen, Plunker, etc) with the an example demonstrating the bug : https://jsfiddle.net/rx3f1bvz/1/ for a way to add it after creation.
- [ ] Instructions to replicate the bug in the Fiddle

Option can be label or labelled-by . Don't think need to get a default if original input have a label ?

**Comment by Shnoulle** [comment]
Updated … label on the slider : https://jsfiddle.net/2uLegs98/

**Comment by jespirit** [comment]
You can set an option for `labelledby` for the slider thumb(s).

https://github.com/seiyria/bootstrap-slider#options

![image](https://user-images.githubusercontent.com/5477929/56073545-16b41180-5d74-11e9-97a6-dad5d2abfc40.png)

**Comment by Shnoulle** [comment]
Oups … sorry
