### ISSUE TITLE
Are there a solution for hold both slider handles in range option

### ISSUE THREAD

**Issue by alonsoct00** [seiyria/bootstrap-slider#924]
I need to apply a limit for both slider-handles in the range control, i.e. do not pass or cross each other... like the jquery slider UI that the both handles stops the slide behavior, and never cross.

https://jqueryui.com/slider/#range

I make a codepen with my code using bootstrap-slider

https://codepen.io/alonsoct00/pen/xojLdE

Thanks

**Comment by seiyria** [comment]
You would have to watch the `slideStop` event and `return false` if the values cross. You can check `value[0] > value[1]` in that function and it should work for your purposes.

**Comment by alonsoct00** [comment]
Thanks

**Comment by alonsoct00** [comment]
@seiyria I trying but doesn't works

rangeSlider.on('change', function() {
                    var minv = rangeSlider.data('slider-min');
                        maxv = rangeSlider.data('slider-max');
                    if (maxv == minv) {
                      $(this).setValue(maxv, false, false);
                      $(this).stopSlide();
                    }
                    else if (minv == maxv) {
                      $(this).setValue(minv, false, false);
                      $(this).stopSlide();
                    }
                  });

What am I doing wrong?

Thanks

**Comment by alonsoct00** [comment]
I updated my script but doesn't works 

          $(this).on("slideStop", function() {
                    var  rangeVal = $(this).val();
                    var splitRange = rangeVal.split(',');
                    var check0 = splitRange[0];
                    var check1 = splitRange[1];
                     if (check0 == check1) {

                         return false;
                   
                    }
               });


please help me

**Comment by seiyria** [comment]
I saw you had opened a stackoverflows question so I will defer to that. Sorry!
