### ISSUE TITLE
Tooltip: allow adding html output in formatter

### ISSUE THREAD

**Issue by klihelp** [seiyria/bootstrap-slider#929]

**Comment by seiyria** [comment]
Related: https://github.com/seiyria/angular-bootstrap-slider/issues/97

For your needs, it is recommended to style a particular sliders tooltip directly with CSS (if you're putting enough information in there to need more space, you probably shouldnt be using a tooltip)

**Comment by klihelp** [comment]
My usecase is to display an image inside the tooltip.
