### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by cavie78** [seiyria/bootstrap-slider#933]
It looks like boostrap-slider doesn't work in IE11? I'm sure it *did* a few months ago?

**Comment by seiyria** [comment]
Posting an error/stack trace would help immensely.

**Comment by cavie78** [comment]
The error is that the slider element doesn't display in IE11

**Comment by cavie78** [comment]
My bad! Sorry, must be something I'm doing - the examples page works in IE11
