### ISSUE TITLE
Feature Request: single tick support

### ISSUE THREAD

**Issue by neno--** [seiyria/bootstrap-slider#938]
It would be great if only one tick would be possible. This one tick is useful when you need to position something with a slider. 
In such a scenario, this one value is useful, while others (eg min and max) are not particularly useful and should not be marked as ticks. So you try to position your object, but only default should be middle, and you want to make it easy for the slider to snap to it.

There is a workaround for this in https://github.com/seiyria/bootstrap-slider/issues/861, but
this works poorly with `ticks_snap_bounds` because it snaps to some value not visible in the slider.

Example: https://jsfiddle.net/3jma681w/

**Comment by seiyria** [comment]
This doesn't really appear useful from a slider perspective. If you're worried about positioning something, you may just want to use CSS.
