### ISSUE TITLE
Why sliders in not in 100% length?

### ISSUE THREAD

**Issue by ayoubkhan558** [seiyria/bootstrap-slider#944]
I tried slider, But its not in full length, It should exapdn to 100% width, So it will be responsive too,
![image](https://user-images.githubusercontent.com/20210961/83928154-2a0c1280-a7a8-11ea-805e-93f959f4ed45.png)

**Comment by seiyria** [comment]
This is something you can do yourself with CSS. At this time, I'm not sure if we have plans to change this.

**Comment by Ignatus** [comment]
I agree, for example for a slider horizontal, i don't understand following lines : 
`.slider.slider-horizontal {
  width: 210px;
  height: 20px;
}
`
Why a hard width ?
Overwrite slider, slider-track, etc.. ok we can do that but..
