### ISSUE TITLE
Issues when using class for slider event handle

### ISSUE THREAD

**Issue by Nugjii** [seiyria/bootstrap-slider#949]
I am try to handle slider events by class attribute because of multiple and dynamic propose.
It is not working on select by class like follow:

```
$(".priceSlider").slider().on('slide', function(){     
  v = $(this).data('slider').getValue(); 
  console.log(v);
});
```

Selecting by id attribute is working fine. 
I have created a JSFiddle for this here:
[https://jsfiddle.net/mq87gnay/1/](https://jsfiddle.net/mq87gnay/1/)

**Comment by KRI2635** [comment]
Hey Nugjii
You need to remove .slider()
Like
`$(".priceSlider").slider({});

$(".priceSlider").on('slide', function(){     
  v = $(this).data('slider').getValue();     
  $(".price-min").val(v[0]);
  $(".price-max").val(v[1]);
});`

**Comment by chamilagunawardana** [comment]
Hello Kenya69,
I have done remove slider and then call event, but still it wont work.
Me to need to call event using class instead of id. Do we have any alternate way.
@Nugjii did you find solution for that.

Regards,
Chamila

**Comment by Nugjii** [comment]
Thanks, @Kenya69

@chamilagunawardana 
I have created a working JSFiddle for this here:
https://jsfiddle.net/5wf98j4r/
