### ISSUE TITLE
Min & max description on vertical slider in JSON object? 

### ISSUE THREAD

**Issue by louisedennevi** [seiyria/bootstrap-slider#951]
Hi, I'm using surveyJS and bootstrap-slider in JSON object. I've used the vertical slider and want to add a min and max description but not sure how to implement this. 

Is this possible? I've created a sandbox to show my code, and I would like to have de option to have min and max description in the JSON object.

thanks!

https://codesandbox.io/s/survey-pigk5?file=/src/components/HelloWorld.vue

**Comment by seiyria** [comment]
You may want to ask the creator of the vue wrapper. With the base bootstrap-slider there is no problem using `formatter` to describe the value of the knob.
