### ISSUE TITLE
Example 2 : How can I move the tooltip value to external one?

### ISSUE THREAD

**Issue by devhoussam** [seiyria/bootstrap-slider#954]
I want to move the tooltip value to external value :

**Example 2 | Filter by price interval :**

**HTML**

```
<b class="min">$ 10</b> 
<input id="example2" type="text" data-slider-min="0" data-slider-max="2000" data-slider-step="1" data-slider-value="14" data-slider-tooltip="hide" /> 
<b class="max">$ 1000</b>
```

**JavaScript**

`var slider = new Slider('#example2', {});`

**Comment by seiyria** [comment]
I'm not sure what you mean by "external value" but the [change](https://github.com/seiyria/bootstrap-slider#events) event might help you, as well as the [setValue](https://github.com/seiyria/bootstrap-slider#functions) function. If you need more help, please create a descriptive jsfiddle with what you're trying and what you want to do.
