### ISSUE TITLE
How can I custom the range slider CSS style that generated by JS?

### ISSUE THREAD

**Issue by devhoussam** [seiyria/bootstrap-slider#955]
I want to custom the` .slider-handle.max-slider-handle {}` CSS Style

Here is the result that I want to achieve :

![Image of Yaktocat](https://i.imgur.com/47wtKkR.png)

instead of `left: 100%;` in `.slider-handle.max-slider-handle {}` I want to add only `left: 95%;`

I already tried to add my own custom CSS by declaring the class in CSS but this style it generated by JS how can I change it?

**Comment by seiyria** [comment]
You can always use CSS and !important to do this. It's not ideal, but in general we try not to make styles you need to override like that. Given that this is the slider knob, you want it to be in the right position. You probably instead want to move the entire slider over 5%? Either way; CSS can be used here.

**Comment by devhoussam** [comment]
I already try to this but not working the JS remove the CSS Style .....
