### ISSUE TITLE
Rails 6.+ version not supporting from gem file.

### ISSUE THREAD

**Issue by venkatnr** [seiyria/bootstrap-slider#956]
When am updating my project from 5.2.4.4 to 6.0.3.4 am getting 

Could not find gem 'bootstrap-slider-rails (~> 11.0.2)' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache.

**railties < 6.0, >= 3.2**

so how to use bootstrap-slider in rails 6 application, or is there any alternative to bootstrap-slider gem.

**Comment by seiyria** [comment]
We don't directly support rails. You should ask on their github issue tracker.
