### ISSUE TITLE
Bootstrap 4.5?

### ISSUE THREAD

**Issue by cal-zone** [seiyria/bootstrap-slider#957]
As far as I can tell, this is completely non-functional on Bootstrap 4.5

I realize the docs say it's for Bootstrap 4… but that leaves open the question about whether it's a minimum, maximum, or exact requirement. The wording makes it sound as if 4 is the minimum. 

But anything 4.x is an open question.

**Comment by seiyria** [comment]
I'm not sure what you mean. We have no direct dependency on bootstrap; visually it matches bootstrap 3 and 4, that's all. If something is nonfunctional you should create an example of what's broken.

**Comment by cal-zone** [comment]
Ok, then it's simply nonfunctional, period.

I disabled all js except jquery and bootstrap 4.5 js

The bootstrap-slider widget displays with no layout… rather, to be accurate: zero height. Its invisible.

I can "access" it by clicking and dragging the general area in the document where I know it should be and the tooltip flickers and flashes and it can sort of be dragged to vast extremes (exceeding the container it's supposed to be inside).

I can't imagine what it is conflicting with other than bootstrap 4.5 css itself.

**Comment by seiyria** [comment]
You'll need to provide a jsfiddle or similar then, as stated previously.
