### ISSUE TITLE
DevTools failed to load source map: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by paulvancity** [seiyria/bootstrap-slider#963]
Getting this error when loading.

DevTools failed to load source map: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Thank you.

**Comment by seiyria** [comment]
This isn't anything we have control over.

**Comment by capegreg** [comment]
sourceMappingURL is expected, but the minify build is not producing it in dist/

https://cdn.jsdelivr.net/npm/bootstrap-slider@11.0.2/dist/css/bootstrap-slider.min.css
/*# sourceMappingURL=bootstrap-slider.min.css.map */
